// Code generated by ent, DO NOT EDIT.

package availabilitydraft

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/betallsoph/shiftz/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldLTE(FieldID, id))
}

// ShopID applies equality check predicate on the "shop_id" field. It's identical to ShopIDEQ.
func ShopID(v uuid.UUID) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldEQ(FieldShopID, v))
}

// EmployeeID applies equality check predicate on the "employee_id" field. It's identical to EmployeeIDEQ.
func EmployeeID(v uuid.UUID) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldEQ(FieldEmployeeID, v))
}

// TelegramUserID applies equality check predicate on the "telegram_user_id" field. It's identical to TelegramUserIDEQ.
func TelegramUserID(v int64) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldEQ(FieldTelegramUserID, v))
}

// ChatID applies equality check predicate on the "chat_id" field. It's identical to ChatIDEQ.
func ChatID(v int64) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldEQ(FieldChatID, v))
}

// WeekStart applies equality check predicate on the "week_start" field. It's identical to WeekStartEQ.
func WeekStart(v time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldEQ(FieldWeekStart, v))
}

// Timezone applies equality check predicate on the "timezone" field. It's identical to TimezoneEQ.
func Timezone(v string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldEQ(FieldTimezone, v))
}

// RawMessage applies equality check predicate on the "raw_message" field. It's identical to RawMessageEQ.
func RawMessage(v string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldEQ(FieldRawMessage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldEQ(FieldCreatedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldEQ(FieldExpiresAt, v))
}

// ShopIDEQ applies the EQ predicate on the "shop_id" field.
func ShopIDEQ(v uuid.UUID) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldEQ(FieldShopID, v))
}

// ShopIDNEQ applies the NEQ predicate on the "shop_id" field.
func ShopIDNEQ(v uuid.UUID) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldNEQ(FieldShopID, v))
}

// ShopIDIn applies the In predicate on the "shop_id" field.
func ShopIDIn(vs ...uuid.UUID) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldIn(FieldShopID, vs...))
}

// ShopIDNotIn applies the NotIn predicate on the "shop_id" field.
func ShopIDNotIn(vs ...uuid.UUID) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldNotIn(FieldShopID, vs...))
}

// EmployeeIDEQ applies the EQ predicate on the "employee_id" field.
func EmployeeIDEQ(v uuid.UUID) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldEQ(FieldEmployeeID, v))
}

// EmployeeIDNEQ applies the NEQ predicate on the "employee_id" field.
func EmployeeIDNEQ(v uuid.UUID) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldNEQ(FieldEmployeeID, v))
}

// EmployeeIDIn applies the In predicate on the "employee_id" field.
func EmployeeIDIn(vs ...uuid.UUID) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldIn(FieldEmployeeID, vs...))
}

// EmployeeIDNotIn applies the NotIn predicate on the "employee_id" field.
func EmployeeIDNotIn(vs ...uuid.UUID) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldNotIn(FieldEmployeeID, vs...))
}

// TelegramUserIDEQ applies the EQ predicate on the "telegram_user_id" field.
func TelegramUserIDEQ(v int64) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldEQ(FieldTelegramUserID, v))
}

// TelegramUserIDNEQ applies the NEQ predicate on the "telegram_user_id" field.
func TelegramUserIDNEQ(v int64) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldNEQ(FieldTelegramUserID, v))
}

// TelegramUserIDIn applies the In predicate on the "telegram_user_id" field.
func TelegramUserIDIn(vs ...int64) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldIn(FieldTelegramUserID, vs...))
}

// TelegramUserIDNotIn applies the NotIn predicate on the "telegram_user_id" field.
func TelegramUserIDNotIn(vs ...int64) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldNotIn(FieldTelegramUserID, vs...))
}

// TelegramUserIDGT applies the GT predicate on the "telegram_user_id" field.
func TelegramUserIDGT(v int64) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldGT(FieldTelegramUserID, v))
}

// TelegramUserIDGTE applies the GTE predicate on the "telegram_user_id" field.
func TelegramUserIDGTE(v int64) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldGTE(FieldTelegramUserID, v))
}

// TelegramUserIDLT applies the LT predicate on the "telegram_user_id" field.
func TelegramUserIDLT(v int64) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldLT(FieldTelegramUserID, v))
}

// TelegramUserIDLTE applies the LTE predicate on the "telegram_user_id" field.
func TelegramUserIDLTE(v int64) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldLTE(FieldTelegramUserID, v))
}

// ChatIDEQ applies the EQ predicate on the "chat_id" field.
func ChatIDEQ(v int64) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldEQ(FieldChatID, v))
}

// ChatIDNEQ applies the NEQ predicate on the "chat_id" field.
func ChatIDNEQ(v int64) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldNEQ(FieldChatID, v))
}

// ChatIDIn applies the In predicate on the "chat_id" field.
func ChatIDIn(vs ...int64) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldIn(FieldChatID, vs...))
}

// ChatIDNotIn applies the NotIn predicate on the "chat_id" field.
func ChatIDNotIn(vs ...int64) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldNotIn(FieldChatID, vs...))
}

// ChatIDGT applies the GT predicate on the "chat_id" field.
func ChatIDGT(v int64) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldGT(FieldChatID, v))
}

// ChatIDGTE applies the GTE predicate on the "chat_id" field.
func ChatIDGTE(v int64) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldGTE(FieldChatID, v))
}

// ChatIDLT applies the LT predicate on the "chat_id" field.
func ChatIDLT(v int64) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldLT(FieldChatID, v))
}

// ChatIDLTE applies the LTE predicate on the "chat_id" field.
func ChatIDLTE(v int64) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldLTE(FieldChatID, v))
}

// WeekStartEQ applies the EQ predicate on the "week_start" field.
func WeekStartEQ(v time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldEQ(FieldWeekStart, v))
}

// WeekStartNEQ applies the NEQ predicate on the "week_start" field.
func WeekStartNEQ(v time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldNEQ(FieldWeekStart, v))
}

// WeekStartIn applies the In predicate on the "week_start" field.
func WeekStartIn(vs ...time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldIn(FieldWeekStart, vs...))
}

// WeekStartNotIn applies the NotIn predicate on the "week_start" field.
func WeekStartNotIn(vs ...time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldNotIn(FieldWeekStart, vs...))
}

// WeekStartGT applies the GT predicate on the "week_start" field.
func WeekStartGT(v time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldGT(FieldWeekStart, v))
}

// WeekStartGTE applies the GTE predicate on the "week_start" field.
func WeekStartGTE(v time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldGTE(FieldWeekStart, v))
}

// WeekStartLT applies the LT predicate on the "week_start" field.
func WeekStartLT(v time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldLT(FieldWeekStart, v))
}

// WeekStartLTE applies the LTE predicate on the "week_start" field.
func WeekStartLTE(v time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldLTE(FieldWeekStart, v))
}

// TimezoneEQ applies the EQ predicate on the "timezone" field.
func TimezoneEQ(v string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldEQ(FieldTimezone, v))
}

// TimezoneNEQ applies the NEQ predicate on the "timezone" field.
func TimezoneNEQ(v string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldNEQ(FieldTimezone, v))
}

// TimezoneIn applies the In predicate on the "timezone" field.
func TimezoneIn(vs ...string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldIn(FieldTimezone, vs...))
}

// TimezoneNotIn applies the NotIn predicate on the "timezone" field.
func TimezoneNotIn(vs ...string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldNotIn(FieldTimezone, vs...))
}

// TimezoneGT applies the GT predicate on the "timezone" field.
func TimezoneGT(v string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldGT(FieldTimezone, v))
}

// TimezoneGTE applies the GTE predicate on the "timezone" field.
func TimezoneGTE(v string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldGTE(FieldTimezone, v))
}

// TimezoneLT applies the LT predicate on the "timezone" field.
func TimezoneLT(v string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldLT(FieldTimezone, v))
}

// TimezoneLTE applies the LTE predicate on the "timezone" field.
func TimezoneLTE(v string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldLTE(FieldTimezone, v))
}

// TimezoneContains applies the Contains predicate on the "timezone" field.
func TimezoneContains(v string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldContains(FieldTimezone, v))
}

// TimezoneHasPrefix applies the HasPrefix predicate on the "timezone" field.
func TimezoneHasPrefix(v string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldHasPrefix(FieldTimezone, v))
}

// TimezoneHasSuffix applies the HasSuffix predicate on the "timezone" field.
func TimezoneHasSuffix(v string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldHasSuffix(FieldTimezone, v))
}

// TimezoneEqualFold applies the EqualFold predicate on the "timezone" field.
func TimezoneEqualFold(v string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldEqualFold(FieldTimezone, v))
}

// TimezoneContainsFold applies the ContainsFold predicate on the "timezone" field.
func TimezoneContainsFold(v string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldContainsFold(FieldTimezone, v))
}

// RawMessageEQ applies the EQ predicate on the "raw_message" field.
func RawMessageEQ(v string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldEQ(FieldRawMessage, v))
}

// RawMessageNEQ applies the NEQ predicate on the "raw_message" field.
func RawMessageNEQ(v string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldNEQ(FieldRawMessage, v))
}

// RawMessageIn applies the In predicate on the "raw_message" field.
func RawMessageIn(vs ...string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldIn(FieldRawMessage, vs...))
}

// RawMessageNotIn applies the NotIn predicate on the "raw_message" field.
func RawMessageNotIn(vs ...string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldNotIn(FieldRawMessage, vs...))
}

// RawMessageGT applies the GT predicate on the "raw_message" field.
func RawMessageGT(v string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldGT(FieldRawMessage, v))
}

// RawMessageGTE applies the GTE predicate on the "raw_message" field.
func RawMessageGTE(v string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldGTE(FieldRawMessage, v))
}

// RawMessageLT applies the LT predicate on the "raw_message" field.
func RawMessageLT(v string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldLT(FieldRawMessage, v))
}

// RawMessageLTE applies the LTE predicate on the "raw_message" field.
func RawMessageLTE(v string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldLTE(FieldRawMessage, v))
}

// RawMessageContains applies the Contains predicate on the "raw_message" field.
func RawMessageContains(v string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldContains(FieldRawMessage, v))
}

// RawMessageHasPrefix applies the HasPrefix predicate on the "raw_message" field.
func RawMessageHasPrefix(v string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldHasPrefix(FieldRawMessage, v))
}

// RawMessageHasSuffix applies the HasSuffix predicate on the "raw_message" field.
func RawMessageHasSuffix(v string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldHasSuffix(FieldRawMessage, v))
}

// RawMessageEqualFold applies the EqualFold predicate on the "raw_message" field.
func RawMessageEqualFold(v string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldEqualFold(FieldRawMessage, v))
}

// RawMessageContainsFold applies the ContainsFold predicate on the "raw_message" field.
func RawMessageContainsFold(v string) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldContainsFold(FieldRawMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldLTE(FieldCreatedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.FieldLTE(FieldExpiresAt, v))
}

// HasShop applies the HasEdge predicate on the "shop" edge.
func HasShop() predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ShopTable, ShopColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasShopWith applies the HasEdge predicate on the "shop" edge with a given conditions (other predicates).
func HasShopWith(preds ...predicate.Shop) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(func(s *sql.Selector) {
		step := newShopStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEmployee applies the HasEdge predicate on the "employee" edge.
func HasEmployee() predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EmployeeTable, EmployeeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEmployeeWith applies the HasEdge predicate on the "employee" edge with a given conditions (other predicates).
func HasEmployeeWith(preds ...predicate.Employee) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(func(s *sql.Selector) {
		step := newEmployeeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AvailabilityDraft) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AvailabilityDraft) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AvailabilityDraft) predicate.AvailabilityDraft {
	return predicate.AvailabilityDraft(sql.NotPredicates(p))
}
