// Code generated by ent, DO NOT EDIT.

package employee

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/betallsoph/shiftz/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Employee {
	return predicate.Employee(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Employee {
	return predicate.Employee(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Employee {
	return predicate.Employee(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Employee {
	return predicate.Employee(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Employee {
	return predicate.Employee(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Employee {
	return predicate.Employee(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Employee {
	return predicate.Employee(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Employee {
	return predicate.Employee(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Employee {
	return predicate.Employee(sql.FieldLTE(FieldID, id))
}

// ShopID applies equality check predicate on the "shop_id" field. It's identical to ShopIDEQ.
func ShopID(v int) predicate.Employee {
	return predicate.Employee(sql.FieldEQ(FieldShopID, v))
}

// TelegramUserID applies equality check predicate on the "telegram_user_id" field. It's identical to TelegramUserIDEQ.
func TelegramUserID(v int64) predicate.Employee {
	return predicate.Employee(sql.FieldEQ(FieldTelegramUserID, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.Employee {
	return predicate.Employee(sql.FieldEQ(FieldDisplayName, v))
}

// MaxHoursPerWeek applies equality check predicate on the "max_hours_per_week" field. It's identical to MaxHoursPerWeekEQ.
func MaxHoursPerWeek(v float64) predicate.Employee {
	return predicate.Employee(sql.FieldEQ(FieldMaxHoursPerWeek, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.Employee {
	return predicate.Employee(sql.FieldEQ(FieldActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Employee {
	return predicate.Employee(sql.FieldEQ(FieldCreatedAt, v))
}

// ShopIDEQ applies the EQ predicate on the "shop_id" field.
func ShopIDEQ(v int) predicate.Employee {
	return predicate.Employee(sql.FieldEQ(FieldShopID, v))
}

// ShopIDNEQ applies the NEQ predicate on the "shop_id" field.
func ShopIDNEQ(v int) predicate.Employee {
	return predicate.Employee(sql.FieldNEQ(FieldShopID, v))
}

// ShopIDIn applies the In predicate on the "shop_id" field.
func ShopIDIn(vs ...int) predicate.Employee {
	return predicate.Employee(sql.FieldIn(FieldShopID, vs...))
}

// ShopIDNotIn applies the NotIn predicate on the "shop_id" field.
func ShopIDNotIn(vs ...int) predicate.Employee {
	return predicate.Employee(sql.FieldNotIn(FieldShopID, vs...))
}

// TelegramUserIDEQ applies the EQ predicate on the "telegram_user_id" field.
func TelegramUserIDEQ(v int64) predicate.Employee {
	return predicate.Employee(sql.FieldEQ(FieldTelegramUserID, v))
}

// TelegramUserIDNEQ applies the NEQ predicate on the "telegram_user_id" field.
func TelegramUserIDNEQ(v int64) predicate.Employee {
	return predicate.Employee(sql.FieldNEQ(FieldTelegramUserID, v))
}

// TelegramUserIDIn applies the In predicate on the "telegram_user_id" field.
func TelegramUserIDIn(vs ...int64) predicate.Employee {
	return predicate.Employee(sql.FieldIn(FieldTelegramUserID, vs...))
}

// TelegramUserIDNotIn applies the NotIn predicate on the "telegram_user_id" field.
func TelegramUserIDNotIn(vs ...int64) predicate.Employee {
	return predicate.Employee(sql.FieldNotIn(FieldTelegramUserID, vs...))
}

// TelegramUserIDGT applies the GT predicate on the "telegram_user_id" field.
func TelegramUserIDGT(v int64) predicate.Employee {
	return predicate.Employee(sql.FieldGT(FieldTelegramUserID, v))
}

// TelegramUserIDGTE applies the GTE predicate on the "telegram_user_id" field.
func TelegramUserIDGTE(v int64) predicate.Employee {
	return predicate.Employee(sql.FieldGTE(FieldTelegramUserID, v))
}

// TelegramUserIDLT applies the LT predicate on the "telegram_user_id" field.
func TelegramUserIDLT(v int64) predicate.Employee {
	return predicate.Employee(sql.FieldLT(FieldTelegramUserID, v))
}

// TelegramUserIDLTE applies the LTE predicate on the "telegram_user_id" field.
func TelegramUserIDLTE(v int64) predicate.Employee {
	return predicate.Employee(sql.FieldLTE(FieldTelegramUserID, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.Employee {
	return predicate.Employee(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.Employee {
	return predicate.Employee(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.Employee {
	return predicate.Employee(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.Employee {
	return predicate.Employee(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.Employee {
	return predicate.Employee(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.Employee {
	return predicate.Employee(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.Employee {
	return predicate.Employee(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.Employee {
	return predicate.Employee(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.Employee {
	return predicate.Employee(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.Employee {
	return predicate.Employee(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.Employee {
	return predicate.Employee(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.Employee {
	return predicate.Employee(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.Employee {
	return predicate.Employee(sql.FieldContainsFold(FieldDisplayName, v))
}

// MaxHoursPerWeekEQ applies the EQ predicate on the "max_hours_per_week" field.
func MaxHoursPerWeekEQ(v float64) predicate.Employee {
	return predicate.Employee(sql.FieldEQ(FieldMaxHoursPerWeek, v))
}

// MaxHoursPerWeekNEQ applies the NEQ predicate on the "max_hours_per_week" field.
func MaxHoursPerWeekNEQ(v float64) predicate.Employee {
	return predicate.Employee(sql.FieldNEQ(FieldMaxHoursPerWeek, v))
}

// MaxHoursPerWeekIn applies the In predicate on the "max_hours_per_week" field.
func MaxHoursPerWeekIn(vs ...float64) predicate.Employee {
	return predicate.Employee(sql.FieldIn(FieldMaxHoursPerWeek, vs...))
}

// MaxHoursPerWeekNotIn applies the NotIn predicate on the "max_hours_per_week" field.
func MaxHoursPerWeekNotIn(vs ...float64) predicate.Employee {
	return predicate.Employee(sql.FieldNotIn(FieldMaxHoursPerWeek, vs...))
}

// MaxHoursPerWeekGT applies the GT predicate on the "max_hours_per_week" field.
func MaxHoursPerWeekGT(v float64) predicate.Employee {
	return predicate.Employee(sql.FieldGT(FieldMaxHoursPerWeek, v))
}

// MaxHoursPerWeekGTE applies the GTE predicate on the "max_hours_per_week" field.
func MaxHoursPerWeekGTE(v float64) predicate.Employee {
	return predicate.Employee(sql.FieldGTE(FieldMaxHoursPerWeek, v))
}

// MaxHoursPerWeekLT applies the LT predicate on the "max_hours_per_week" field.
func MaxHoursPerWeekLT(v float64) predicate.Employee {
	return predicate.Employee(sql.FieldLT(FieldMaxHoursPerWeek, v))
}

// MaxHoursPerWeekLTE applies the LTE predicate on the "max_hours_per_week" field.
func MaxHoursPerWeekLTE(v float64) predicate.Employee {
	return predicate.Employee(sql.FieldLTE(FieldMaxHoursPerWeek, v))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.Employee {
	return predicate.Employee(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.Employee {
	return predicate.Employee(sql.FieldNEQ(FieldActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Employee {
	return predicate.Employee(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Employee {
	return predicate.Employee(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Employee {
	return predicate.Employee(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Employee {
	return predicate.Employee(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Employee {
	return predicate.Employee(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Employee {
	return predicate.Employee(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Employee {
	return predicate.Employee(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Employee {
	return predicate.Employee(sql.FieldLTE(FieldCreatedAt, v))
}

// HasShop applies the HasEdge predicate on the "shop" edge.
func HasShop() predicate.Employee {
	return predicate.Employee(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ShopTable, ShopColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasShopWith applies the HasEdge predicate on the "shop" edge with a given conditions (other predicates).
func HasShopWith(preds ...predicate.Shop) predicate.Employee {
	return predicate.Employee(func(s *sql.Selector) {
		step := newShopStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAvailability applies the HasEdge predicate on the "availability" edge.
func HasAvailability() predicate.Employee {
	return predicate.Employee(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AvailabilityTable, AvailabilityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAvailabilityWith applies the HasEdge predicate on the "availability" edge with a given conditions (other predicates).
func HasAvailabilityWith(preds ...predicate.Availability) predicate.Employee {
	return predicate.Employee(func(s *sql.Selector) {
		step := newAvailabilityStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAssignments applies the HasEdge predicate on the "assignments" edge.
func HasAssignments() predicate.Employee {
	return predicate.Employee(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AssignmentsTable, AssignmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssignmentsWith applies the HasEdge predicate on the "assignments" edge with a given conditions (other predicates).
func HasAssignmentsWith(preds ...predicate.ScheduleAssignment) predicate.Employee {
	return predicate.Employee(func(s *sql.Selector) {
		step := newAssignmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasVotes applies the HasEdge predicate on the "votes" edge.
func HasVotes() predicate.Employee {
	return predicate.Employee(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, VotesTable, VotesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVotesWith applies the HasEdge predicate on the "votes" edge with a given conditions (other predicates).
func HasVotesWith(preds ...predicate.ScheduleVote) predicate.Employee {
	return predicate.Employee(func(s *sql.Selector) {
		step := newVotesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Employee) predicate.Employee {
	return predicate.Employee(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Employee) predicate.Employee {
	return predicate.Employee(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Employee) predicate.Employee {
	return predicate.Employee(sql.NotPredicates(p))
}
