// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AvailabilitiesColumns holds the columns for the "availabilities" table.
	AvailabilitiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "week_start", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "slots", Type: field.TypeJSON},
		{Name: "raw_message", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "employee_id", Type: field.TypeUUID},
		{Name: "shop_id", Type: field.TypeUUID},
	}
	// AvailabilitiesTable holds the schema information for the "availabilities" table.
	AvailabilitiesTable = &schema.Table{
		Name:       "availabilities",
		Columns:    AvailabilitiesColumns,
		PrimaryKey: []*schema.Column{AvailabilitiesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "availabilities_employees_availabilities",
				Columns:    []*schema.Column{AvailabilitiesColumns[5]},
				RefColumns: []*schema.Column{EmployeesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "availabilities_shops_availabilities",
				Columns:    []*schema.Column{AvailabilitiesColumns[6]},
				RefColumns: []*schema.Column{ShopsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "availability_shop_id_employee_id_week_start",
				Unique:  true,
				Columns: []*schema.Column{AvailabilitiesColumns[6], AvailabilitiesColumns[5], AvailabilitiesColumns[1]},
			},
			{
				Name:    "availability_shop_id_week_start",
				Unique:  false,
				Columns: []*schema.Column{AvailabilitiesColumns[6], AvailabilitiesColumns[1]},
			},
		},
	}
	// AvailabilityDraftsColumns holds the columns for the "availability_drafts" table.
	AvailabilityDraftsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "telegram_user_id", Type: field.TypeInt64},
		{Name: "chat_id", Type: field.TypeInt64},
		{Name: "week_start", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "timezone", Type: field.TypeString},
		{Name: "slots", Type: field.TypeJSON},
		{Name: "raw_message", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "employee_id", Type: field.TypeUUID},
		{Name: "shop_id", Type: field.TypeUUID},
	}
	// AvailabilityDraftsTable holds the schema information for the "availability_drafts" table.
	AvailabilityDraftsTable = &schema.Table{
		Name:       "availability_drafts",
		Columns:    AvailabilityDraftsColumns,
		PrimaryKey: []*schema.Column{AvailabilityDraftsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "availability_drafts_employees_availability_drafts",
				Columns:    []*schema.Column{AvailabilityDraftsColumns[9]},
				RefColumns: []*schema.Column{EmployeesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "availability_drafts_shops_availability_drafts",
				Columns:    []*schema.Column{AvailabilityDraftsColumns[10]},
				RefColumns: []*schema.Column{ShopsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "availabilitydraft_expires_at",
				Unique:  false,
				Columns: []*schema.Column{AvailabilityDraftsColumns[8]},
			},
			{
				Name:    "availabilitydraft_telegram_user_id_expires_at",
				Unique:  false,
				Columns: []*schema.Column{AvailabilityDraftsColumns[1], AvailabilityDraftsColumns[8]},
			},
		},
	}
	// EmployeesColumns holds the columns for the "employees" table.
	EmployeesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "telegram_user_id", Type: field.TypeInt64},
		{Name: "display_name", Type: field.TypeString},
		{Name: "role", Type: field.TypeString, Default: ""},
		{Name: "max_hours_per_week", Type: field.TypeFloat64, Default: 40},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "shop_id", Type: field.TypeUUID},
	}
	// EmployeesTable holds the schema information for the "employees" table.
	EmployeesTable = &schema.Table{
		Name:       "employees",
		Columns:    EmployeesColumns,
		PrimaryKey: []*schema.Column{EmployeesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "employees_shops_employees",
				Columns:    []*schema.Column{EmployeesColumns[7]},
				RefColumns: []*schema.Column{ShopsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "employee_shop_id_telegram_user_id",
				Unique:  true,
				Columns: []*schema.Column{EmployeesColumns[7], EmployeesColumns[1]},
			},
			{
				Name:    "employee_shop_id_is_active",
				Unique:  false,
				Columns: []*schema.Column{EmployeesColumns[7], EmployeesColumns[5]},
			},
			{
				Name:    "employee_telegram_user_id",
				Unique:  false,
				Columns: []*schema.Column{EmployeesColumns[1]},
			},
		},
	}
	// ReminderDeliveriesColumns holds the columns for the "reminder_deliveries" table.
	ReminderDeliveriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "week_start", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "kind", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "sent", "failed"}, Default: "pending"},
		{Name: "attempts", Type: field.TypeInt, Default: 0},
		{Name: "last_error", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "sent_at", Type: field.TypeTime, Nullable: true},
		{Name: "employee_id", Type: field.TypeUUID},
		{Name: "shop_id", Type: field.TypeUUID},
	}
	// ReminderDeliveriesTable holds the schema information for the "reminder_deliveries" table.
	ReminderDeliveriesTable = &schema.Table{
		Name:       "reminder_deliveries",
		Columns:    ReminderDeliveriesColumns,
		PrimaryKey: []*schema.Column{ReminderDeliveriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "reminder_deliveries_employees_reminder_deliveries",
				Columns:    []*schema.Column{ReminderDeliveriesColumns[8]},
				RefColumns: []*schema.Column{EmployeesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "reminder_deliveries_shops_reminder_deliveries",
				Columns:    []*schema.Column{ReminderDeliveriesColumns[9]},
				RefColumns: []*schema.Column{ShopsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "reminderdelivery_shop_id_employee_id_week_start_kind",
				Unique:  true,
				Columns: []*schema.Column{ReminderDeliveriesColumns[9], ReminderDeliveriesColumns[8], ReminderDeliveriesColumns[1], ReminderDeliveriesColumns[2]},
			},
			{
				Name:    "reminderdelivery_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{ReminderDeliveriesColumns[3], ReminderDeliveriesColumns[6]},
			},
		},
	}
	// RulesColumns holds the columns for the "rules" table.
	RulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "description", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "rule_json", Type: field.TypeJSON, Nullable: true},
		{Name: "weight", Type: field.TypeFloat64, Default: 1},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "shop_id", Type: field.TypeUUID},
	}
	// RulesTable holds the schema information for the "rules" table.
	RulesTable = &schema.Table{
		Name:       "rules",
		Columns:    RulesColumns,
		PrimaryKey: []*schema.Column{RulesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "rules_shops_rules",
				Columns:    []*schema.Column{RulesColumns[6]},
				RefColumns: []*schema.Column{ShopsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "rule_shop_id_is_active",
				Unique:  false,
				Columns: []*schema.Column{RulesColumns[6], RulesColumns[4]},
			},
		},
	}
	// SchedulesColumns holds the columns for the "schedules" table.
	SchedulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "week_start", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"draft", "voting", "approved", "published"}, Default: "draft"},
		{Name: "variant_label", Type: field.TypeString, Default: ""},
		{Name: "score", Type: field.TypeFloat64, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "shop_id", Type: field.TypeUUID},
	}
	// SchedulesTable holds the schema information for the "schedules" table.
	SchedulesTable = &schema.Table{
		Name:       "schedules",
		Columns:    SchedulesColumns,
		PrimaryKey: []*schema.Column{SchedulesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "schedules_shops_schedules",
				Columns:    []*schema.Column{SchedulesColumns[6]},
				RefColumns: []*schema.Column{ShopsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "schedule_shop_id_week_start",
				Unique:  false,
				Columns: []*schema.Column{SchedulesColumns[6], SchedulesColumns[1]},
			},
			{
				Name:    "schedule_shop_id_week_start_variant_label",
				Unique:  true,
				Columns: []*schema.Column{SchedulesColumns[6], SchedulesColumns[1], SchedulesColumns[3]},
			},
		},
	}
	// ScheduleAssignmentsColumns holds the columns for the "schedule_assignments" table.
	ScheduleAssignmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "date", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "employee_id", Type: field.TypeUUID},
		{Name: "schedule_id", Type: field.TypeUUID},
		{Name: "shop_id", Type: field.TypeUUID},
		{Name: "shift_id", Type: field.TypeUUID},
	}
	// ScheduleAssignmentsTable holds the schema information for the "schedule_assignments" table.
	ScheduleAssignmentsTable = &schema.Table{
		Name:       "schedule_assignments",
		Columns:    ScheduleAssignmentsColumns,
		PrimaryKey: []*schema.Column{ScheduleAssignmentsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "schedule_assignments_employees_assignments",
				Columns:    []*schema.Column{ScheduleAssignmentsColumns[2]},
				RefColumns: []*schema.Column{EmployeesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "schedule_assignments_schedules_assignments",
				Columns:    []*schema.Column{ScheduleAssignmentsColumns[3]},
				RefColumns: []*schema.Column{SchedulesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "schedule_assignments_shops_shop",
				Columns:    []*schema.Column{ScheduleAssignmentsColumns[4]},
				RefColumns: []*schema.Column{ShopsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "schedule_assignments_shifts_assignments",
				Columns:    []*schema.Column{ScheduleAssignmentsColumns[5]},
				RefColumns: []*schema.Column{ShiftsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "scheduleassignment_shop_id_schedule_id",
				Unique:  false,
				Columns: []*schema.Column{ScheduleAssignmentsColumns[4], ScheduleAssignmentsColumns[3]},
			},
			{
				Name:    "scheduleassignment_shop_id_employee_id_date",
				Unique:  false,
				Columns: []*schema.Column{ScheduleAssignmentsColumns[4], ScheduleAssignmentsColumns[2], ScheduleAssignmentsColumns[1]},
			},
		},
	}
	// ScheduleVotesColumns holds the columns for the "schedule_votes" table.
	ScheduleVotesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "week_start", Type: field.TypeTime, SchemaType: map[string]string{"postgres": "date"}},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "employee_id", Type: field.TypeUUID},
		{Name: "schedule_id", Type: field.TypeUUID},
		{Name: "shop_id", Type: field.TypeUUID},
	}
	// ScheduleVotesTable holds the schema information for the "schedule_votes" table.
	ScheduleVotesTable = &schema.Table{
		Name:       "schedule_votes",
		Columns:    ScheduleVotesColumns,
		PrimaryKey: []*schema.Column{ScheduleVotesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "schedule_votes_employees_votes",
				Columns:    []*schema.Column{ScheduleVotesColumns[3]},
				RefColumns: []*schema.Column{EmployeesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "schedule_votes_schedules_votes",
				Columns:    []*schema.Column{ScheduleVotesColumns[4]},
				RefColumns: []*schema.Column{SchedulesColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "schedule_votes_shops_shop",
				Columns:    []*schema.Column{ScheduleVotesColumns[5]},
				RefColumns: []*schema.Column{ShopsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "schedulevote_shop_id_employee_id_week_start",
				Unique:  true,
				Columns: []*schema.Column{ScheduleVotesColumns[5], ScheduleVotesColumns[3], ScheduleVotesColumns[1]},
			},
			{
				Name:    "schedulevote_shop_id_schedule_id",
				Unique:  false,
				Columns: []*schema.Column{ScheduleVotesColumns[5], ScheduleVotesColumns[4]},
			},
		},
	}
	// ShiftsColumns holds the columns for the "shifts" table.
	ShiftsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "weekday", Type: field.TypeInt},
		{Name: "start_time", Type: field.TypeString},
		{Name: "end_time", Type: field.TypeString},
		{Name: "min_staff", Type: field.TypeInt, Default: 1},
		{Name: "max_staff", Type: field.TypeInt, Default: 1},
		{Name: "is_active", Type: field.TypeBool, Default: true},
		{Name: "shop_id", Type: field.TypeUUID},
	}
	// ShiftsTable holds the schema information for the "shifts" table.
	ShiftsTable = &schema.Table{
		Name:       "shifts",
		Columns:    ShiftsColumns,
		PrimaryKey: []*schema.Column{ShiftsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "shifts_shops_shifts",
				Columns:    []*schema.Column{ShiftsColumns[8]},
				RefColumns: []*schema.Column{ShopsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// ShopsColumns holds the columns for the "shops" table.
	ShopsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "timezone", Type: field.TypeString, Default: "UTC"},
		{Name: "invite_code", Type: field.TypeString, Unique: true},
		{Name: "telegram_group_id", Type: field.TypeInt64},
		{Name: "telegram_team_chat_id", Type: field.TypeInt64, Nullable: true},
		{Name: "owner_telegram_id", Type: field.TypeInt64, Nullable: true},
		{Name: "owner_link_token_hash", Type: field.TypeString, Nullable: true},
		{Name: "owner_link_token_expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "plan", Type: field.TypeString, Default: "free"},
		{Name: "dashboard_token_hash", Type: field.TypeString, Nullable: true},
		{Name: "dashboard_username", Type: field.TypeString, Nullable: true},
		{Name: "dashboard_password_hash", Type: field.TypeString, Nullable: true},
		{Name: "dashboard_email", Type: field.TypeString, Nullable: true},
		{Name: "dashboard_password_hint", Type: field.TypeString, Nullable: true},
		{Name: "dashboard_password_reset_hash", Type: field.TypeString, Nullable: true},
		{Name: "dashboard_password_reset_expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ShopsTable holds the schema information for the "shops" table.
	ShopsTable = &schema.Table{
		Name:       "shops",
		Columns:    ShopsColumns,
		PrimaryKey: []*schema.Column{ShopsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "shop_dashboard_username",
				Unique:  true,
				Columns: []*schema.Column{ShopsColumns[11]},
			},
			{
				Name:    "shop_owner_telegram_id",
				Unique:  true,
				Columns: []*schema.Column{ShopsColumns[6]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AvailabilitiesTable,
		AvailabilityDraftsTable,
		EmployeesTable,
		ReminderDeliveriesTable,
		RulesTable,
		SchedulesTable,
		ScheduleAssignmentsTable,
		ScheduleVotesTable,
		ShiftsTable,
		ShopsTable,
	}
)

func init() {
	AvailabilitiesTable.ForeignKeys[0].RefTable = EmployeesTable
	AvailabilitiesTable.ForeignKeys[1].RefTable = ShopsTable
	AvailabilityDraftsTable.ForeignKeys[0].RefTable = EmployeesTable
	AvailabilityDraftsTable.ForeignKeys[1].RefTable = ShopsTable
	EmployeesTable.ForeignKeys[0].RefTable = ShopsTable
	ReminderDeliveriesTable.ForeignKeys[0].RefTable = EmployeesTable
	ReminderDeliveriesTable.ForeignKeys[1].RefTable = ShopsTable
	RulesTable.ForeignKeys[0].RefTable = ShopsTable
	SchedulesTable.ForeignKeys[0].RefTable = ShopsTable
	ScheduleAssignmentsTable.ForeignKeys[0].RefTable = EmployeesTable
	ScheduleAssignmentsTable.ForeignKeys[1].RefTable = SchedulesTable
	ScheduleAssignmentsTable.ForeignKeys[2].RefTable = ShopsTable
	ScheduleAssignmentsTable.ForeignKeys[3].RefTable = ShiftsTable
	ScheduleVotesTable.ForeignKeys[0].RefTable = EmployeesTable
	ScheduleVotesTable.ForeignKeys[1].RefTable = SchedulesTable
	ScheduleVotesTable.ForeignKeys[2].RefTable = ShopsTable
	ShiftsTable.ForeignKeys[0].RefTable = ShopsTable
}
