// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/betallsoph/shiftz/internal/ent/availabilitydraft"
	"github.com/betallsoph/shiftz/internal/ent/employee"
	"github.com/betallsoph/shiftz/internal/ent/schema"
	"github.com/betallsoph/shiftz/internal/ent/shop"
	"github.com/google/uuid"
)

// AvailabilityDraftCreate is the builder for creating a AvailabilityDraft entity.
type AvailabilityDraftCreate struct {
	config
	mutation *AvailabilityDraftMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetShopID sets the "shop_id" field.
func (_c *AvailabilityDraftCreate) SetShopID(v uuid.UUID) *AvailabilityDraftCreate {
	_c.mutation.SetShopID(v)
	return _c
}

// SetEmployeeID sets the "employee_id" field.
func (_c *AvailabilityDraftCreate) SetEmployeeID(v uuid.UUID) *AvailabilityDraftCreate {
	_c.mutation.SetEmployeeID(v)
	return _c
}

// SetTelegramUserID sets the "telegram_user_id" field.
func (_c *AvailabilityDraftCreate) SetTelegramUserID(v int64) *AvailabilityDraftCreate {
	_c.mutation.SetTelegramUserID(v)
	return _c
}

// SetChatID sets the "chat_id" field.
func (_c *AvailabilityDraftCreate) SetChatID(v int64) *AvailabilityDraftCreate {
	_c.mutation.SetChatID(v)
	return _c
}

// SetWeekStart sets the "week_start" field.
func (_c *AvailabilityDraftCreate) SetWeekStart(v time.Time) *AvailabilityDraftCreate {
	_c.mutation.SetWeekStart(v)
	return _c
}

// SetTimezone sets the "timezone" field.
func (_c *AvailabilityDraftCreate) SetTimezone(v string) *AvailabilityDraftCreate {
	_c.mutation.SetTimezone(v)
	return _c
}

// SetSlots sets the "slots" field.
func (_c *AvailabilityDraftCreate) SetSlots(v []schema.AvailabilitySlot) *AvailabilityDraftCreate {
	_c.mutation.SetSlots(v)
	return _c
}

// SetRawMessage sets the "raw_message" field.
func (_c *AvailabilityDraftCreate) SetRawMessage(v string) *AvailabilityDraftCreate {
	_c.mutation.SetRawMessage(v)
	return _c
}

// SetNillableRawMessage sets the "raw_message" field if the given value is not nil.
func (_c *AvailabilityDraftCreate) SetNillableRawMessage(v *string) *AvailabilityDraftCreate {
	if v != nil {
		_c.SetRawMessage(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AvailabilityDraftCreate) SetCreatedAt(v time.Time) *AvailabilityDraftCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AvailabilityDraftCreate) SetNillableCreatedAt(v *time.Time) *AvailabilityDraftCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *AvailabilityDraftCreate) SetExpiresAt(v time.Time) *AvailabilityDraftCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AvailabilityDraftCreate) SetID(v uuid.UUID) *AvailabilityDraftCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AvailabilityDraftCreate) SetNillableID(v *uuid.UUID) *AvailabilityDraftCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetShop sets the "shop" edge to the Shop entity.
func (_c *AvailabilityDraftCreate) SetShop(v *Shop) *AvailabilityDraftCreate {
	return _c.SetShopID(v.ID)
}

// SetEmployee sets the "employee" edge to the Employee entity.
func (_c *AvailabilityDraftCreate) SetEmployee(v *Employee) *AvailabilityDraftCreate {
	return _c.SetEmployeeID(v.ID)
}

// Mutation returns the AvailabilityDraftMutation object of the builder.
func (_c *AvailabilityDraftCreate) Mutation() *AvailabilityDraftMutation {
	return _c.mutation
}

// Save creates the AvailabilityDraft in the database.
func (_c *AvailabilityDraftCreate) Save(ctx context.Context) (*AvailabilityDraft, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AvailabilityDraftCreate) SaveX(ctx context.Context) *AvailabilityDraft {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AvailabilityDraftCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AvailabilityDraftCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AvailabilityDraftCreate) defaults() {
	if _, ok := _c.mutation.RawMessage(); !ok {
		v := availabilitydraft.DefaultRawMessage
		_c.mutation.SetRawMessage(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := availabilitydraft.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := availabilitydraft.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AvailabilityDraftCreate) check() error {
	if _, ok := _c.mutation.ShopID(); !ok {
		return &ValidationError{Name: "shop_id", err: errors.New(`ent: missing required field "AvailabilityDraft.shop_id"`)}
	}
	if _, ok := _c.mutation.EmployeeID(); !ok {
		return &ValidationError{Name: "employee_id", err: errors.New(`ent: missing required field "AvailabilityDraft.employee_id"`)}
	}
	if _, ok := _c.mutation.TelegramUserID(); !ok {
		return &ValidationError{Name: "telegram_user_id", err: errors.New(`ent: missing required field "AvailabilityDraft.telegram_user_id"`)}
	}
	if _, ok := _c.mutation.ChatID(); !ok {
		return &ValidationError{Name: "chat_id", err: errors.New(`ent: missing required field "AvailabilityDraft.chat_id"`)}
	}
	if _, ok := _c.mutation.WeekStart(); !ok {
		return &ValidationError{Name: "week_start", err: errors.New(`ent: missing required field "AvailabilityDraft.week_start"`)}
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		return &ValidationError{Name: "timezone", err: errors.New(`ent: missing required field "AvailabilityDraft.timezone"`)}
	}
	if _, ok := _c.mutation.Slots(); !ok {
		return &ValidationError{Name: "slots", err: errors.New(`ent: missing required field "AvailabilityDraft.slots"`)}
	}
	if _, ok := _c.mutation.RawMessage(); !ok {
		return &ValidationError{Name: "raw_message", err: errors.New(`ent: missing required field "AvailabilityDraft.raw_message"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AvailabilityDraft.created_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "AvailabilityDraft.expires_at"`)}
	}
	if len(_c.mutation.ShopIDs()) == 0 {
		return &ValidationError{Name: "shop", err: errors.New(`ent: missing required edge "AvailabilityDraft.shop"`)}
	}
	if len(_c.mutation.EmployeeIDs()) == 0 {
		return &ValidationError{Name: "employee", err: errors.New(`ent: missing required edge "AvailabilityDraft.employee"`)}
	}
	return nil
}

func (_c *AvailabilityDraftCreate) sqlSave(ctx context.Context) (*AvailabilityDraft, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AvailabilityDraftCreate) createSpec() (*AvailabilityDraft, *sqlgraph.CreateSpec) {
	var (
		_node = &AvailabilityDraft{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(availabilitydraft.Table, sqlgraph.NewFieldSpec(availabilitydraft.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TelegramUserID(); ok {
		_spec.SetField(availabilitydraft.FieldTelegramUserID, field.TypeInt64, value)
		_node.TelegramUserID = value
	}
	if value, ok := _c.mutation.ChatID(); ok {
		_spec.SetField(availabilitydraft.FieldChatID, field.TypeInt64, value)
		_node.ChatID = value
	}
	if value, ok := _c.mutation.WeekStart(); ok {
		_spec.SetField(availabilitydraft.FieldWeekStart, field.TypeTime, value)
		_node.WeekStart = value
	}
	if value, ok := _c.mutation.Timezone(); ok {
		_spec.SetField(availabilitydraft.FieldTimezone, field.TypeString, value)
		_node.Timezone = value
	}
	if value, ok := _c.mutation.Slots(); ok {
		_spec.SetField(availabilitydraft.FieldSlots, field.TypeJSON, value)
		_node.Slots = value
	}
	if value, ok := _c.mutation.RawMessage(); ok {
		_spec.SetField(availabilitydraft.FieldRawMessage, field.TypeString, value)
		_node.RawMessage = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(availabilitydraft.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(availabilitydraft.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if nodes := _c.mutation.ShopIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availabilitydraft.ShopTable,
			Columns: []string{availabilitydraft.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ShopID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availabilitydraft.EmployeeTable,
			Columns: []string{availabilitydraft.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EmployeeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AvailabilityDraft.Create().
//		SetShopID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AvailabilityDraftUpsert) {
//			SetShopID(v+v).
//		}).
//		Exec(ctx)
func (_c *AvailabilityDraftCreate) OnConflict(opts ...sql.ConflictOption) *AvailabilityDraftUpsertOne {
	_c.conflict = opts
	return &AvailabilityDraftUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AvailabilityDraft.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AvailabilityDraftCreate) OnConflictColumns(columns ...string) *AvailabilityDraftUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AvailabilityDraftUpsertOne{
		create: _c,
	}
}

type (
	// AvailabilityDraftUpsertOne is the builder for "upsert"-ing
	//  one AvailabilityDraft node.
	AvailabilityDraftUpsertOne struct {
		create *AvailabilityDraftCreate
	}

	// AvailabilityDraftUpsert is the "OnConflict" setter.
	AvailabilityDraftUpsert struct {
		*sql.UpdateSet
	}
)

// SetShopID sets the "shop_id" field.
func (u *AvailabilityDraftUpsert) SetShopID(v uuid.UUID) *AvailabilityDraftUpsert {
	u.Set(availabilitydraft.FieldShopID, v)
	return u
}

// UpdateShopID sets the "shop_id" field to the value that was provided on create.
func (u *AvailabilityDraftUpsert) UpdateShopID() *AvailabilityDraftUpsert {
	u.SetExcluded(availabilitydraft.FieldShopID)
	return u
}

// SetEmployeeID sets the "employee_id" field.
func (u *AvailabilityDraftUpsert) SetEmployeeID(v uuid.UUID) *AvailabilityDraftUpsert {
	u.Set(availabilitydraft.FieldEmployeeID, v)
	return u
}

// UpdateEmployeeID sets the "employee_id" field to the value that was provided on create.
func (u *AvailabilityDraftUpsert) UpdateEmployeeID() *AvailabilityDraftUpsert {
	u.SetExcluded(availabilitydraft.FieldEmployeeID)
	return u
}

// SetTelegramUserID sets the "telegram_user_id" field.
func (u *AvailabilityDraftUpsert) SetTelegramUserID(v int64) *AvailabilityDraftUpsert {
	u.Set(availabilitydraft.FieldTelegramUserID, v)
	return u
}

// UpdateTelegramUserID sets the "telegram_user_id" field to the value that was provided on create.
func (u *AvailabilityDraftUpsert) UpdateTelegramUserID() *AvailabilityDraftUpsert {
	u.SetExcluded(availabilitydraft.FieldTelegramUserID)
	return u
}

// AddTelegramUserID adds v to the "telegram_user_id" field.
func (u *AvailabilityDraftUpsert) AddTelegramUserID(v int64) *AvailabilityDraftUpsert {
	u.Add(availabilitydraft.FieldTelegramUserID, v)
	return u
}

// SetChatID sets the "chat_id" field.
func (u *AvailabilityDraftUpsert) SetChatID(v int64) *AvailabilityDraftUpsert {
	u.Set(availabilitydraft.FieldChatID, v)
	return u
}

// UpdateChatID sets the "chat_id" field to the value that was provided on create.
func (u *AvailabilityDraftUpsert) UpdateChatID() *AvailabilityDraftUpsert {
	u.SetExcluded(availabilitydraft.FieldChatID)
	return u
}

// AddChatID adds v to the "chat_id" field.
func (u *AvailabilityDraftUpsert) AddChatID(v int64) *AvailabilityDraftUpsert {
	u.Add(availabilitydraft.FieldChatID, v)
	return u
}

// SetWeekStart sets the "week_start" field.
func (u *AvailabilityDraftUpsert) SetWeekStart(v time.Time) *AvailabilityDraftUpsert {
	u.Set(availabilitydraft.FieldWeekStart, v)
	return u
}

// UpdateWeekStart sets the "week_start" field to the value that was provided on create.
func (u *AvailabilityDraftUpsert) UpdateWeekStart() *AvailabilityDraftUpsert {
	u.SetExcluded(availabilitydraft.FieldWeekStart)
	return u
}

// SetTimezone sets the "timezone" field.
func (u *AvailabilityDraftUpsert) SetTimezone(v string) *AvailabilityDraftUpsert {
	u.Set(availabilitydraft.FieldTimezone, v)
	return u
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *AvailabilityDraftUpsert) UpdateTimezone() *AvailabilityDraftUpsert {
	u.SetExcluded(availabilitydraft.FieldTimezone)
	return u
}

// SetSlots sets the "slots" field.
func (u *AvailabilityDraftUpsert) SetSlots(v []schema.AvailabilitySlot) *AvailabilityDraftUpsert {
	u.Set(availabilitydraft.FieldSlots, v)
	return u
}

// UpdateSlots sets the "slots" field to the value that was provided on create.
func (u *AvailabilityDraftUpsert) UpdateSlots() *AvailabilityDraftUpsert {
	u.SetExcluded(availabilitydraft.FieldSlots)
	return u
}

// SetRawMessage sets the "raw_message" field.
func (u *AvailabilityDraftUpsert) SetRawMessage(v string) *AvailabilityDraftUpsert {
	u.Set(availabilitydraft.FieldRawMessage, v)
	return u
}

// UpdateRawMessage sets the "raw_message" field to the value that was provided on create.
func (u *AvailabilityDraftUpsert) UpdateRawMessage() *AvailabilityDraftUpsert {
	u.SetExcluded(availabilitydraft.FieldRawMessage)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *AvailabilityDraftUpsert) SetExpiresAt(v time.Time) *AvailabilityDraftUpsert {
	u.Set(availabilitydraft.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AvailabilityDraftUpsert) UpdateExpiresAt() *AvailabilityDraftUpsert {
	u.SetExcluded(availabilitydraft.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.AvailabilityDraft.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(availabilitydraft.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AvailabilityDraftUpsertOne) UpdateNewValues() *AvailabilityDraftUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(availabilitydraft.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(availabilitydraft.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AvailabilityDraft.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AvailabilityDraftUpsertOne) Ignore() *AvailabilityDraftUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AvailabilityDraftUpsertOne) DoNothing() *AvailabilityDraftUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AvailabilityDraftCreate.OnConflict
// documentation for more info.
func (u *AvailabilityDraftUpsertOne) Update(set func(*AvailabilityDraftUpsert)) *AvailabilityDraftUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AvailabilityDraftUpsert{UpdateSet: update})
	}))
	return u
}

// SetShopID sets the "shop_id" field.
func (u *AvailabilityDraftUpsertOne) SetShopID(v uuid.UUID) *AvailabilityDraftUpsertOne {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.SetShopID(v)
	})
}

// UpdateShopID sets the "shop_id" field to the value that was provided on create.
func (u *AvailabilityDraftUpsertOne) UpdateShopID() *AvailabilityDraftUpsertOne {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.UpdateShopID()
	})
}

// SetEmployeeID sets the "employee_id" field.
func (u *AvailabilityDraftUpsertOne) SetEmployeeID(v uuid.UUID) *AvailabilityDraftUpsertOne {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.SetEmployeeID(v)
	})
}

// UpdateEmployeeID sets the "employee_id" field to the value that was provided on create.
func (u *AvailabilityDraftUpsertOne) UpdateEmployeeID() *AvailabilityDraftUpsertOne {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.UpdateEmployeeID()
	})
}

// SetTelegramUserID sets the "telegram_user_id" field.
func (u *AvailabilityDraftUpsertOne) SetTelegramUserID(v int64) *AvailabilityDraftUpsertOne {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.SetTelegramUserID(v)
	})
}

// AddTelegramUserID adds v to the "telegram_user_id" field.
func (u *AvailabilityDraftUpsertOne) AddTelegramUserID(v int64) *AvailabilityDraftUpsertOne {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.AddTelegramUserID(v)
	})
}

// UpdateTelegramUserID sets the "telegram_user_id" field to the value that was provided on create.
func (u *AvailabilityDraftUpsertOne) UpdateTelegramUserID() *AvailabilityDraftUpsertOne {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.UpdateTelegramUserID()
	})
}

// SetChatID sets the "chat_id" field.
func (u *AvailabilityDraftUpsertOne) SetChatID(v int64) *AvailabilityDraftUpsertOne {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.SetChatID(v)
	})
}

// AddChatID adds v to the "chat_id" field.
func (u *AvailabilityDraftUpsertOne) AddChatID(v int64) *AvailabilityDraftUpsertOne {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.AddChatID(v)
	})
}

// UpdateChatID sets the "chat_id" field to the value that was provided on create.
func (u *AvailabilityDraftUpsertOne) UpdateChatID() *AvailabilityDraftUpsertOne {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.UpdateChatID()
	})
}

// SetWeekStart sets the "week_start" field.
func (u *AvailabilityDraftUpsertOne) SetWeekStart(v time.Time) *AvailabilityDraftUpsertOne {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.SetWeekStart(v)
	})
}

// UpdateWeekStart sets the "week_start" field to the value that was provided on create.
func (u *AvailabilityDraftUpsertOne) UpdateWeekStart() *AvailabilityDraftUpsertOne {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.UpdateWeekStart()
	})
}

// SetTimezone sets the "timezone" field.
func (u *AvailabilityDraftUpsertOne) SetTimezone(v string) *AvailabilityDraftUpsertOne {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.SetTimezone(v)
	})
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *AvailabilityDraftUpsertOne) UpdateTimezone() *AvailabilityDraftUpsertOne {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.UpdateTimezone()
	})
}

// SetSlots sets the "slots" field.
func (u *AvailabilityDraftUpsertOne) SetSlots(v []schema.AvailabilitySlot) *AvailabilityDraftUpsertOne {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.SetSlots(v)
	})
}

// UpdateSlots sets the "slots" field to the value that was provided on create.
func (u *AvailabilityDraftUpsertOne) UpdateSlots() *AvailabilityDraftUpsertOne {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.UpdateSlots()
	})
}

// SetRawMessage sets the "raw_message" field.
func (u *AvailabilityDraftUpsertOne) SetRawMessage(v string) *AvailabilityDraftUpsertOne {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.SetRawMessage(v)
	})
}

// UpdateRawMessage sets the "raw_message" field to the value that was provided on create.
func (u *AvailabilityDraftUpsertOne) UpdateRawMessage() *AvailabilityDraftUpsertOne {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.UpdateRawMessage()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *AvailabilityDraftUpsertOne) SetExpiresAt(v time.Time) *AvailabilityDraftUpsertOne {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AvailabilityDraftUpsertOne) UpdateExpiresAt() *AvailabilityDraftUpsertOne {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *AvailabilityDraftUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AvailabilityDraftCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AvailabilityDraftUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AvailabilityDraftUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: AvailabilityDraftUpsertOne.ID is not supported by MySQL driver. Use AvailabilityDraftUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AvailabilityDraftUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AvailabilityDraftCreateBulk is the builder for creating many AvailabilityDraft entities in bulk.
type AvailabilityDraftCreateBulk struct {
	config
	err      error
	builders []*AvailabilityDraftCreate
	conflict []sql.ConflictOption
}

// Save creates the AvailabilityDraft entities in the database.
func (_c *AvailabilityDraftCreateBulk) Save(ctx context.Context) ([]*AvailabilityDraft, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AvailabilityDraft, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AvailabilityDraftMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AvailabilityDraftCreateBulk) SaveX(ctx context.Context) []*AvailabilityDraft {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AvailabilityDraftCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AvailabilityDraftCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AvailabilityDraft.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AvailabilityDraftUpsert) {
//			SetShopID(v+v).
//		}).
//		Exec(ctx)
func (_c *AvailabilityDraftCreateBulk) OnConflict(opts ...sql.ConflictOption) *AvailabilityDraftUpsertBulk {
	_c.conflict = opts
	return &AvailabilityDraftUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AvailabilityDraft.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AvailabilityDraftCreateBulk) OnConflictColumns(columns ...string) *AvailabilityDraftUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AvailabilityDraftUpsertBulk{
		create: _c,
	}
}

// AvailabilityDraftUpsertBulk is the builder for "upsert"-ing
// a bulk of AvailabilityDraft nodes.
type AvailabilityDraftUpsertBulk struct {
	create *AvailabilityDraftCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AvailabilityDraft.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(availabilitydraft.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *AvailabilityDraftUpsertBulk) UpdateNewValues() *AvailabilityDraftUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(availabilitydraft.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(availabilitydraft.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AvailabilityDraft.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AvailabilityDraftUpsertBulk) Ignore() *AvailabilityDraftUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AvailabilityDraftUpsertBulk) DoNothing() *AvailabilityDraftUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AvailabilityDraftCreateBulk.OnConflict
// documentation for more info.
func (u *AvailabilityDraftUpsertBulk) Update(set func(*AvailabilityDraftUpsert)) *AvailabilityDraftUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AvailabilityDraftUpsert{UpdateSet: update})
	}))
	return u
}

// SetShopID sets the "shop_id" field.
func (u *AvailabilityDraftUpsertBulk) SetShopID(v uuid.UUID) *AvailabilityDraftUpsertBulk {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.SetShopID(v)
	})
}

// UpdateShopID sets the "shop_id" field to the value that was provided on create.
func (u *AvailabilityDraftUpsertBulk) UpdateShopID() *AvailabilityDraftUpsertBulk {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.UpdateShopID()
	})
}

// SetEmployeeID sets the "employee_id" field.
func (u *AvailabilityDraftUpsertBulk) SetEmployeeID(v uuid.UUID) *AvailabilityDraftUpsertBulk {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.SetEmployeeID(v)
	})
}

// UpdateEmployeeID sets the "employee_id" field to the value that was provided on create.
func (u *AvailabilityDraftUpsertBulk) UpdateEmployeeID() *AvailabilityDraftUpsertBulk {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.UpdateEmployeeID()
	})
}

// SetTelegramUserID sets the "telegram_user_id" field.
func (u *AvailabilityDraftUpsertBulk) SetTelegramUserID(v int64) *AvailabilityDraftUpsertBulk {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.SetTelegramUserID(v)
	})
}

// AddTelegramUserID adds v to the "telegram_user_id" field.
func (u *AvailabilityDraftUpsertBulk) AddTelegramUserID(v int64) *AvailabilityDraftUpsertBulk {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.AddTelegramUserID(v)
	})
}

// UpdateTelegramUserID sets the "telegram_user_id" field to the value that was provided on create.
func (u *AvailabilityDraftUpsertBulk) UpdateTelegramUserID() *AvailabilityDraftUpsertBulk {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.UpdateTelegramUserID()
	})
}

// SetChatID sets the "chat_id" field.
func (u *AvailabilityDraftUpsertBulk) SetChatID(v int64) *AvailabilityDraftUpsertBulk {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.SetChatID(v)
	})
}

// AddChatID adds v to the "chat_id" field.
func (u *AvailabilityDraftUpsertBulk) AddChatID(v int64) *AvailabilityDraftUpsertBulk {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.AddChatID(v)
	})
}

// UpdateChatID sets the "chat_id" field to the value that was provided on create.
func (u *AvailabilityDraftUpsertBulk) UpdateChatID() *AvailabilityDraftUpsertBulk {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.UpdateChatID()
	})
}

// SetWeekStart sets the "week_start" field.
func (u *AvailabilityDraftUpsertBulk) SetWeekStart(v time.Time) *AvailabilityDraftUpsertBulk {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.SetWeekStart(v)
	})
}

// UpdateWeekStart sets the "week_start" field to the value that was provided on create.
func (u *AvailabilityDraftUpsertBulk) UpdateWeekStart() *AvailabilityDraftUpsertBulk {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.UpdateWeekStart()
	})
}

// SetTimezone sets the "timezone" field.
func (u *AvailabilityDraftUpsertBulk) SetTimezone(v string) *AvailabilityDraftUpsertBulk {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.SetTimezone(v)
	})
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *AvailabilityDraftUpsertBulk) UpdateTimezone() *AvailabilityDraftUpsertBulk {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.UpdateTimezone()
	})
}

// SetSlots sets the "slots" field.
func (u *AvailabilityDraftUpsertBulk) SetSlots(v []schema.AvailabilitySlot) *AvailabilityDraftUpsertBulk {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.SetSlots(v)
	})
}

// UpdateSlots sets the "slots" field to the value that was provided on create.
func (u *AvailabilityDraftUpsertBulk) UpdateSlots() *AvailabilityDraftUpsertBulk {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.UpdateSlots()
	})
}

// SetRawMessage sets the "raw_message" field.
func (u *AvailabilityDraftUpsertBulk) SetRawMessage(v string) *AvailabilityDraftUpsertBulk {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.SetRawMessage(v)
	})
}

// UpdateRawMessage sets the "raw_message" field to the value that was provided on create.
func (u *AvailabilityDraftUpsertBulk) UpdateRawMessage() *AvailabilityDraftUpsertBulk {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.UpdateRawMessage()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *AvailabilityDraftUpsertBulk) SetExpiresAt(v time.Time) *AvailabilityDraftUpsertBulk {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *AvailabilityDraftUpsertBulk) UpdateExpiresAt() *AvailabilityDraftUpsertBulk {
	return u.Update(func(s *AvailabilityDraftUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *AvailabilityDraftUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AvailabilityDraftCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AvailabilityDraftCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AvailabilityDraftUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
