// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/betallsoph/shiftz/internal/ent/availability"
	"github.com/betallsoph/shiftz/internal/ent/employee"
	"github.com/betallsoph/shiftz/internal/ent/predicate"
	"github.com/betallsoph/shiftz/internal/ent/schema"
	"github.com/betallsoph/shiftz/internal/ent/shop"
	"github.com/google/uuid"
)

// AvailabilityUpdate is the builder for updating Availability entities.
type AvailabilityUpdate struct {
	config
	hooks    []Hook
	mutation *AvailabilityMutation
}

// Where appends a list predicates to the AvailabilityUpdate builder.
func (_u *AvailabilityUpdate) Where(ps ...predicate.Availability) *AvailabilityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetShopID sets the "shop_id" field.
func (_u *AvailabilityUpdate) SetShopID(v uuid.UUID) *AvailabilityUpdate {
	_u.mutation.SetShopID(v)
	return _u
}

// SetNillableShopID sets the "shop_id" field if the given value is not nil.
func (_u *AvailabilityUpdate) SetNillableShopID(v *uuid.UUID) *AvailabilityUpdate {
	if v != nil {
		_u.SetShopID(*v)
	}
	return _u
}

// SetEmployeeID sets the "employee_id" field.
func (_u *AvailabilityUpdate) SetEmployeeID(v uuid.UUID) *AvailabilityUpdate {
	_u.mutation.SetEmployeeID(v)
	return _u
}

// SetNillableEmployeeID sets the "employee_id" field if the given value is not nil.
func (_u *AvailabilityUpdate) SetNillableEmployeeID(v *uuid.UUID) *AvailabilityUpdate {
	if v != nil {
		_u.SetEmployeeID(*v)
	}
	return _u
}

// SetWeekStart sets the "week_start" field.
func (_u *AvailabilityUpdate) SetWeekStart(v time.Time) *AvailabilityUpdate {
	_u.mutation.SetWeekStart(v)
	return _u
}

// SetNillableWeekStart sets the "week_start" field if the given value is not nil.
func (_u *AvailabilityUpdate) SetNillableWeekStart(v *time.Time) *AvailabilityUpdate {
	if v != nil {
		_u.SetWeekStart(*v)
	}
	return _u
}

// SetSlots sets the "slots" field.
func (_u *AvailabilityUpdate) SetSlots(v []schema.AvailabilitySlot) *AvailabilityUpdate {
	_u.mutation.SetSlots(v)
	return _u
}

// AppendSlots appends value to the "slots" field.
func (_u *AvailabilityUpdate) AppendSlots(v []schema.AvailabilitySlot) *AvailabilityUpdate {
	_u.mutation.AppendSlots(v)
	return _u
}

// SetRawMessage sets the "raw_message" field.
func (_u *AvailabilityUpdate) SetRawMessage(v string) *AvailabilityUpdate {
	_u.mutation.SetRawMessage(v)
	return _u
}

// SetNillableRawMessage sets the "raw_message" field if the given value is not nil.
func (_u *AvailabilityUpdate) SetNillableRawMessage(v *string) *AvailabilityUpdate {
	if v != nil {
		_u.SetRawMessage(*v)
	}
	return _u
}

// SetShop sets the "shop" edge to the Shop entity.
func (_u *AvailabilityUpdate) SetShop(v *Shop) *AvailabilityUpdate {
	return _u.SetShopID(v.ID)
}

// SetEmployee sets the "employee" edge to the Employee entity.
func (_u *AvailabilityUpdate) SetEmployee(v *Employee) *AvailabilityUpdate {
	return _u.SetEmployeeID(v.ID)
}

// Mutation returns the AvailabilityMutation object of the builder.
func (_u *AvailabilityUpdate) Mutation() *AvailabilityMutation {
	return _u.mutation
}

// ClearShop clears the "shop" edge to the Shop entity.
func (_u *AvailabilityUpdate) ClearShop() *AvailabilityUpdate {
	_u.mutation.ClearShop()
	return _u
}

// ClearEmployee clears the "employee" edge to the Employee entity.
func (_u *AvailabilityUpdate) ClearEmployee() *AvailabilityUpdate {
	_u.mutation.ClearEmployee()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AvailabilityUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AvailabilityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AvailabilityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AvailabilityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AvailabilityUpdate) check() error {
	if _u.mutation.ShopCleared() && len(_u.mutation.ShopIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Availability.shop"`)
	}
	if _u.mutation.EmployeeCleared() && len(_u.mutation.EmployeeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Availability.employee"`)
	}
	return nil
}

func (_u *AvailabilityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(availability.Table, availability.Columns, sqlgraph.NewFieldSpec(availability.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.WeekStart(); ok {
		_spec.SetField(availability.FieldWeekStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Slots(); ok {
		_spec.SetField(availability.FieldSlots, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSlots(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, availability.FieldSlots, value)
		})
	}
	if value, ok := _u.mutation.RawMessage(); ok {
		_spec.SetField(availability.FieldRawMessage, field.TypeString, value)
	}
	if _u.mutation.ShopCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availability.ShopTable,
			Columns: []string{availability.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShopIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availability.ShopTable,
			Columns: []string{availability.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EmployeeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availability.EmployeeTable,
			Columns: []string{availability.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availability.EmployeeTable,
			Columns: []string{availability.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{availability.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AvailabilityUpdateOne is the builder for updating a single Availability entity.
type AvailabilityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AvailabilityMutation
}

// SetShopID sets the "shop_id" field.
func (_u *AvailabilityUpdateOne) SetShopID(v uuid.UUID) *AvailabilityUpdateOne {
	_u.mutation.SetShopID(v)
	return _u
}

// SetNillableShopID sets the "shop_id" field if the given value is not nil.
func (_u *AvailabilityUpdateOne) SetNillableShopID(v *uuid.UUID) *AvailabilityUpdateOne {
	if v != nil {
		_u.SetShopID(*v)
	}
	return _u
}

// SetEmployeeID sets the "employee_id" field.
func (_u *AvailabilityUpdateOne) SetEmployeeID(v uuid.UUID) *AvailabilityUpdateOne {
	_u.mutation.SetEmployeeID(v)
	return _u
}

// SetNillableEmployeeID sets the "employee_id" field if the given value is not nil.
func (_u *AvailabilityUpdateOne) SetNillableEmployeeID(v *uuid.UUID) *AvailabilityUpdateOne {
	if v != nil {
		_u.SetEmployeeID(*v)
	}
	return _u
}

// SetWeekStart sets the "week_start" field.
func (_u *AvailabilityUpdateOne) SetWeekStart(v time.Time) *AvailabilityUpdateOne {
	_u.mutation.SetWeekStart(v)
	return _u
}

// SetNillableWeekStart sets the "week_start" field if the given value is not nil.
func (_u *AvailabilityUpdateOne) SetNillableWeekStart(v *time.Time) *AvailabilityUpdateOne {
	if v != nil {
		_u.SetWeekStart(*v)
	}
	return _u
}

// SetSlots sets the "slots" field.
func (_u *AvailabilityUpdateOne) SetSlots(v []schema.AvailabilitySlot) *AvailabilityUpdateOne {
	_u.mutation.SetSlots(v)
	return _u
}

// AppendSlots appends value to the "slots" field.
func (_u *AvailabilityUpdateOne) AppendSlots(v []schema.AvailabilitySlot) *AvailabilityUpdateOne {
	_u.mutation.AppendSlots(v)
	return _u
}

// SetRawMessage sets the "raw_message" field.
func (_u *AvailabilityUpdateOne) SetRawMessage(v string) *AvailabilityUpdateOne {
	_u.mutation.SetRawMessage(v)
	return _u
}

// SetNillableRawMessage sets the "raw_message" field if the given value is not nil.
func (_u *AvailabilityUpdateOne) SetNillableRawMessage(v *string) *AvailabilityUpdateOne {
	if v != nil {
		_u.SetRawMessage(*v)
	}
	return _u
}

// SetShop sets the "shop" edge to the Shop entity.
func (_u *AvailabilityUpdateOne) SetShop(v *Shop) *AvailabilityUpdateOne {
	return _u.SetShopID(v.ID)
}

// SetEmployee sets the "employee" edge to the Employee entity.
func (_u *AvailabilityUpdateOne) SetEmployee(v *Employee) *AvailabilityUpdateOne {
	return _u.SetEmployeeID(v.ID)
}

// Mutation returns the AvailabilityMutation object of the builder.
func (_u *AvailabilityUpdateOne) Mutation() *AvailabilityMutation {
	return _u.mutation
}

// ClearShop clears the "shop" edge to the Shop entity.
func (_u *AvailabilityUpdateOne) ClearShop() *AvailabilityUpdateOne {
	_u.mutation.ClearShop()
	return _u
}

// ClearEmployee clears the "employee" edge to the Employee entity.
func (_u *AvailabilityUpdateOne) ClearEmployee() *AvailabilityUpdateOne {
	_u.mutation.ClearEmployee()
	return _u
}

// Where appends a list predicates to the AvailabilityUpdate builder.
func (_u *AvailabilityUpdateOne) Where(ps ...predicate.Availability) *AvailabilityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AvailabilityUpdateOne) Select(field string, fields ...string) *AvailabilityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Availability entity.
func (_u *AvailabilityUpdateOne) Save(ctx context.Context) (*Availability, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AvailabilityUpdateOne) SaveX(ctx context.Context) *Availability {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AvailabilityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AvailabilityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AvailabilityUpdateOne) check() error {
	if _u.mutation.ShopCleared() && len(_u.mutation.ShopIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Availability.shop"`)
	}
	if _u.mutation.EmployeeCleared() && len(_u.mutation.EmployeeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Availability.employee"`)
	}
	return nil
}

func (_u *AvailabilityUpdateOne) sqlSave(ctx context.Context) (_node *Availability, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(availability.Table, availability.Columns, sqlgraph.NewFieldSpec(availability.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Availability.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, availability.FieldID)
		for _, f := range fields {
			if !availability.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != availability.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.WeekStart(); ok {
		_spec.SetField(availability.FieldWeekStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Slots(); ok {
		_spec.SetField(availability.FieldSlots, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSlots(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, availability.FieldSlots, value)
		})
	}
	if value, ok := _u.mutation.RawMessage(); ok {
		_spec.SetField(availability.FieldRawMessage, field.TypeString, value)
	}
	if _u.mutation.ShopCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availability.ShopTable,
			Columns: []string{availability.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShopIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availability.ShopTable,
			Columns: []string{availability.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EmployeeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availability.EmployeeTable,
			Columns: []string{availability.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availability.EmployeeTable,
			Columns: []string{availability.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Availability{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{availability.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
