// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/betallsoph/shiftz/internal/ent/availability"
	"github.com/betallsoph/shiftz/internal/ent/employee"
	"github.com/betallsoph/shiftz/internal/ent/schema"
	"github.com/betallsoph/shiftz/internal/ent/shop"
	"github.com/google/uuid"
)

// Availability is the model entity for the Availability schema.
type Availability struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ShopID holds the value of the "shop_id" field.
	ShopID uuid.UUID `json:"shop_id,omitempty"`
	// EmployeeID holds the value of the "employee_id" field.
	EmployeeID uuid.UUID `json:"employee_id,omitempty"`
	// WeekStart holds the value of the "week_start" field.
	WeekStart time.Time `json:"week_start,omitempty"`
	// Slots holds the value of the "slots" field.
	Slots []schema.AvailabilitySlot `json:"slots,omitempty"`
	// RawMessage holds the value of the "raw_message" field.
	RawMessage string `json:"raw_message,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AvailabilityQuery when eager-loading is set.
	Edges        AvailabilityEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AvailabilityEdges holds the relations/edges for other nodes in the graph.
type AvailabilityEdges struct {
	// Shop holds the value of the shop edge.
	Shop *Shop `json:"shop,omitempty"`
	// Employee holds the value of the employee edge.
	Employee *Employee `json:"employee,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ShopOrErr returns the Shop value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AvailabilityEdges) ShopOrErr() (*Shop, error) {
	if e.Shop != nil {
		return e.Shop, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: shop.Label}
	}
	return nil, &NotLoadedError{edge: "shop"}
}

// EmployeeOrErr returns the Employee value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AvailabilityEdges) EmployeeOrErr() (*Employee, error) {
	if e.Employee != nil {
		return e.Employee, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: employee.Label}
	}
	return nil, &NotLoadedError{edge: "employee"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Availability) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case availability.FieldSlots:
			values[i] = new([]byte)
		case availability.FieldRawMessage:
			values[i] = new(sql.NullString)
		case availability.FieldWeekStart, availability.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case availability.FieldID, availability.FieldShopID, availability.FieldEmployeeID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Availability fields.
func (_m *Availability) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case availability.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case availability.FieldShopID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field shop_id", values[i])
			} else if value != nil {
				_m.ShopID = *value
			}
		case availability.FieldEmployeeID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field employee_id", values[i])
			} else if value != nil {
				_m.EmployeeID = *value
			}
		case availability.FieldWeekStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field week_start", values[i])
			} else if value.Valid {
				_m.WeekStart = value.Time
			}
		case availability.FieldSlots:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field slots", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Slots); err != nil {
					return fmt.Errorf("unmarshal field slots: %w", err)
				}
			}
		case availability.FieldRawMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field raw_message", values[i])
			} else if value.Valid {
				_m.RawMessage = value.String
			}
		case availability.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Availability.
// This includes values selected through modifiers, order, etc.
func (_m *Availability) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryShop queries the "shop" edge of the Availability entity.
func (_m *Availability) QueryShop() *ShopQuery {
	return NewAvailabilityClient(_m.config).QueryShop(_m)
}

// QueryEmployee queries the "employee" edge of the Availability entity.
func (_m *Availability) QueryEmployee() *EmployeeQuery {
	return NewAvailabilityClient(_m.config).QueryEmployee(_m)
}

// Update returns a builder for updating this Availability.
// Note that you need to call Availability.Unwrap() before calling this method if this Availability
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Availability) Update() *AvailabilityUpdateOne {
	return NewAvailabilityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Availability entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Availability) Unwrap() *Availability {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Availability is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Availability) String() string {
	var builder strings.Builder
	builder.WriteString("Availability(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("shop_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ShopID))
	builder.WriteString(", ")
	builder.WriteString("employee_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EmployeeID))
	builder.WriteString(", ")
	builder.WriteString("week_start=")
	builder.WriteString(_m.WeekStart.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("slots=")
	builder.WriteString(fmt.Sprintf("%v", _m.Slots))
	builder.WriteString(", ")
	builder.WriteString("raw_message=")
	builder.WriteString(_m.RawMessage)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Availabilities is a parsable slice of Availability.
type Availabilities []*Availability
