// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/betallsoph/shiftz/internal/ent/availabilitydraft"
	"github.com/betallsoph/shiftz/internal/ent/employee"
	"github.com/betallsoph/shiftz/internal/ent/schema"
	"github.com/betallsoph/shiftz/internal/ent/shop"
	"github.com/google/uuid"
)

// AvailabilityDraft is the model entity for the AvailabilityDraft schema.
type AvailabilityDraft struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ShopID holds the value of the "shop_id" field.
	ShopID uuid.UUID `json:"shop_id,omitempty"`
	// EmployeeID holds the value of the "employee_id" field.
	EmployeeID uuid.UUID `json:"employee_id,omitempty"`
	// TelegramUserID holds the value of the "telegram_user_id" field.
	TelegramUserID int64 `json:"telegram_user_id,omitempty"`
	// ChatID holds the value of the "chat_id" field.
	ChatID int64 `json:"chat_id,omitempty"`
	// WeekStart holds the value of the "week_start" field.
	WeekStart time.Time `json:"week_start,omitempty"`
	// Timezone holds the value of the "timezone" field.
	Timezone string `json:"timezone,omitempty"`
	// Slots holds the value of the "slots" field.
	Slots []schema.AvailabilitySlot `json:"slots,omitempty"`
	// RawMessage holds the value of the "raw_message" field.
	RawMessage string `json:"raw_message,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AvailabilityDraftQuery when eager-loading is set.
	Edges        AvailabilityDraftEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AvailabilityDraftEdges holds the relations/edges for other nodes in the graph.
type AvailabilityDraftEdges struct {
	// Shop holds the value of the shop edge.
	Shop *Shop `json:"shop,omitempty"`
	// Employee holds the value of the employee edge.
	Employee *Employee `json:"employee,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ShopOrErr returns the Shop value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AvailabilityDraftEdges) ShopOrErr() (*Shop, error) {
	if e.Shop != nil {
		return e.Shop, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: shop.Label}
	}
	return nil, &NotLoadedError{edge: "shop"}
}

// EmployeeOrErr returns the Employee value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AvailabilityDraftEdges) EmployeeOrErr() (*Employee, error) {
	if e.Employee != nil {
		return e.Employee, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: employee.Label}
	}
	return nil, &NotLoadedError{edge: "employee"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AvailabilityDraft) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case availabilitydraft.FieldSlots:
			values[i] = new([]byte)
		case availabilitydraft.FieldTelegramUserID, availabilitydraft.FieldChatID:
			values[i] = new(sql.NullInt64)
		case availabilitydraft.FieldTimezone, availabilitydraft.FieldRawMessage:
			values[i] = new(sql.NullString)
		case availabilitydraft.FieldWeekStart, availabilitydraft.FieldCreatedAt, availabilitydraft.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		case availabilitydraft.FieldID, availabilitydraft.FieldShopID, availabilitydraft.FieldEmployeeID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AvailabilityDraft fields.
func (_m *AvailabilityDraft) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case availabilitydraft.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case availabilitydraft.FieldShopID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field shop_id", values[i])
			} else if value != nil {
				_m.ShopID = *value
			}
		case availabilitydraft.FieldEmployeeID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field employee_id", values[i])
			} else if value != nil {
				_m.EmployeeID = *value
			}
		case availabilitydraft.FieldTelegramUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field telegram_user_id", values[i])
			} else if value.Valid {
				_m.TelegramUserID = value.Int64
			}
		case availabilitydraft.FieldChatID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chat_id", values[i])
			} else if value.Valid {
				_m.ChatID = value.Int64
			}
		case availabilitydraft.FieldWeekStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field week_start", values[i])
			} else if value.Valid {
				_m.WeekStart = value.Time
			}
		case availabilitydraft.FieldTimezone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field timezone", values[i])
			} else if value.Valid {
				_m.Timezone = value.String
			}
		case availabilitydraft.FieldSlots:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field slots", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Slots); err != nil {
					return fmt.Errorf("unmarshal field slots: %w", err)
				}
			}
		case availabilitydraft.FieldRawMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field raw_message", values[i])
			} else if value.Valid {
				_m.RawMessage = value.String
			}
		case availabilitydraft.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case availabilitydraft.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AvailabilityDraft.
// This includes values selected through modifiers, order, etc.
func (_m *AvailabilityDraft) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryShop queries the "shop" edge of the AvailabilityDraft entity.
func (_m *AvailabilityDraft) QueryShop() *ShopQuery {
	return NewAvailabilityDraftClient(_m.config).QueryShop(_m)
}

// QueryEmployee queries the "employee" edge of the AvailabilityDraft entity.
func (_m *AvailabilityDraft) QueryEmployee() *EmployeeQuery {
	return NewAvailabilityDraftClient(_m.config).QueryEmployee(_m)
}

// Update returns a builder for updating this AvailabilityDraft.
// Note that you need to call AvailabilityDraft.Unwrap() before calling this method if this AvailabilityDraft
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AvailabilityDraft) Update() *AvailabilityDraftUpdateOne {
	return NewAvailabilityDraftClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AvailabilityDraft entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AvailabilityDraft) Unwrap() *AvailabilityDraft {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AvailabilityDraft is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AvailabilityDraft) String() string {
	var builder strings.Builder
	builder.WriteString("AvailabilityDraft(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("shop_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ShopID))
	builder.WriteString(", ")
	builder.WriteString("employee_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EmployeeID))
	builder.WriteString(", ")
	builder.WriteString("telegram_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TelegramUserID))
	builder.WriteString(", ")
	builder.WriteString("chat_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChatID))
	builder.WriteString(", ")
	builder.WriteString("week_start=")
	builder.WriteString(_m.WeekStart.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("timezone=")
	builder.WriteString(_m.Timezone)
	builder.WriteString(", ")
	builder.WriteString("slots=")
	builder.WriteString(fmt.Sprintf("%v", _m.Slots))
	builder.WriteString(", ")
	builder.WriteString("raw_message=")
	builder.WriteString(_m.RawMessage)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AvailabilityDrafts is a parsable slice of AvailabilityDraft.
type AvailabilityDrafts []*AvailabilityDraft
