// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/betallsoph/shiftz/internal/ent/availabilitydraft"
	"github.com/betallsoph/shiftz/internal/ent/employee"
	"github.com/betallsoph/shiftz/internal/ent/predicate"
	"github.com/betallsoph/shiftz/internal/ent/schema"
	"github.com/betallsoph/shiftz/internal/ent/shop"
	"github.com/google/uuid"
)

// AvailabilityDraftUpdate is the builder for updating AvailabilityDraft entities.
type AvailabilityDraftUpdate struct {
	config
	hooks    []Hook
	mutation *AvailabilityDraftMutation
}

// Where appends a list predicates to the AvailabilityDraftUpdate builder.
func (_u *AvailabilityDraftUpdate) Where(ps ...predicate.AvailabilityDraft) *AvailabilityDraftUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetShopID sets the "shop_id" field.
func (_u *AvailabilityDraftUpdate) SetShopID(v uuid.UUID) *AvailabilityDraftUpdate {
	_u.mutation.SetShopID(v)
	return _u
}

// SetNillableShopID sets the "shop_id" field if the given value is not nil.
func (_u *AvailabilityDraftUpdate) SetNillableShopID(v *uuid.UUID) *AvailabilityDraftUpdate {
	if v != nil {
		_u.SetShopID(*v)
	}
	return _u
}

// SetEmployeeID sets the "employee_id" field.
func (_u *AvailabilityDraftUpdate) SetEmployeeID(v uuid.UUID) *AvailabilityDraftUpdate {
	_u.mutation.SetEmployeeID(v)
	return _u
}

// SetNillableEmployeeID sets the "employee_id" field if the given value is not nil.
func (_u *AvailabilityDraftUpdate) SetNillableEmployeeID(v *uuid.UUID) *AvailabilityDraftUpdate {
	if v != nil {
		_u.SetEmployeeID(*v)
	}
	return _u
}

// SetTelegramUserID sets the "telegram_user_id" field.
func (_u *AvailabilityDraftUpdate) SetTelegramUserID(v int64) *AvailabilityDraftUpdate {
	_u.mutation.ResetTelegramUserID()
	_u.mutation.SetTelegramUserID(v)
	return _u
}

// SetNillableTelegramUserID sets the "telegram_user_id" field if the given value is not nil.
func (_u *AvailabilityDraftUpdate) SetNillableTelegramUserID(v *int64) *AvailabilityDraftUpdate {
	if v != nil {
		_u.SetTelegramUserID(*v)
	}
	return _u
}

// AddTelegramUserID adds value to the "telegram_user_id" field.
func (_u *AvailabilityDraftUpdate) AddTelegramUserID(v int64) *AvailabilityDraftUpdate {
	_u.mutation.AddTelegramUserID(v)
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *AvailabilityDraftUpdate) SetChatID(v int64) *AvailabilityDraftUpdate {
	_u.mutation.ResetChatID()
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *AvailabilityDraftUpdate) SetNillableChatID(v *int64) *AvailabilityDraftUpdate {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// AddChatID adds value to the "chat_id" field.
func (_u *AvailabilityDraftUpdate) AddChatID(v int64) *AvailabilityDraftUpdate {
	_u.mutation.AddChatID(v)
	return _u
}

// SetWeekStart sets the "week_start" field.
func (_u *AvailabilityDraftUpdate) SetWeekStart(v time.Time) *AvailabilityDraftUpdate {
	_u.mutation.SetWeekStart(v)
	return _u
}

// SetNillableWeekStart sets the "week_start" field if the given value is not nil.
func (_u *AvailabilityDraftUpdate) SetNillableWeekStart(v *time.Time) *AvailabilityDraftUpdate {
	if v != nil {
		_u.SetWeekStart(*v)
	}
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *AvailabilityDraftUpdate) SetTimezone(v string) *AvailabilityDraftUpdate {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *AvailabilityDraftUpdate) SetNillableTimezone(v *string) *AvailabilityDraftUpdate {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetSlots sets the "slots" field.
func (_u *AvailabilityDraftUpdate) SetSlots(v []schema.AvailabilitySlot) *AvailabilityDraftUpdate {
	_u.mutation.SetSlots(v)
	return _u
}

// AppendSlots appends value to the "slots" field.
func (_u *AvailabilityDraftUpdate) AppendSlots(v []schema.AvailabilitySlot) *AvailabilityDraftUpdate {
	_u.mutation.AppendSlots(v)
	return _u
}

// SetRawMessage sets the "raw_message" field.
func (_u *AvailabilityDraftUpdate) SetRawMessage(v string) *AvailabilityDraftUpdate {
	_u.mutation.SetRawMessage(v)
	return _u
}

// SetNillableRawMessage sets the "raw_message" field if the given value is not nil.
func (_u *AvailabilityDraftUpdate) SetNillableRawMessage(v *string) *AvailabilityDraftUpdate {
	if v != nil {
		_u.SetRawMessage(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AvailabilityDraftUpdate) SetExpiresAt(v time.Time) *AvailabilityDraftUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AvailabilityDraftUpdate) SetNillableExpiresAt(v *time.Time) *AvailabilityDraftUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetShop sets the "shop" edge to the Shop entity.
func (_u *AvailabilityDraftUpdate) SetShop(v *Shop) *AvailabilityDraftUpdate {
	return _u.SetShopID(v.ID)
}

// SetEmployee sets the "employee" edge to the Employee entity.
func (_u *AvailabilityDraftUpdate) SetEmployee(v *Employee) *AvailabilityDraftUpdate {
	return _u.SetEmployeeID(v.ID)
}

// Mutation returns the AvailabilityDraftMutation object of the builder.
func (_u *AvailabilityDraftUpdate) Mutation() *AvailabilityDraftMutation {
	return _u.mutation
}

// ClearShop clears the "shop" edge to the Shop entity.
func (_u *AvailabilityDraftUpdate) ClearShop() *AvailabilityDraftUpdate {
	_u.mutation.ClearShop()
	return _u
}

// ClearEmployee clears the "employee" edge to the Employee entity.
func (_u *AvailabilityDraftUpdate) ClearEmployee() *AvailabilityDraftUpdate {
	_u.mutation.ClearEmployee()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AvailabilityDraftUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AvailabilityDraftUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AvailabilityDraftUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AvailabilityDraftUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AvailabilityDraftUpdate) check() error {
	if _u.mutation.ShopCleared() && len(_u.mutation.ShopIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AvailabilityDraft.shop"`)
	}
	if _u.mutation.EmployeeCleared() && len(_u.mutation.EmployeeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AvailabilityDraft.employee"`)
	}
	return nil
}

func (_u *AvailabilityDraftUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(availabilitydraft.Table, availabilitydraft.Columns, sqlgraph.NewFieldSpec(availabilitydraft.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TelegramUserID(); ok {
		_spec.SetField(availabilitydraft.FieldTelegramUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTelegramUserID(); ok {
		_spec.AddField(availabilitydraft.FieldTelegramUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(availabilitydraft.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChatID(); ok {
		_spec.AddField(availabilitydraft.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.WeekStart(); ok {
		_spec.SetField(availabilitydraft.FieldWeekStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(availabilitydraft.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slots(); ok {
		_spec.SetField(availabilitydraft.FieldSlots, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSlots(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, availabilitydraft.FieldSlots, value)
		})
	}
	if value, ok := _u.mutation.RawMessage(); ok {
		_spec.SetField(availabilitydraft.FieldRawMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(availabilitydraft.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ShopCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availabilitydraft.ShopTable,
			Columns: []string{availabilitydraft.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShopIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availabilitydraft.ShopTable,
			Columns: []string{availabilitydraft.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EmployeeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availabilitydraft.EmployeeTable,
			Columns: []string{availabilitydraft.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availabilitydraft.EmployeeTable,
			Columns: []string{availabilitydraft.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{availabilitydraft.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AvailabilityDraftUpdateOne is the builder for updating a single AvailabilityDraft entity.
type AvailabilityDraftUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AvailabilityDraftMutation
}

// SetShopID sets the "shop_id" field.
func (_u *AvailabilityDraftUpdateOne) SetShopID(v uuid.UUID) *AvailabilityDraftUpdateOne {
	_u.mutation.SetShopID(v)
	return _u
}

// SetNillableShopID sets the "shop_id" field if the given value is not nil.
func (_u *AvailabilityDraftUpdateOne) SetNillableShopID(v *uuid.UUID) *AvailabilityDraftUpdateOne {
	if v != nil {
		_u.SetShopID(*v)
	}
	return _u
}

// SetEmployeeID sets the "employee_id" field.
func (_u *AvailabilityDraftUpdateOne) SetEmployeeID(v uuid.UUID) *AvailabilityDraftUpdateOne {
	_u.mutation.SetEmployeeID(v)
	return _u
}

// SetNillableEmployeeID sets the "employee_id" field if the given value is not nil.
func (_u *AvailabilityDraftUpdateOne) SetNillableEmployeeID(v *uuid.UUID) *AvailabilityDraftUpdateOne {
	if v != nil {
		_u.SetEmployeeID(*v)
	}
	return _u
}

// SetTelegramUserID sets the "telegram_user_id" field.
func (_u *AvailabilityDraftUpdateOne) SetTelegramUserID(v int64) *AvailabilityDraftUpdateOne {
	_u.mutation.ResetTelegramUserID()
	_u.mutation.SetTelegramUserID(v)
	return _u
}

// SetNillableTelegramUserID sets the "telegram_user_id" field if the given value is not nil.
func (_u *AvailabilityDraftUpdateOne) SetNillableTelegramUserID(v *int64) *AvailabilityDraftUpdateOne {
	if v != nil {
		_u.SetTelegramUserID(*v)
	}
	return _u
}

// AddTelegramUserID adds value to the "telegram_user_id" field.
func (_u *AvailabilityDraftUpdateOne) AddTelegramUserID(v int64) *AvailabilityDraftUpdateOne {
	_u.mutation.AddTelegramUserID(v)
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *AvailabilityDraftUpdateOne) SetChatID(v int64) *AvailabilityDraftUpdateOne {
	_u.mutation.ResetChatID()
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *AvailabilityDraftUpdateOne) SetNillableChatID(v *int64) *AvailabilityDraftUpdateOne {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// AddChatID adds value to the "chat_id" field.
func (_u *AvailabilityDraftUpdateOne) AddChatID(v int64) *AvailabilityDraftUpdateOne {
	_u.mutation.AddChatID(v)
	return _u
}

// SetWeekStart sets the "week_start" field.
func (_u *AvailabilityDraftUpdateOne) SetWeekStart(v time.Time) *AvailabilityDraftUpdateOne {
	_u.mutation.SetWeekStart(v)
	return _u
}

// SetNillableWeekStart sets the "week_start" field if the given value is not nil.
func (_u *AvailabilityDraftUpdateOne) SetNillableWeekStart(v *time.Time) *AvailabilityDraftUpdateOne {
	if v != nil {
		_u.SetWeekStart(*v)
	}
	return _u
}

// SetTimezone sets the "timezone" field.
func (_u *AvailabilityDraftUpdateOne) SetTimezone(v string) *AvailabilityDraftUpdateOne {
	_u.mutation.SetTimezone(v)
	return _u
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_u *AvailabilityDraftUpdateOne) SetNillableTimezone(v *string) *AvailabilityDraftUpdateOne {
	if v != nil {
		_u.SetTimezone(*v)
	}
	return _u
}

// SetSlots sets the "slots" field.
func (_u *AvailabilityDraftUpdateOne) SetSlots(v []schema.AvailabilitySlot) *AvailabilityDraftUpdateOne {
	_u.mutation.SetSlots(v)
	return _u
}

// AppendSlots appends value to the "slots" field.
func (_u *AvailabilityDraftUpdateOne) AppendSlots(v []schema.AvailabilitySlot) *AvailabilityDraftUpdateOne {
	_u.mutation.AppendSlots(v)
	return _u
}

// SetRawMessage sets the "raw_message" field.
func (_u *AvailabilityDraftUpdateOne) SetRawMessage(v string) *AvailabilityDraftUpdateOne {
	_u.mutation.SetRawMessage(v)
	return _u
}

// SetNillableRawMessage sets the "raw_message" field if the given value is not nil.
func (_u *AvailabilityDraftUpdateOne) SetNillableRawMessage(v *string) *AvailabilityDraftUpdateOne {
	if v != nil {
		_u.SetRawMessage(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AvailabilityDraftUpdateOne) SetExpiresAt(v time.Time) *AvailabilityDraftUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AvailabilityDraftUpdateOne) SetNillableExpiresAt(v *time.Time) *AvailabilityDraftUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetShop sets the "shop" edge to the Shop entity.
func (_u *AvailabilityDraftUpdateOne) SetShop(v *Shop) *AvailabilityDraftUpdateOne {
	return _u.SetShopID(v.ID)
}

// SetEmployee sets the "employee" edge to the Employee entity.
func (_u *AvailabilityDraftUpdateOne) SetEmployee(v *Employee) *AvailabilityDraftUpdateOne {
	return _u.SetEmployeeID(v.ID)
}

// Mutation returns the AvailabilityDraftMutation object of the builder.
func (_u *AvailabilityDraftUpdateOne) Mutation() *AvailabilityDraftMutation {
	return _u.mutation
}

// ClearShop clears the "shop" edge to the Shop entity.
func (_u *AvailabilityDraftUpdateOne) ClearShop() *AvailabilityDraftUpdateOne {
	_u.mutation.ClearShop()
	return _u
}

// ClearEmployee clears the "employee" edge to the Employee entity.
func (_u *AvailabilityDraftUpdateOne) ClearEmployee() *AvailabilityDraftUpdateOne {
	_u.mutation.ClearEmployee()
	return _u
}

// Where appends a list predicates to the AvailabilityDraftUpdate builder.
func (_u *AvailabilityDraftUpdateOne) Where(ps ...predicate.AvailabilityDraft) *AvailabilityDraftUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AvailabilityDraftUpdateOne) Select(field string, fields ...string) *AvailabilityDraftUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AvailabilityDraft entity.
func (_u *AvailabilityDraftUpdateOne) Save(ctx context.Context) (*AvailabilityDraft, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AvailabilityDraftUpdateOne) SaveX(ctx context.Context) *AvailabilityDraft {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AvailabilityDraftUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AvailabilityDraftUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AvailabilityDraftUpdateOne) check() error {
	if _u.mutation.ShopCleared() && len(_u.mutation.ShopIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AvailabilityDraft.shop"`)
	}
	if _u.mutation.EmployeeCleared() && len(_u.mutation.EmployeeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AvailabilityDraft.employee"`)
	}
	return nil
}

func (_u *AvailabilityDraftUpdateOne) sqlSave(ctx context.Context) (_node *AvailabilityDraft, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(availabilitydraft.Table, availabilitydraft.Columns, sqlgraph.NewFieldSpec(availabilitydraft.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AvailabilityDraft.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, availabilitydraft.FieldID)
		for _, f := range fields {
			if !availabilitydraft.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != availabilitydraft.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TelegramUserID(); ok {
		_spec.SetField(availabilitydraft.FieldTelegramUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTelegramUserID(); ok {
		_spec.AddField(availabilitydraft.FieldTelegramUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(availabilitydraft.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedChatID(); ok {
		_spec.AddField(availabilitydraft.FieldChatID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.WeekStart(); ok {
		_spec.SetField(availabilitydraft.FieldWeekStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Timezone(); ok {
		_spec.SetField(availabilitydraft.FieldTimezone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slots(); ok {
		_spec.SetField(availabilitydraft.FieldSlots, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSlots(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, availabilitydraft.FieldSlots, value)
		})
	}
	if value, ok := _u.mutation.RawMessage(); ok {
		_spec.SetField(availabilitydraft.FieldRawMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(availabilitydraft.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ShopCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availabilitydraft.ShopTable,
			Columns: []string{availabilitydraft.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShopIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availabilitydraft.ShopTable,
			Columns: []string{availabilitydraft.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EmployeeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availabilitydraft.EmployeeTable,
			Columns: []string{availabilitydraft.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   availabilitydraft.EmployeeTable,
			Columns: []string{availabilitydraft.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AvailabilityDraft{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{availabilitydraft.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
