// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/betallsoph/shiftz/internal/ent/employee"
	"github.com/betallsoph/shiftz/internal/ent/shop"
)

// Employee is the model entity for the Employee schema.
type Employee struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ShopID holds the value of the "shop_id" field.
	ShopID int `json:"shop_id,omitempty"`
	// TelegramUserID holds the value of the "telegram_user_id" field.
	TelegramUserID int64 `json:"telegram_user_id,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// MaxHoursPerWeek holds the value of the "max_hours_per_week" field.
	MaxHoursPerWeek float64 `json:"max_hours_per_week,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EmployeeQuery when eager-loading is set.
	Edges        EmployeeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EmployeeEdges holds the relations/edges for other nodes in the graph.
type EmployeeEdges struct {
	// Shop holds the value of the shop edge.
	Shop *Shop `json:"shop,omitempty"`
	// Availability holds the value of the availability edge.
	Availability []*Availability `json:"availability,omitempty"`
	// Assignments holds the value of the assignments edge.
	Assignments []*ScheduleAssignment `json:"assignments,omitempty"`
	// Votes holds the value of the votes edge.
	Votes []*ScheduleVote `json:"votes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// ShopOrErr returns the Shop value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EmployeeEdges) ShopOrErr() (*Shop, error) {
	if e.Shop != nil {
		return e.Shop, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: shop.Label}
	}
	return nil, &NotLoadedError{edge: "shop"}
}

// AvailabilityOrErr returns the Availability value or an error if the edge
// was not loaded in eager-loading.
func (e EmployeeEdges) AvailabilityOrErr() ([]*Availability, error) {
	if e.loadedTypes[1] {
		return e.Availability, nil
	}
	return nil, &NotLoadedError{edge: "availability"}
}

// AssignmentsOrErr returns the Assignments value or an error if the edge
// was not loaded in eager-loading.
func (e EmployeeEdges) AssignmentsOrErr() ([]*ScheduleAssignment, error) {
	if e.loadedTypes[2] {
		return e.Assignments, nil
	}
	return nil, &NotLoadedError{edge: "assignments"}
}

// VotesOrErr returns the Votes value or an error if the edge
// was not loaded in eager-loading.
func (e EmployeeEdges) VotesOrErr() ([]*ScheduleVote, error) {
	if e.loadedTypes[3] {
		return e.Votes, nil
	}
	return nil, &NotLoadedError{edge: "votes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Employee) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case employee.FieldActive:
			values[i] = new(sql.NullBool)
		case employee.FieldMaxHoursPerWeek:
			values[i] = new(sql.NullFloat64)
		case employee.FieldID, employee.FieldShopID, employee.FieldTelegramUserID:
			values[i] = new(sql.NullInt64)
		case employee.FieldDisplayName:
			values[i] = new(sql.NullString)
		case employee.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Employee fields.
func (_m *Employee) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case employee.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case employee.FieldShopID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field shop_id", values[i])
			} else if value.Valid {
				_m.ShopID = int(value.Int64)
			}
		case employee.FieldTelegramUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field telegram_user_id", values[i])
			} else if value.Valid {
				_m.TelegramUserID = value.Int64
			}
		case employee.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case employee.FieldMaxHoursPerWeek:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field max_hours_per_week", values[i])
			} else if value.Valid {
				_m.MaxHoursPerWeek = value.Float64
			}
		case employee.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		case employee.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Employee.
// This includes values selected through modifiers, order, etc.
func (_m *Employee) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryShop queries the "shop" edge of the Employee entity.
func (_m *Employee) QueryShop() *ShopQuery {
	return NewEmployeeClient(_m.config).QueryShop(_m)
}

// QueryAvailability queries the "availability" edge of the Employee entity.
func (_m *Employee) QueryAvailability() *AvailabilityQuery {
	return NewEmployeeClient(_m.config).QueryAvailability(_m)
}

// QueryAssignments queries the "assignments" edge of the Employee entity.
func (_m *Employee) QueryAssignments() *ScheduleAssignmentQuery {
	return NewEmployeeClient(_m.config).QueryAssignments(_m)
}

// QueryVotes queries the "votes" edge of the Employee entity.
func (_m *Employee) QueryVotes() *ScheduleVoteQuery {
	return NewEmployeeClient(_m.config).QueryVotes(_m)
}

// Update returns a builder for updating this Employee.
// Note that you need to call Employee.Unwrap() before calling this method if this Employee
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Employee) Update() *EmployeeUpdateOne {
	return NewEmployeeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Employee entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Employee) Unwrap() *Employee {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Employee is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Employee) String() string {
	var builder strings.Builder
	builder.WriteString("Employee(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("shop_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ShopID))
	builder.WriteString(", ")
	builder.WriteString("telegram_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TelegramUserID))
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("max_hours_per_week=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxHoursPerWeek))
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Employees is a parsable slice of Employee.
type Employees []*Employee
