// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/betallsoph/shiftz/internal/ent/availability"
	"github.com/betallsoph/shiftz/internal/ent/employee"
	"github.com/betallsoph/shiftz/internal/ent/predicate"
	"github.com/betallsoph/shiftz/internal/ent/scheduleassignment"
	"github.com/betallsoph/shiftz/internal/ent/schedulevote"
	"github.com/betallsoph/shiftz/internal/ent/shop"
	"github.com/google/uuid"
)

// EmployeeUpdate is the builder for updating Employee entities.
type EmployeeUpdate struct {
	config
	hooks    []Hook
	mutation *EmployeeMutation
}

// Where appends a list predicates to the EmployeeUpdate builder.
func (_u *EmployeeUpdate) Where(ps ...predicate.Employee) *EmployeeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetShopID sets the "shop_id" field.
func (_u *EmployeeUpdate) SetShopID(v uuid.UUID) *EmployeeUpdate {
	_u.mutation.SetShopID(v)
	return _u
}

// SetNillableShopID sets the "shop_id" field if the given value is not nil.
func (_u *EmployeeUpdate) SetNillableShopID(v *uuid.UUID) *EmployeeUpdate {
	if v != nil {
		_u.SetShopID(*v)
	}
	return _u
}

// SetTelegramUserID sets the "telegram_user_id" field.
func (_u *EmployeeUpdate) SetTelegramUserID(v int64) *EmployeeUpdate {
	_u.mutation.ResetTelegramUserID()
	_u.mutation.SetTelegramUserID(v)
	return _u
}

// SetNillableTelegramUserID sets the "telegram_user_id" field if the given value is not nil.
func (_u *EmployeeUpdate) SetNillableTelegramUserID(v *int64) *EmployeeUpdate {
	if v != nil {
		_u.SetTelegramUserID(*v)
	}
	return _u
}

// AddTelegramUserID adds value to the "telegram_user_id" field.
func (_u *EmployeeUpdate) AddTelegramUserID(v int64) *EmployeeUpdate {
	_u.mutation.AddTelegramUserID(v)
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *EmployeeUpdate) SetDisplayName(v string) *EmployeeUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *EmployeeUpdate) SetNillableDisplayName(v *string) *EmployeeUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *EmployeeUpdate) SetRole(v string) *EmployeeUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *EmployeeUpdate) SetNillableRole(v *string) *EmployeeUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetMaxHoursPerWeek sets the "max_hours_per_week" field.
func (_u *EmployeeUpdate) SetMaxHoursPerWeek(v float64) *EmployeeUpdate {
	_u.mutation.ResetMaxHoursPerWeek()
	_u.mutation.SetMaxHoursPerWeek(v)
	return _u
}

// SetNillableMaxHoursPerWeek sets the "max_hours_per_week" field if the given value is not nil.
func (_u *EmployeeUpdate) SetNillableMaxHoursPerWeek(v *float64) *EmployeeUpdate {
	if v != nil {
		_u.SetMaxHoursPerWeek(*v)
	}
	return _u
}

// AddMaxHoursPerWeek adds value to the "max_hours_per_week" field.
func (_u *EmployeeUpdate) AddMaxHoursPerWeek(v float64) *EmployeeUpdate {
	_u.mutation.AddMaxHoursPerWeek(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *EmployeeUpdate) SetIsActive(v bool) *EmployeeUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *EmployeeUpdate) SetNillableIsActive(v *bool) *EmployeeUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetShop sets the "shop" edge to the Shop entity.
func (_u *EmployeeUpdate) SetShop(v *Shop) *EmployeeUpdate {
	return _u.SetShopID(v.ID)
}

// AddAvailabilityIDs adds the "availabilities" edge to the Availability entity by IDs.
func (_u *EmployeeUpdate) AddAvailabilityIDs(ids ...uuid.UUID) *EmployeeUpdate {
	_u.mutation.AddAvailabilityIDs(ids...)
	return _u
}

// AddAvailabilities adds the "availabilities" edges to the Availability entity.
func (_u *EmployeeUpdate) AddAvailabilities(v ...*Availability) *EmployeeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAvailabilityIDs(ids...)
}

// AddAssignmentIDs adds the "assignments" edge to the ScheduleAssignment entity by IDs.
func (_u *EmployeeUpdate) AddAssignmentIDs(ids ...uuid.UUID) *EmployeeUpdate {
	_u.mutation.AddAssignmentIDs(ids...)
	return _u
}

// AddAssignments adds the "assignments" edges to the ScheduleAssignment entity.
func (_u *EmployeeUpdate) AddAssignments(v ...*ScheduleAssignment) *EmployeeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssignmentIDs(ids...)
}

// AddVoteIDs adds the "votes" edge to the ScheduleVote entity by IDs.
func (_u *EmployeeUpdate) AddVoteIDs(ids ...uuid.UUID) *EmployeeUpdate {
	_u.mutation.AddVoteIDs(ids...)
	return _u
}

// AddVotes adds the "votes" edges to the ScheduleVote entity.
func (_u *EmployeeUpdate) AddVotes(v ...*ScheduleVote) *EmployeeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVoteIDs(ids...)
}

// Mutation returns the EmployeeMutation object of the builder.
func (_u *EmployeeUpdate) Mutation() *EmployeeMutation {
	return _u.mutation
}

// ClearShop clears the "shop" edge to the Shop entity.
func (_u *EmployeeUpdate) ClearShop() *EmployeeUpdate {
	_u.mutation.ClearShop()
	return _u
}

// ClearAvailabilities clears all "availabilities" edges to the Availability entity.
func (_u *EmployeeUpdate) ClearAvailabilities() *EmployeeUpdate {
	_u.mutation.ClearAvailabilities()
	return _u
}

// RemoveAvailabilityIDs removes the "availabilities" edge to Availability entities by IDs.
func (_u *EmployeeUpdate) RemoveAvailabilityIDs(ids ...uuid.UUID) *EmployeeUpdate {
	_u.mutation.RemoveAvailabilityIDs(ids...)
	return _u
}

// RemoveAvailabilities removes "availabilities" edges to Availability entities.
func (_u *EmployeeUpdate) RemoveAvailabilities(v ...*Availability) *EmployeeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAvailabilityIDs(ids...)
}

// ClearAssignments clears all "assignments" edges to the ScheduleAssignment entity.
func (_u *EmployeeUpdate) ClearAssignments() *EmployeeUpdate {
	_u.mutation.ClearAssignments()
	return _u
}

// RemoveAssignmentIDs removes the "assignments" edge to ScheduleAssignment entities by IDs.
func (_u *EmployeeUpdate) RemoveAssignmentIDs(ids ...uuid.UUID) *EmployeeUpdate {
	_u.mutation.RemoveAssignmentIDs(ids...)
	return _u
}

// RemoveAssignments removes "assignments" edges to ScheduleAssignment entities.
func (_u *EmployeeUpdate) RemoveAssignments(v ...*ScheduleAssignment) *EmployeeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssignmentIDs(ids...)
}

// ClearVotes clears all "votes" edges to the ScheduleVote entity.
func (_u *EmployeeUpdate) ClearVotes() *EmployeeUpdate {
	_u.mutation.ClearVotes()
	return _u
}

// RemoveVoteIDs removes the "votes" edge to ScheduleVote entities by IDs.
func (_u *EmployeeUpdate) RemoveVoteIDs(ids ...uuid.UUID) *EmployeeUpdate {
	_u.mutation.RemoveVoteIDs(ids...)
	return _u
}

// RemoveVotes removes "votes" edges to ScheduleVote entities.
func (_u *EmployeeUpdate) RemoveVotes(v ...*ScheduleVote) *EmployeeUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVoteIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EmployeeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmployeeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EmployeeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmployeeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmployeeUpdate) check() error {
	if _u.mutation.ShopCleared() && len(_u.mutation.ShopIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Employee.shop"`)
	}
	return nil
}

func (_u *EmployeeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(employee.Table, employee.Columns, sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TelegramUserID(); ok {
		_spec.SetField(employee.FieldTelegramUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTelegramUserID(); ok {
		_spec.AddField(employee.FieldTelegramUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(employee.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(employee.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxHoursPerWeek(); ok {
		_spec.SetField(employee.FieldMaxHoursPerWeek, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxHoursPerWeek(); ok {
		_spec.AddField(employee.FieldMaxHoursPerWeek, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(employee.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.ShopCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.ShopTable,
			Columns: []string{employee.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShopIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.ShopTable,
			Columns: []string{employee.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AvailabilitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.AvailabilitiesTable,
			Columns: []string{employee.AvailabilitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(availability.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAvailabilitiesIDs(); len(nodes) > 0 && !_u.mutation.AvailabilitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.AvailabilitiesTable,
			Columns: []string{employee.AvailabilitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(availability.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AvailabilitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.AvailabilitiesTable,
			Columns: []string{employee.AvailabilitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(availability.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.AssignmentsTable,
			Columns: []string{employee.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scheduleassignment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssignmentsIDs(); len(nodes) > 0 && !_u.mutation.AssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.AssignmentsTable,
			Columns: []string{employee.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scheduleassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.AssignmentsTable,
			Columns: []string{employee.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scheduleassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.VotesTable,
			Columns: []string{employee.VotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(schedulevote.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVotesIDs(); len(nodes) > 0 && !_u.mutation.VotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.VotesTable,
			Columns: []string{employee.VotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(schedulevote.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VotesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.VotesTable,
			Columns: []string{employee.VotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(schedulevote.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EmployeeUpdateOne is the builder for updating a single Employee entity.
type EmployeeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EmployeeMutation
}

// SetShopID sets the "shop_id" field.
func (_u *EmployeeUpdateOne) SetShopID(v uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.SetShopID(v)
	return _u
}

// SetNillableShopID sets the "shop_id" field if the given value is not nil.
func (_u *EmployeeUpdateOne) SetNillableShopID(v *uuid.UUID) *EmployeeUpdateOne {
	if v != nil {
		_u.SetShopID(*v)
	}
	return _u
}

// SetTelegramUserID sets the "telegram_user_id" field.
func (_u *EmployeeUpdateOne) SetTelegramUserID(v int64) *EmployeeUpdateOne {
	_u.mutation.ResetTelegramUserID()
	_u.mutation.SetTelegramUserID(v)
	return _u
}

// SetNillableTelegramUserID sets the "telegram_user_id" field if the given value is not nil.
func (_u *EmployeeUpdateOne) SetNillableTelegramUserID(v *int64) *EmployeeUpdateOne {
	if v != nil {
		_u.SetTelegramUserID(*v)
	}
	return _u
}

// AddTelegramUserID adds value to the "telegram_user_id" field.
func (_u *EmployeeUpdateOne) AddTelegramUserID(v int64) *EmployeeUpdateOne {
	_u.mutation.AddTelegramUserID(v)
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *EmployeeUpdateOne) SetDisplayName(v string) *EmployeeUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *EmployeeUpdateOne) SetNillableDisplayName(v *string) *EmployeeUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *EmployeeUpdateOne) SetRole(v string) *EmployeeUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *EmployeeUpdateOne) SetNillableRole(v *string) *EmployeeUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetMaxHoursPerWeek sets the "max_hours_per_week" field.
func (_u *EmployeeUpdateOne) SetMaxHoursPerWeek(v float64) *EmployeeUpdateOne {
	_u.mutation.ResetMaxHoursPerWeek()
	_u.mutation.SetMaxHoursPerWeek(v)
	return _u
}

// SetNillableMaxHoursPerWeek sets the "max_hours_per_week" field if the given value is not nil.
func (_u *EmployeeUpdateOne) SetNillableMaxHoursPerWeek(v *float64) *EmployeeUpdateOne {
	if v != nil {
		_u.SetMaxHoursPerWeek(*v)
	}
	return _u
}

// AddMaxHoursPerWeek adds value to the "max_hours_per_week" field.
func (_u *EmployeeUpdateOne) AddMaxHoursPerWeek(v float64) *EmployeeUpdateOne {
	_u.mutation.AddMaxHoursPerWeek(v)
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *EmployeeUpdateOne) SetIsActive(v bool) *EmployeeUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *EmployeeUpdateOne) SetNillableIsActive(v *bool) *EmployeeUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetShop sets the "shop" edge to the Shop entity.
func (_u *EmployeeUpdateOne) SetShop(v *Shop) *EmployeeUpdateOne {
	return _u.SetShopID(v.ID)
}

// AddAvailabilityIDs adds the "availabilities" edge to the Availability entity by IDs.
func (_u *EmployeeUpdateOne) AddAvailabilityIDs(ids ...uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.AddAvailabilityIDs(ids...)
	return _u
}

// AddAvailabilities adds the "availabilities" edges to the Availability entity.
func (_u *EmployeeUpdateOne) AddAvailabilities(v ...*Availability) *EmployeeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAvailabilityIDs(ids...)
}

// AddAssignmentIDs adds the "assignments" edge to the ScheduleAssignment entity by IDs.
func (_u *EmployeeUpdateOne) AddAssignmentIDs(ids ...uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.AddAssignmentIDs(ids...)
	return _u
}

// AddAssignments adds the "assignments" edges to the ScheduleAssignment entity.
func (_u *EmployeeUpdateOne) AddAssignments(v ...*ScheduleAssignment) *EmployeeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAssignmentIDs(ids...)
}

// AddVoteIDs adds the "votes" edge to the ScheduleVote entity by IDs.
func (_u *EmployeeUpdateOne) AddVoteIDs(ids ...uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.AddVoteIDs(ids...)
	return _u
}

// AddVotes adds the "votes" edges to the ScheduleVote entity.
func (_u *EmployeeUpdateOne) AddVotes(v ...*ScheduleVote) *EmployeeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddVoteIDs(ids...)
}

// Mutation returns the EmployeeMutation object of the builder.
func (_u *EmployeeUpdateOne) Mutation() *EmployeeMutation {
	return _u.mutation
}

// ClearShop clears the "shop" edge to the Shop entity.
func (_u *EmployeeUpdateOne) ClearShop() *EmployeeUpdateOne {
	_u.mutation.ClearShop()
	return _u
}

// ClearAvailabilities clears all "availabilities" edges to the Availability entity.
func (_u *EmployeeUpdateOne) ClearAvailabilities() *EmployeeUpdateOne {
	_u.mutation.ClearAvailabilities()
	return _u
}

// RemoveAvailabilityIDs removes the "availabilities" edge to Availability entities by IDs.
func (_u *EmployeeUpdateOne) RemoveAvailabilityIDs(ids ...uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.RemoveAvailabilityIDs(ids...)
	return _u
}

// RemoveAvailabilities removes "availabilities" edges to Availability entities.
func (_u *EmployeeUpdateOne) RemoveAvailabilities(v ...*Availability) *EmployeeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAvailabilityIDs(ids...)
}

// ClearAssignments clears all "assignments" edges to the ScheduleAssignment entity.
func (_u *EmployeeUpdateOne) ClearAssignments() *EmployeeUpdateOne {
	_u.mutation.ClearAssignments()
	return _u
}

// RemoveAssignmentIDs removes the "assignments" edge to ScheduleAssignment entities by IDs.
func (_u *EmployeeUpdateOne) RemoveAssignmentIDs(ids ...uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.RemoveAssignmentIDs(ids...)
	return _u
}

// RemoveAssignments removes "assignments" edges to ScheduleAssignment entities.
func (_u *EmployeeUpdateOne) RemoveAssignments(v ...*ScheduleAssignment) *EmployeeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAssignmentIDs(ids...)
}

// ClearVotes clears all "votes" edges to the ScheduleVote entity.
func (_u *EmployeeUpdateOne) ClearVotes() *EmployeeUpdateOne {
	_u.mutation.ClearVotes()
	return _u
}

// RemoveVoteIDs removes the "votes" edge to ScheduleVote entities by IDs.
func (_u *EmployeeUpdateOne) RemoveVoteIDs(ids ...uuid.UUID) *EmployeeUpdateOne {
	_u.mutation.RemoveVoteIDs(ids...)
	return _u
}

// RemoveVotes removes "votes" edges to ScheduleVote entities.
func (_u *EmployeeUpdateOne) RemoveVotes(v ...*ScheduleVote) *EmployeeUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveVoteIDs(ids...)
}

// Where appends a list predicates to the EmployeeUpdate builder.
func (_u *EmployeeUpdateOne) Where(ps ...predicate.Employee) *EmployeeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EmployeeUpdateOne) Select(field string, fields ...string) *EmployeeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Employee entity.
func (_u *EmployeeUpdateOne) Save(ctx context.Context) (*Employee, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmployeeUpdateOne) SaveX(ctx context.Context) *Employee {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EmployeeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmployeeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmployeeUpdateOne) check() error {
	if _u.mutation.ShopCleared() && len(_u.mutation.ShopIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Employee.shop"`)
	}
	return nil
}

func (_u *EmployeeUpdateOne) sqlSave(ctx context.Context) (_node *Employee, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(employee.Table, employee.Columns, sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Employee.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, employee.FieldID)
		for _, f := range fields {
			if !employee.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != employee.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TelegramUserID(); ok {
		_spec.SetField(employee.FieldTelegramUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTelegramUserID(); ok {
		_spec.AddField(employee.FieldTelegramUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(employee.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(employee.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxHoursPerWeek(); ok {
		_spec.SetField(employee.FieldMaxHoursPerWeek, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedMaxHoursPerWeek(); ok {
		_spec.AddField(employee.FieldMaxHoursPerWeek, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(employee.FieldIsActive, field.TypeBool, value)
	}
	if _u.mutation.ShopCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.ShopTable,
			Columns: []string{employee.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShopIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.ShopTable,
			Columns: []string{employee.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AvailabilitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.AvailabilitiesTable,
			Columns: []string{employee.AvailabilitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(availability.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAvailabilitiesIDs(); len(nodes) > 0 && !_u.mutation.AvailabilitiesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.AvailabilitiesTable,
			Columns: []string{employee.AvailabilitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(availability.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AvailabilitiesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.AvailabilitiesTable,
			Columns: []string{employee.AvailabilitiesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(availability.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.AssignmentsTable,
			Columns: []string{employee.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scheduleassignment.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAssignmentsIDs(); len(nodes) > 0 && !_u.mutation.AssignmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.AssignmentsTable,
			Columns: []string{employee.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scheduleassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.AssignmentsTable,
			Columns: []string{employee.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scheduleassignment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.VotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.VotesTable,
			Columns: []string{employee.VotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(schedulevote.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedVotesIDs(); len(nodes) > 0 && !_u.mutation.VotesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.VotesTable,
			Columns: []string{employee.VotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(schedulevote.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.VotesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   employee.VotesTable,
			Columns: []string{employee.VotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(schedulevote.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Employee{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
