// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/betallsoph/shiftz/internal/ent/employee"
	"github.com/betallsoph/shiftz/internal/ent/predicate"
	"github.com/betallsoph/shiftz/internal/ent/reminderdelivery"
	"github.com/betallsoph/shiftz/internal/ent/shop"
	"github.com/google/uuid"
)

// ReminderDeliveryUpdate is the builder for updating ReminderDelivery entities.
type ReminderDeliveryUpdate struct {
	config
	hooks    []Hook
	mutation *ReminderDeliveryMutation
}

// Where appends a list predicates to the ReminderDeliveryUpdate builder.
func (_u *ReminderDeliveryUpdate) Where(ps ...predicate.ReminderDelivery) *ReminderDeliveryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetShopID sets the "shop_id" field.
func (_u *ReminderDeliveryUpdate) SetShopID(v uuid.UUID) *ReminderDeliveryUpdate {
	_u.mutation.SetShopID(v)
	return _u
}

// SetNillableShopID sets the "shop_id" field if the given value is not nil.
func (_u *ReminderDeliveryUpdate) SetNillableShopID(v *uuid.UUID) *ReminderDeliveryUpdate {
	if v != nil {
		_u.SetShopID(*v)
	}
	return _u
}

// SetEmployeeID sets the "employee_id" field.
func (_u *ReminderDeliveryUpdate) SetEmployeeID(v uuid.UUID) *ReminderDeliveryUpdate {
	_u.mutation.SetEmployeeID(v)
	return _u
}

// SetNillableEmployeeID sets the "employee_id" field if the given value is not nil.
func (_u *ReminderDeliveryUpdate) SetNillableEmployeeID(v *uuid.UUID) *ReminderDeliveryUpdate {
	if v != nil {
		_u.SetEmployeeID(*v)
	}
	return _u
}

// SetWeekStart sets the "week_start" field.
func (_u *ReminderDeliveryUpdate) SetWeekStart(v time.Time) *ReminderDeliveryUpdate {
	_u.mutation.SetWeekStart(v)
	return _u
}

// SetNillableWeekStart sets the "week_start" field if the given value is not nil.
func (_u *ReminderDeliveryUpdate) SetNillableWeekStart(v *time.Time) *ReminderDeliveryUpdate {
	if v != nil {
		_u.SetWeekStart(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *ReminderDeliveryUpdate) SetKind(v string) *ReminderDeliveryUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ReminderDeliveryUpdate) SetNillableKind(v *string) *ReminderDeliveryUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReminderDeliveryUpdate) SetStatus(v reminderdelivery.Status) *ReminderDeliveryUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReminderDeliveryUpdate) SetNillableStatus(v *reminderdelivery.Status) *ReminderDeliveryUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *ReminderDeliveryUpdate) SetAttempts(v int) *ReminderDeliveryUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *ReminderDeliveryUpdate) SetNillableAttempts(v *int) *ReminderDeliveryUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *ReminderDeliveryUpdate) AddAttempts(v int) *ReminderDeliveryUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *ReminderDeliveryUpdate) SetLastError(v string) *ReminderDeliveryUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *ReminderDeliveryUpdate) SetNillableLastError(v *string) *ReminderDeliveryUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *ReminderDeliveryUpdate) ClearLastError() *ReminderDeliveryUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *ReminderDeliveryUpdate) SetSentAt(v time.Time) *ReminderDeliveryUpdate {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *ReminderDeliveryUpdate) SetNillableSentAt(v *time.Time) *ReminderDeliveryUpdate {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// ClearSentAt clears the value of the "sent_at" field.
func (_u *ReminderDeliveryUpdate) ClearSentAt() *ReminderDeliveryUpdate {
	_u.mutation.ClearSentAt()
	return _u
}

// SetShop sets the "shop" edge to the Shop entity.
func (_u *ReminderDeliveryUpdate) SetShop(v *Shop) *ReminderDeliveryUpdate {
	return _u.SetShopID(v.ID)
}

// SetEmployee sets the "employee" edge to the Employee entity.
func (_u *ReminderDeliveryUpdate) SetEmployee(v *Employee) *ReminderDeliveryUpdate {
	return _u.SetEmployeeID(v.ID)
}

// Mutation returns the ReminderDeliveryMutation object of the builder.
func (_u *ReminderDeliveryUpdate) Mutation() *ReminderDeliveryMutation {
	return _u.mutation
}

// ClearShop clears the "shop" edge to the Shop entity.
func (_u *ReminderDeliveryUpdate) ClearShop() *ReminderDeliveryUpdate {
	_u.mutation.ClearShop()
	return _u
}

// ClearEmployee clears the "employee" edge to the Employee entity.
func (_u *ReminderDeliveryUpdate) ClearEmployee() *ReminderDeliveryUpdate {
	_u.mutation.ClearEmployee()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReminderDeliveryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReminderDeliveryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReminderDeliveryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReminderDeliveryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReminderDeliveryUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := reminderdelivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReminderDelivery.status": %w`, err)}
		}
	}
	if _u.mutation.ShopCleared() && len(_u.mutation.ShopIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReminderDelivery.shop"`)
	}
	if _u.mutation.EmployeeCleared() && len(_u.mutation.EmployeeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReminderDelivery.employee"`)
	}
	return nil
}

func (_u *ReminderDeliveryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reminderdelivery.Table, reminderdelivery.Columns, sqlgraph.NewFieldSpec(reminderdelivery.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.WeekStart(); ok {
		_spec.SetField(reminderdelivery.FieldWeekStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(reminderdelivery.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(reminderdelivery.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(reminderdelivery.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(reminderdelivery.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(reminderdelivery.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(reminderdelivery.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(reminderdelivery.FieldSentAt, field.TypeTime, value)
	}
	if _u.mutation.SentAtCleared() {
		_spec.ClearField(reminderdelivery.FieldSentAt, field.TypeTime)
	}
	if _u.mutation.ShopCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reminderdelivery.ShopTable,
			Columns: []string{reminderdelivery.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShopIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reminderdelivery.ShopTable,
			Columns: []string{reminderdelivery.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EmployeeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reminderdelivery.EmployeeTable,
			Columns: []string{reminderdelivery.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reminderdelivery.EmployeeTable,
			Columns: []string{reminderdelivery.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reminderdelivery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReminderDeliveryUpdateOne is the builder for updating a single ReminderDelivery entity.
type ReminderDeliveryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReminderDeliveryMutation
}

// SetShopID sets the "shop_id" field.
func (_u *ReminderDeliveryUpdateOne) SetShopID(v uuid.UUID) *ReminderDeliveryUpdateOne {
	_u.mutation.SetShopID(v)
	return _u
}

// SetNillableShopID sets the "shop_id" field if the given value is not nil.
func (_u *ReminderDeliveryUpdateOne) SetNillableShopID(v *uuid.UUID) *ReminderDeliveryUpdateOne {
	if v != nil {
		_u.SetShopID(*v)
	}
	return _u
}

// SetEmployeeID sets the "employee_id" field.
func (_u *ReminderDeliveryUpdateOne) SetEmployeeID(v uuid.UUID) *ReminderDeliveryUpdateOne {
	_u.mutation.SetEmployeeID(v)
	return _u
}

// SetNillableEmployeeID sets the "employee_id" field if the given value is not nil.
func (_u *ReminderDeliveryUpdateOne) SetNillableEmployeeID(v *uuid.UUID) *ReminderDeliveryUpdateOne {
	if v != nil {
		_u.SetEmployeeID(*v)
	}
	return _u
}

// SetWeekStart sets the "week_start" field.
func (_u *ReminderDeliveryUpdateOne) SetWeekStart(v time.Time) *ReminderDeliveryUpdateOne {
	_u.mutation.SetWeekStart(v)
	return _u
}

// SetNillableWeekStart sets the "week_start" field if the given value is not nil.
func (_u *ReminderDeliveryUpdateOne) SetNillableWeekStart(v *time.Time) *ReminderDeliveryUpdateOne {
	if v != nil {
		_u.SetWeekStart(*v)
	}
	return _u
}

// SetKind sets the "kind" field.
func (_u *ReminderDeliveryUpdateOne) SetKind(v string) *ReminderDeliveryUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ReminderDeliveryUpdateOne) SetNillableKind(v *string) *ReminderDeliveryUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReminderDeliveryUpdateOne) SetStatus(v reminderdelivery.Status) *ReminderDeliveryUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReminderDeliveryUpdateOne) SetNillableStatus(v *reminderdelivery.Status) *ReminderDeliveryUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *ReminderDeliveryUpdateOne) SetAttempts(v int) *ReminderDeliveryUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *ReminderDeliveryUpdateOne) SetNillableAttempts(v *int) *ReminderDeliveryUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *ReminderDeliveryUpdateOne) AddAttempts(v int) *ReminderDeliveryUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *ReminderDeliveryUpdateOne) SetLastError(v string) *ReminderDeliveryUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *ReminderDeliveryUpdateOne) SetNillableLastError(v *string) *ReminderDeliveryUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *ReminderDeliveryUpdateOne) ClearLastError() *ReminderDeliveryUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetSentAt sets the "sent_at" field.
func (_u *ReminderDeliveryUpdateOne) SetSentAt(v time.Time) *ReminderDeliveryUpdateOne {
	_u.mutation.SetSentAt(v)
	return _u
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_u *ReminderDeliveryUpdateOne) SetNillableSentAt(v *time.Time) *ReminderDeliveryUpdateOne {
	if v != nil {
		_u.SetSentAt(*v)
	}
	return _u
}

// ClearSentAt clears the value of the "sent_at" field.
func (_u *ReminderDeliveryUpdateOne) ClearSentAt() *ReminderDeliveryUpdateOne {
	_u.mutation.ClearSentAt()
	return _u
}

// SetShop sets the "shop" edge to the Shop entity.
func (_u *ReminderDeliveryUpdateOne) SetShop(v *Shop) *ReminderDeliveryUpdateOne {
	return _u.SetShopID(v.ID)
}

// SetEmployee sets the "employee" edge to the Employee entity.
func (_u *ReminderDeliveryUpdateOne) SetEmployee(v *Employee) *ReminderDeliveryUpdateOne {
	return _u.SetEmployeeID(v.ID)
}

// Mutation returns the ReminderDeliveryMutation object of the builder.
func (_u *ReminderDeliveryUpdateOne) Mutation() *ReminderDeliveryMutation {
	return _u.mutation
}

// ClearShop clears the "shop" edge to the Shop entity.
func (_u *ReminderDeliveryUpdateOne) ClearShop() *ReminderDeliveryUpdateOne {
	_u.mutation.ClearShop()
	return _u
}

// ClearEmployee clears the "employee" edge to the Employee entity.
func (_u *ReminderDeliveryUpdateOne) ClearEmployee() *ReminderDeliveryUpdateOne {
	_u.mutation.ClearEmployee()
	return _u
}

// Where appends a list predicates to the ReminderDeliveryUpdate builder.
func (_u *ReminderDeliveryUpdateOne) Where(ps ...predicate.ReminderDelivery) *ReminderDeliveryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReminderDeliveryUpdateOne) Select(field string, fields ...string) *ReminderDeliveryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReminderDelivery entity.
func (_u *ReminderDeliveryUpdateOne) Save(ctx context.Context) (*ReminderDelivery, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReminderDeliveryUpdateOne) SaveX(ctx context.Context) *ReminderDelivery {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReminderDeliveryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReminderDeliveryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReminderDeliveryUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := reminderdelivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReminderDelivery.status": %w`, err)}
		}
	}
	if _u.mutation.ShopCleared() && len(_u.mutation.ShopIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReminderDelivery.shop"`)
	}
	if _u.mutation.EmployeeCleared() && len(_u.mutation.EmployeeIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ReminderDelivery.employee"`)
	}
	return nil
}

func (_u *ReminderDeliveryUpdateOne) sqlSave(ctx context.Context) (_node *ReminderDelivery, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(reminderdelivery.Table, reminderdelivery.Columns, sqlgraph.NewFieldSpec(reminderdelivery.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReminderDelivery.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reminderdelivery.FieldID)
		for _, f := range fields {
			if !reminderdelivery.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != reminderdelivery.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.WeekStart(); ok {
		_spec.SetField(reminderdelivery.FieldWeekStart, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(reminderdelivery.FieldKind, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(reminderdelivery.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(reminderdelivery.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(reminderdelivery.FieldAttempts, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(reminderdelivery.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(reminderdelivery.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.SentAt(); ok {
		_spec.SetField(reminderdelivery.FieldSentAt, field.TypeTime, value)
	}
	if _u.mutation.SentAtCleared() {
		_spec.ClearField(reminderdelivery.FieldSentAt, field.TypeTime)
	}
	if _u.mutation.ShopCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reminderdelivery.ShopTable,
			Columns: []string{reminderdelivery.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ShopIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reminderdelivery.ShopTable,
			Columns: []string{reminderdelivery.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EmployeeCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reminderdelivery.EmployeeTable,
			Columns: []string{reminderdelivery.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reminderdelivery.EmployeeTable,
			Columns: []string{reminderdelivery.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ReminderDelivery{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{reminderdelivery.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
