// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/betallsoph/shiftz/internal/ent/employee"
	"github.com/betallsoph/shiftz/internal/ent/reminderdelivery"
	"github.com/betallsoph/shiftz/internal/ent/shop"
	"github.com/google/uuid"
)

// ReminderDeliveryCreate is the builder for creating a ReminderDelivery entity.
type ReminderDeliveryCreate struct {
	config
	mutation *ReminderDeliveryMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetShopID sets the "shop_id" field.
func (_c *ReminderDeliveryCreate) SetShopID(v uuid.UUID) *ReminderDeliveryCreate {
	_c.mutation.SetShopID(v)
	return _c
}

// SetEmployeeID sets the "employee_id" field.
func (_c *ReminderDeliveryCreate) SetEmployeeID(v uuid.UUID) *ReminderDeliveryCreate {
	_c.mutation.SetEmployeeID(v)
	return _c
}

// SetWeekStart sets the "week_start" field.
func (_c *ReminderDeliveryCreate) SetWeekStart(v time.Time) *ReminderDeliveryCreate {
	_c.mutation.SetWeekStart(v)
	return _c
}

// SetKind sets the "kind" field.
func (_c *ReminderDeliveryCreate) SetKind(v string) *ReminderDeliveryCreate {
	_c.mutation.SetKind(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ReminderDeliveryCreate) SetStatus(v reminderdelivery.Status) *ReminderDeliveryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ReminderDeliveryCreate) SetNillableStatus(v *reminderdelivery.Status) *ReminderDeliveryCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *ReminderDeliveryCreate) SetAttempts(v int) *ReminderDeliveryCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_c *ReminderDeliveryCreate) SetNillableAttempts(v *int) *ReminderDeliveryCreate {
	if v != nil {
		_c.SetAttempts(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *ReminderDeliveryCreate) SetLastError(v string) *ReminderDeliveryCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *ReminderDeliveryCreate) SetNillableLastError(v *string) *ReminderDeliveryCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReminderDeliveryCreate) SetCreatedAt(v time.Time) *ReminderDeliveryCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReminderDeliveryCreate) SetNillableCreatedAt(v *time.Time) *ReminderDeliveryCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetSentAt sets the "sent_at" field.
func (_c *ReminderDeliveryCreate) SetSentAt(v time.Time) *ReminderDeliveryCreate {
	_c.mutation.SetSentAt(v)
	return _c
}

// SetNillableSentAt sets the "sent_at" field if the given value is not nil.
func (_c *ReminderDeliveryCreate) SetNillableSentAt(v *time.Time) *ReminderDeliveryCreate {
	if v != nil {
		_c.SetSentAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ReminderDeliveryCreate) SetID(v uuid.UUID) *ReminderDeliveryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ReminderDeliveryCreate) SetNillableID(v *uuid.UUID) *ReminderDeliveryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetShop sets the "shop" edge to the Shop entity.
func (_c *ReminderDeliveryCreate) SetShop(v *Shop) *ReminderDeliveryCreate {
	return _c.SetShopID(v.ID)
}

// SetEmployee sets the "employee" edge to the Employee entity.
func (_c *ReminderDeliveryCreate) SetEmployee(v *Employee) *ReminderDeliveryCreate {
	return _c.SetEmployeeID(v.ID)
}

// Mutation returns the ReminderDeliveryMutation object of the builder.
func (_c *ReminderDeliveryCreate) Mutation() *ReminderDeliveryMutation {
	return _c.mutation
}

// Save creates the ReminderDelivery in the database.
func (_c *ReminderDeliveryCreate) Save(ctx context.Context) (*ReminderDelivery, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReminderDeliveryCreate) SaveX(ctx context.Context) *ReminderDelivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReminderDeliveryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReminderDeliveryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReminderDeliveryCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := reminderdelivery.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		v := reminderdelivery.DefaultAttempts
		_c.mutation.SetAttempts(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := reminderdelivery.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := reminderdelivery.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReminderDeliveryCreate) check() error {
	if _, ok := _c.mutation.ShopID(); !ok {
		return &ValidationError{Name: "shop_id", err: errors.New(`ent: missing required field "ReminderDelivery.shop_id"`)}
	}
	if _, ok := _c.mutation.EmployeeID(); !ok {
		return &ValidationError{Name: "employee_id", err: errors.New(`ent: missing required field "ReminderDelivery.employee_id"`)}
	}
	if _, ok := _c.mutation.WeekStart(); !ok {
		return &ValidationError{Name: "week_start", err: errors.New(`ent: missing required field "ReminderDelivery.week_start"`)}
	}
	if _, ok := _c.mutation.Kind(); !ok {
		return &ValidationError{Name: "kind", err: errors.New(`ent: missing required field "ReminderDelivery.kind"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ReminderDelivery.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := reminderdelivery.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReminderDelivery.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "ReminderDelivery.attempts"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ReminderDelivery.created_at"`)}
	}
	if len(_c.mutation.ShopIDs()) == 0 {
		return &ValidationError{Name: "shop", err: errors.New(`ent: missing required edge "ReminderDelivery.shop"`)}
	}
	if len(_c.mutation.EmployeeIDs()) == 0 {
		return &ValidationError{Name: "employee", err: errors.New(`ent: missing required edge "ReminderDelivery.employee"`)}
	}
	return nil
}

func (_c *ReminderDeliveryCreate) sqlSave(ctx context.Context) (*ReminderDelivery, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReminderDeliveryCreate) createSpec() (*ReminderDelivery, *sqlgraph.CreateSpec) {
	var (
		_node = &ReminderDelivery{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(reminderdelivery.Table, sqlgraph.NewFieldSpec(reminderdelivery.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.WeekStart(); ok {
		_spec.SetField(reminderdelivery.FieldWeekStart, field.TypeTime, value)
		_node.WeekStart = value
	}
	if value, ok := _c.mutation.Kind(); ok {
		_spec.SetField(reminderdelivery.FieldKind, field.TypeString, value)
		_node.Kind = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(reminderdelivery.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(reminderdelivery.FieldAttempts, field.TypeInt, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(reminderdelivery.FieldLastError, field.TypeString, value)
		_node.LastError = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(reminderdelivery.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.SentAt(); ok {
		_spec.SetField(reminderdelivery.FieldSentAt, field.TypeTime, value)
		_node.SentAt = &value
	}
	if nodes := _c.mutation.ShopIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reminderdelivery.ShopTable,
			Columns: []string{reminderdelivery.ShopColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shop.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ShopID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EmployeeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   reminderdelivery.EmployeeTable,
			Columns: []string{reminderdelivery.EmployeeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EmployeeID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReminderDelivery.Create().
//		SetShopID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReminderDeliveryUpsert) {
//			SetShopID(v+v).
//		}).
//		Exec(ctx)
func (_c *ReminderDeliveryCreate) OnConflict(opts ...sql.ConflictOption) *ReminderDeliveryUpsertOne {
	_c.conflict = opts
	return &ReminderDeliveryUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReminderDelivery.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReminderDeliveryCreate) OnConflictColumns(columns ...string) *ReminderDeliveryUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReminderDeliveryUpsertOne{
		create: _c,
	}
}

type (
	// ReminderDeliveryUpsertOne is the builder for "upsert"-ing
	//  one ReminderDelivery node.
	ReminderDeliveryUpsertOne struct {
		create *ReminderDeliveryCreate
	}

	// ReminderDeliveryUpsert is the "OnConflict" setter.
	ReminderDeliveryUpsert struct {
		*sql.UpdateSet
	}
)

// SetShopID sets the "shop_id" field.
func (u *ReminderDeliveryUpsert) SetShopID(v uuid.UUID) *ReminderDeliveryUpsert {
	u.Set(reminderdelivery.FieldShopID, v)
	return u
}

// UpdateShopID sets the "shop_id" field to the value that was provided on create.
func (u *ReminderDeliveryUpsert) UpdateShopID() *ReminderDeliveryUpsert {
	u.SetExcluded(reminderdelivery.FieldShopID)
	return u
}

// SetEmployeeID sets the "employee_id" field.
func (u *ReminderDeliveryUpsert) SetEmployeeID(v uuid.UUID) *ReminderDeliveryUpsert {
	u.Set(reminderdelivery.FieldEmployeeID, v)
	return u
}

// UpdateEmployeeID sets the "employee_id" field to the value that was provided on create.
func (u *ReminderDeliveryUpsert) UpdateEmployeeID() *ReminderDeliveryUpsert {
	u.SetExcluded(reminderdelivery.FieldEmployeeID)
	return u
}

// SetWeekStart sets the "week_start" field.
func (u *ReminderDeliveryUpsert) SetWeekStart(v time.Time) *ReminderDeliveryUpsert {
	u.Set(reminderdelivery.FieldWeekStart, v)
	return u
}

// UpdateWeekStart sets the "week_start" field to the value that was provided on create.
func (u *ReminderDeliveryUpsert) UpdateWeekStart() *ReminderDeliveryUpsert {
	u.SetExcluded(reminderdelivery.FieldWeekStart)
	return u
}

// SetKind sets the "kind" field.
func (u *ReminderDeliveryUpsert) SetKind(v string) *ReminderDeliveryUpsert {
	u.Set(reminderdelivery.FieldKind, v)
	return u
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ReminderDeliveryUpsert) UpdateKind() *ReminderDeliveryUpsert {
	u.SetExcluded(reminderdelivery.FieldKind)
	return u
}

// SetStatus sets the "status" field.
func (u *ReminderDeliveryUpsert) SetStatus(v reminderdelivery.Status) *ReminderDeliveryUpsert {
	u.Set(reminderdelivery.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReminderDeliveryUpsert) UpdateStatus() *ReminderDeliveryUpsert {
	u.SetExcluded(reminderdelivery.FieldStatus)
	return u
}

// SetAttempts sets the "attempts" field.
func (u *ReminderDeliveryUpsert) SetAttempts(v int) *ReminderDeliveryUpsert {
	u.Set(reminderdelivery.FieldAttempts, v)
	return u
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *ReminderDeliveryUpsert) UpdateAttempts() *ReminderDeliveryUpsert {
	u.SetExcluded(reminderdelivery.FieldAttempts)
	return u
}

// AddAttempts adds v to the "attempts" field.
func (u *ReminderDeliveryUpsert) AddAttempts(v int) *ReminderDeliveryUpsert {
	u.Add(reminderdelivery.FieldAttempts, v)
	return u
}

// SetLastError sets the "last_error" field.
func (u *ReminderDeliveryUpsert) SetLastError(v string) *ReminderDeliveryUpsert {
	u.Set(reminderdelivery.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *ReminderDeliveryUpsert) UpdateLastError() *ReminderDeliveryUpsert {
	u.SetExcluded(reminderdelivery.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *ReminderDeliveryUpsert) ClearLastError() *ReminderDeliveryUpsert {
	u.SetNull(reminderdelivery.FieldLastError)
	return u
}

// SetSentAt sets the "sent_at" field.
func (u *ReminderDeliveryUpsert) SetSentAt(v time.Time) *ReminderDeliveryUpsert {
	u.Set(reminderdelivery.FieldSentAt, v)
	return u
}

// UpdateSentAt sets the "sent_at" field to the value that was provided on create.
func (u *ReminderDeliveryUpsert) UpdateSentAt() *ReminderDeliveryUpsert {
	u.SetExcluded(reminderdelivery.FieldSentAt)
	return u
}

// ClearSentAt clears the value of the "sent_at" field.
func (u *ReminderDeliveryUpsert) ClearSentAt() *ReminderDeliveryUpsert {
	u.SetNull(reminderdelivery.FieldSentAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ReminderDelivery.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(reminderdelivery.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ReminderDeliveryUpsertOne) UpdateNewValues() *ReminderDeliveryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(reminderdelivery.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(reminderdelivery.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReminderDelivery.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ReminderDeliveryUpsertOne) Ignore() *ReminderDeliveryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReminderDeliveryUpsertOne) DoNothing() *ReminderDeliveryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReminderDeliveryCreate.OnConflict
// documentation for more info.
func (u *ReminderDeliveryUpsertOne) Update(set func(*ReminderDeliveryUpsert)) *ReminderDeliveryUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReminderDeliveryUpsert{UpdateSet: update})
	}))
	return u
}

// SetShopID sets the "shop_id" field.
func (u *ReminderDeliveryUpsertOne) SetShopID(v uuid.UUID) *ReminderDeliveryUpsertOne {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.SetShopID(v)
	})
}

// UpdateShopID sets the "shop_id" field to the value that was provided on create.
func (u *ReminderDeliveryUpsertOne) UpdateShopID() *ReminderDeliveryUpsertOne {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.UpdateShopID()
	})
}

// SetEmployeeID sets the "employee_id" field.
func (u *ReminderDeliveryUpsertOne) SetEmployeeID(v uuid.UUID) *ReminderDeliveryUpsertOne {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.SetEmployeeID(v)
	})
}

// UpdateEmployeeID sets the "employee_id" field to the value that was provided on create.
func (u *ReminderDeliveryUpsertOne) UpdateEmployeeID() *ReminderDeliveryUpsertOne {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.UpdateEmployeeID()
	})
}

// SetWeekStart sets the "week_start" field.
func (u *ReminderDeliveryUpsertOne) SetWeekStart(v time.Time) *ReminderDeliveryUpsertOne {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.SetWeekStart(v)
	})
}

// UpdateWeekStart sets the "week_start" field to the value that was provided on create.
func (u *ReminderDeliveryUpsertOne) UpdateWeekStart() *ReminderDeliveryUpsertOne {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.UpdateWeekStart()
	})
}

// SetKind sets the "kind" field.
func (u *ReminderDeliveryUpsertOne) SetKind(v string) *ReminderDeliveryUpsertOne {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ReminderDeliveryUpsertOne) UpdateKind() *ReminderDeliveryUpsertOne {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.UpdateKind()
	})
}

// SetStatus sets the "status" field.
func (u *ReminderDeliveryUpsertOne) SetStatus(v reminderdelivery.Status) *ReminderDeliveryUpsertOne {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReminderDeliveryUpsertOne) UpdateStatus() *ReminderDeliveryUpsertOne {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.UpdateStatus()
	})
}

// SetAttempts sets the "attempts" field.
func (u *ReminderDeliveryUpsertOne) SetAttempts(v int) *ReminderDeliveryUpsertOne {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *ReminderDeliveryUpsertOne) AddAttempts(v int) *ReminderDeliveryUpsertOne {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *ReminderDeliveryUpsertOne) UpdateAttempts() *ReminderDeliveryUpsertOne {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.UpdateAttempts()
	})
}

// SetLastError sets the "last_error" field.
func (u *ReminderDeliveryUpsertOne) SetLastError(v string) *ReminderDeliveryUpsertOne {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *ReminderDeliveryUpsertOne) UpdateLastError() *ReminderDeliveryUpsertOne {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *ReminderDeliveryUpsertOne) ClearLastError() *ReminderDeliveryUpsertOne {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.ClearLastError()
	})
}

// SetSentAt sets the "sent_at" field.
func (u *ReminderDeliveryUpsertOne) SetSentAt(v time.Time) *ReminderDeliveryUpsertOne {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.SetSentAt(v)
	})
}

// UpdateSentAt sets the "sent_at" field to the value that was provided on create.
func (u *ReminderDeliveryUpsertOne) UpdateSentAt() *ReminderDeliveryUpsertOne {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.UpdateSentAt()
	})
}

// ClearSentAt clears the value of the "sent_at" field.
func (u *ReminderDeliveryUpsertOne) ClearSentAt() *ReminderDeliveryUpsertOne {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.ClearSentAt()
	})
}

// Exec executes the query.
func (u *ReminderDeliveryUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReminderDeliveryCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReminderDeliveryUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ReminderDeliveryUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ReminderDeliveryUpsertOne.ID is not supported by MySQL driver. Use ReminderDeliveryUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ReminderDeliveryUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ReminderDeliveryCreateBulk is the builder for creating many ReminderDelivery entities in bulk.
type ReminderDeliveryCreateBulk struct {
	config
	err      error
	builders []*ReminderDeliveryCreate
	conflict []sql.ConflictOption
}

// Save creates the ReminderDelivery entities in the database.
func (_c *ReminderDeliveryCreateBulk) Save(ctx context.Context) ([]*ReminderDelivery, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReminderDelivery, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReminderDeliveryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReminderDeliveryCreateBulk) SaveX(ctx context.Context) []*ReminderDelivery {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReminderDeliveryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReminderDeliveryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReminderDelivery.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReminderDeliveryUpsert) {
//			SetShopID(v+v).
//		}).
//		Exec(ctx)
func (_c *ReminderDeliveryCreateBulk) OnConflict(opts ...sql.ConflictOption) *ReminderDeliveryUpsertBulk {
	_c.conflict = opts
	return &ReminderDeliveryUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReminderDelivery.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReminderDeliveryCreateBulk) OnConflictColumns(columns ...string) *ReminderDeliveryUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReminderDeliveryUpsertBulk{
		create: _c,
	}
}

// ReminderDeliveryUpsertBulk is the builder for "upsert"-ing
// a bulk of ReminderDelivery nodes.
type ReminderDeliveryUpsertBulk struct {
	create *ReminderDeliveryCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ReminderDelivery.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(reminderdelivery.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ReminderDeliveryUpsertBulk) UpdateNewValues() *ReminderDeliveryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(reminderdelivery.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(reminderdelivery.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReminderDelivery.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ReminderDeliveryUpsertBulk) Ignore() *ReminderDeliveryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReminderDeliveryUpsertBulk) DoNothing() *ReminderDeliveryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReminderDeliveryCreateBulk.OnConflict
// documentation for more info.
func (u *ReminderDeliveryUpsertBulk) Update(set func(*ReminderDeliveryUpsert)) *ReminderDeliveryUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReminderDeliveryUpsert{UpdateSet: update})
	}))
	return u
}

// SetShopID sets the "shop_id" field.
func (u *ReminderDeliveryUpsertBulk) SetShopID(v uuid.UUID) *ReminderDeliveryUpsertBulk {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.SetShopID(v)
	})
}

// UpdateShopID sets the "shop_id" field to the value that was provided on create.
func (u *ReminderDeliveryUpsertBulk) UpdateShopID() *ReminderDeliveryUpsertBulk {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.UpdateShopID()
	})
}

// SetEmployeeID sets the "employee_id" field.
func (u *ReminderDeliveryUpsertBulk) SetEmployeeID(v uuid.UUID) *ReminderDeliveryUpsertBulk {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.SetEmployeeID(v)
	})
}

// UpdateEmployeeID sets the "employee_id" field to the value that was provided on create.
func (u *ReminderDeliveryUpsertBulk) UpdateEmployeeID() *ReminderDeliveryUpsertBulk {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.UpdateEmployeeID()
	})
}

// SetWeekStart sets the "week_start" field.
func (u *ReminderDeliveryUpsertBulk) SetWeekStart(v time.Time) *ReminderDeliveryUpsertBulk {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.SetWeekStart(v)
	})
}

// UpdateWeekStart sets the "week_start" field to the value that was provided on create.
func (u *ReminderDeliveryUpsertBulk) UpdateWeekStart() *ReminderDeliveryUpsertBulk {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.UpdateWeekStart()
	})
}

// SetKind sets the "kind" field.
func (u *ReminderDeliveryUpsertBulk) SetKind(v string) *ReminderDeliveryUpsertBulk {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.SetKind(v)
	})
}

// UpdateKind sets the "kind" field to the value that was provided on create.
func (u *ReminderDeliveryUpsertBulk) UpdateKind() *ReminderDeliveryUpsertBulk {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.UpdateKind()
	})
}

// SetStatus sets the "status" field.
func (u *ReminderDeliveryUpsertBulk) SetStatus(v reminderdelivery.Status) *ReminderDeliveryUpsertBulk {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReminderDeliveryUpsertBulk) UpdateStatus() *ReminderDeliveryUpsertBulk {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.UpdateStatus()
	})
}

// SetAttempts sets the "attempts" field.
func (u *ReminderDeliveryUpsertBulk) SetAttempts(v int) *ReminderDeliveryUpsertBulk {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.SetAttempts(v)
	})
}

// AddAttempts adds v to the "attempts" field.
func (u *ReminderDeliveryUpsertBulk) AddAttempts(v int) *ReminderDeliveryUpsertBulk {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.AddAttempts(v)
	})
}

// UpdateAttempts sets the "attempts" field to the value that was provided on create.
func (u *ReminderDeliveryUpsertBulk) UpdateAttempts() *ReminderDeliveryUpsertBulk {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.UpdateAttempts()
	})
}

// SetLastError sets the "last_error" field.
func (u *ReminderDeliveryUpsertBulk) SetLastError(v string) *ReminderDeliveryUpsertBulk {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *ReminderDeliveryUpsertBulk) UpdateLastError() *ReminderDeliveryUpsertBulk {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *ReminderDeliveryUpsertBulk) ClearLastError() *ReminderDeliveryUpsertBulk {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.ClearLastError()
	})
}

// SetSentAt sets the "sent_at" field.
func (u *ReminderDeliveryUpsertBulk) SetSentAt(v time.Time) *ReminderDeliveryUpsertBulk {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.SetSentAt(v)
	})
}

// UpdateSentAt sets the "sent_at" field to the value that was provided on create.
func (u *ReminderDeliveryUpsertBulk) UpdateSentAt() *ReminderDeliveryUpsertBulk {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.UpdateSentAt()
	})
}

// ClearSentAt clears the value of the "sent_at" field.
func (u *ReminderDeliveryUpsertBulk) ClearSentAt() *ReminderDeliveryUpsertBulk {
	return u.Update(func(s *ReminderDeliveryUpsert) {
		s.ClearSentAt()
	})
}

// Exec executes the query.
func (u *ReminderDeliveryUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ReminderDeliveryCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReminderDeliveryCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReminderDeliveryUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
