// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/betallsoph/shiftz/internal/ent/predicate"
	"github.com/betallsoph/shiftz/internal/ent/reminderdelivery"
)

// ReminderDeliveryDelete is the builder for deleting a ReminderDelivery entity.
type ReminderDeliveryDelete struct {
	config
	hooks    []Hook
	mutation *ReminderDeliveryMutation
}

// Where appends a list predicates to the ReminderDeliveryDelete builder.
func (_d *ReminderDeliveryDelete) Where(ps ...predicate.ReminderDelivery) *ReminderDeliveryDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ReminderDeliveryDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ReminderDeliveryDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ReminderDeliveryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(reminderdelivery.Table, sqlgraph.NewFieldSpec(reminderdelivery.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ReminderDeliveryDeleteOne is the builder for deleting a single ReminderDelivery entity.
type ReminderDeliveryDeleteOne struct {
	_d *ReminderDeliveryDelete
}

// Where appends a list predicates to the ReminderDeliveryDelete builder.
func (_d *ReminderDeliveryDeleteOne) Where(ps ...predicate.ReminderDelivery) *ReminderDeliveryDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ReminderDeliveryDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{reminderdelivery.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ReminderDeliveryDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
