// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/betallsoph/shiftz/internal/ent/employee"
	"github.com/betallsoph/shiftz/internal/ent/reminderdelivery"
	"github.com/betallsoph/shiftz/internal/ent/shop"
	"github.com/google/uuid"
)

// ReminderDelivery is the model entity for the ReminderDelivery schema.
type ReminderDelivery struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ShopID holds the value of the "shop_id" field.
	ShopID uuid.UUID `json:"shop_id,omitempty"`
	// EmployeeID holds the value of the "employee_id" field.
	EmployeeID uuid.UUID `json:"employee_id,omitempty"`
	// WeekStart holds the value of the "week_start" field.
	WeekStart time.Time `json:"week_start,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind string `json:"kind,omitempty"`
	// Status holds the value of the "status" field.
	Status reminderdelivery.Status `json:"status,omitempty"`
	// Attempts holds the value of the "attempts" field.
	Attempts int `json:"attempts,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError *string `json:"last_error,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// SentAt holds the value of the "sent_at" field.
	SentAt *time.Time `json:"sent_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReminderDeliveryQuery when eager-loading is set.
	Edges        ReminderDeliveryEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ReminderDeliveryEdges holds the relations/edges for other nodes in the graph.
type ReminderDeliveryEdges struct {
	// Shop holds the value of the shop edge.
	Shop *Shop `json:"shop,omitempty"`
	// Employee holds the value of the employee edge.
	Employee *Employee `json:"employee,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ShopOrErr returns the Shop value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReminderDeliveryEdges) ShopOrErr() (*Shop, error) {
	if e.Shop != nil {
		return e.Shop, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: shop.Label}
	}
	return nil, &NotLoadedError{edge: "shop"}
}

// EmployeeOrErr returns the Employee value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReminderDeliveryEdges) EmployeeOrErr() (*Employee, error) {
	if e.Employee != nil {
		return e.Employee, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: employee.Label}
	}
	return nil, &NotLoadedError{edge: "employee"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReminderDelivery) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case reminderdelivery.FieldAttempts:
			values[i] = new(sql.NullInt64)
		case reminderdelivery.FieldKind, reminderdelivery.FieldStatus, reminderdelivery.FieldLastError:
			values[i] = new(sql.NullString)
		case reminderdelivery.FieldWeekStart, reminderdelivery.FieldCreatedAt, reminderdelivery.FieldSentAt:
			values[i] = new(sql.NullTime)
		case reminderdelivery.FieldID, reminderdelivery.FieldShopID, reminderdelivery.FieldEmployeeID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReminderDelivery fields.
func (_m *ReminderDelivery) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case reminderdelivery.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case reminderdelivery.FieldShopID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field shop_id", values[i])
			} else if value != nil {
				_m.ShopID = *value
			}
		case reminderdelivery.FieldEmployeeID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field employee_id", values[i])
			} else if value != nil {
				_m.EmployeeID = *value
			}
		case reminderdelivery.FieldWeekStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field week_start", values[i])
			} else if value.Valid {
				_m.WeekStart = value.Time
			}
		case reminderdelivery.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case reminderdelivery.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = reminderdelivery.Status(value.String)
			}
		case reminderdelivery.FieldAttempts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempts", values[i])
			} else if value.Valid {
				_m.Attempts = int(value.Int64)
			}
		case reminderdelivery.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		case reminderdelivery.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case reminderdelivery.FieldSentAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field sent_at", values[i])
			} else if value.Valid {
				_m.SentAt = new(time.Time)
				*_m.SentAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReminderDelivery.
// This includes values selected through modifiers, order, etc.
func (_m *ReminderDelivery) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryShop queries the "shop" edge of the ReminderDelivery entity.
func (_m *ReminderDelivery) QueryShop() *ShopQuery {
	return NewReminderDeliveryClient(_m.config).QueryShop(_m)
}

// QueryEmployee queries the "employee" edge of the ReminderDelivery entity.
func (_m *ReminderDelivery) QueryEmployee() *EmployeeQuery {
	return NewReminderDeliveryClient(_m.config).QueryEmployee(_m)
}

// Update returns a builder for updating this ReminderDelivery.
// Note that you need to call ReminderDelivery.Unwrap() before calling this method if this ReminderDelivery
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReminderDelivery) Update() *ReminderDeliveryUpdateOne {
	return NewReminderDeliveryClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReminderDelivery entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReminderDelivery) Unwrap() *ReminderDelivery {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReminderDelivery is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReminderDelivery) String() string {
	var builder strings.Builder
	builder.WriteString("ReminderDelivery(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("shop_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ShopID))
	builder.WriteString(", ")
	builder.WriteString("employee_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EmployeeID))
	builder.WriteString(", ")
	builder.WriteString("week_start=")
	builder.WriteString(_m.WeekStart.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("attempts=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attempts))
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.SentAt; v != nil {
		builder.WriteString("sent_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ReminderDeliveries is a parsable slice of ReminderDelivery.
type ReminderDeliveries []*ReminderDelivery
