// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/betallsoph/shiftz/internal/ent/availability"
	"github.com/betallsoph/shiftz/internal/ent/employee"
	"github.com/betallsoph/shiftz/internal/ent/rule"
	"github.com/betallsoph/shiftz/internal/ent/schedule"
	"github.com/betallsoph/shiftz/internal/ent/schedulevote"
	"github.com/betallsoph/shiftz/internal/ent/schema"
	"github.com/betallsoph/shiftz/internal/ent/shift"
	"github.com/betallsoph/shiftz/internal/ent/shop"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	availabilityFields := schema.Availability{}.Fields()
	_ = availabilityFields
	// availabilityDescPreference is the schema descriptor for preference field.
	availabilityDescPreference := availabilityFields[5].Descriptor()
	// availability.DefaultPreference holds the default value on creation for the preference field.
	availability.DefaultPreference = availabilityDescPreference.Default.(int)
	// availabilityDescNote is the schema descriptor for note field.
	availabilityDescNote := availabilityFields[6].Descriptor()
	// availability.DefaultNote holds the default value on creation for the note field.
	availability.DefaultNote = availabilityDescNote.Default.(string)
	// availabilityDescRawText is the schema descriptor for raw_text field.
	availabilityDescRawText := availabilityFields[7].Descriptor()
	// availability.DefaultRawText holds the default value on creation for the raw_text field.
	availability.DefaultRawText = availabilityDescRawText.Default.(string)
	// availabilityDescCreatedAt is the schema descriptor for created_at field.
	availabilityDescCreatedAt := availabilityFields[8].Descriptor()
	// availability.DefaultCreatedAt holds the default value on creation for the created_at field.
	availability.DefaultCreatedAt = availabilityDescCreatedAt.Default.(func() time.Time)
	employeeFields := schema.Employee{}.Fields()
	_ = employeeFields
	// employeeDescMaxHoursPerWeek is the schema descriptor for max_hours_per_week field.
	employeeDescMaxHoursPerWeek := employeeFields[3].Descriptor()
	// employee.DefaultMaxHoursPerWeek holds the default value on creation for the max_hours_per_week field.
	employee.DefaultMaxHoursPerWeek = employeeDescMaxHoursPerWeek.Default.(float64)
	// employeeDescActive is the schema descriptor for active field.
	employeeDescActive := employeeFields[4].Descriptor()
	// employee.DefaultActive holds the default value on creation for the active field.
	employee.DefaultActive = employeeDescActive.Default.(bool)
	// employeeDescCreatedAt is the schema descriptor for created_at field.
	employeeDescCreatedAt := employeeFields[5].Descriptor()
	// employee.DefaultCreatedAt holds the default value on creation for the created_at field.
	employee.DefaultCreatedAt = employeeDescCreatedAt.Default.(func() time.Time)
	ruleFields := schema.Rule{}.Fields()
	_ = ruleFields
	// ruleDescWeight is the schema descriptor for weight field.
	ruleDescWeight := ruleFields[3].Descriptor()
	// rule.DefaultWeight holds the default value on creation for the weight field.
	rule.DefaultWeight = ruleDescWeight.Default.(float64)
	// ruleDescSourceText is the schema descriptor for source_text field.
	ruleDescSourceText := ruleFields[4].Descriptor()
	// rule.DefaultSourceText holds the default value on creation for the source_text field.
	rule.DefaultSourceText = ruleDescSourceText.Default.(string)
	// ruleDescActive is the schema descriptor for active field.
	ruleDescActive := ruleFields[5].Descriptor()
	// rule.DefaultActive holds the default value on creation for the active field.
	rule.DefaultActive = ruleDescActive.Default.(bool)
	// ruleDescCreatedAt is the schema descriptor for created_at field.
	ruleDescCreatedAt := ruleFields[6].Descriptor()
	// rule.DefaultCreatedAt holds the default value on creation for the created_at field.
	rule.DefaultCreatedAt = ruleDescCreatedAt.Default.(func() time.Time)
	scheduleFields := schema.Schedule{}.Fields()
	_ = scheduleFields
	// scheduleDescLabel is the schema descriptor for label field.
	scheduleDescLabel := scheduleFields[2].Descriptor()
	// schedule.DefaultLabel holds the default value on creation for the label field.
	schedule.DefaultLabel = scheduleDescLabel.Default.(string)
	// scheduleDescScore is the schema descriptor for score field.
	scheduleDescScore := scheduleFields[4].Descriptor()
	// schedule.DefaultScore holds the default value on creation for the score field.
	schedule.DefaultScore = scheduleDescScore.Default.(float64)
	// scheduleDescCreatedAt is the schema descriptor for created_at field.
	scheduleDescCreatedAt := scheduleFields[5].Descriptor()
	// schedule.DefaultCreatedAt holds the default value on creation for the created_at field.
	schedule.DefaultCreatedAt = scheduleDescCreatedAt.Default.(func() time.Time)
	schedulevoteFields := schema.ScheduleVote{}.Fields()
	_ = schedulevoteFields
	// schedulevoteDescCreatedAt is the schema descriptor for created_at field.
	schedulevoteDescCreatedAt := schedulevoteFields[3].Descriptor()
	// schedulevote.DefaultCreatedAt holds the default value on creation for the created_at field.
	schedulevote.DefaultCreatedAt = schedulevoteDescCreatedAt.Default.(func() time.Time)
	shiftFields := schema.Shift{}.Fields()
	_ = shiftFields
	// shiftDescRole is the schema descriptor for role field.
	shiftDescRole := shiftFields[1].Descriptor()
	// shift.DefaultRole holds the default value on creation for the role field.
	shift.DefaultRole = shiftDescRole.Default.(string)
	// shiftDescMinStaff is the schema descriptor for min_staff field.
	shiftDescMinStaff := shiftFields[4].Descriptor()
	// shift.DefaultMinStaff holds the default value on creation for the min_staff field.
	shift.DefaultMinStaff = shiftDescMinStaff.Default.(int)
	// shift.MinStaffValidator is a validator for the "min_staff" field. It is called by the builders before save.
	shift.MinStaffValidator = shiftDescMinStaff.Validators[0].(func(int) error)
	// shiftDescMaxStaff is the schema descriptor for max_staff field.
	shiftDescMaxStaff := shiftFields[5].Descriptor()
	// shift.DefaultMaxStaff holds the default value on creation for the max_staff field.
	shift.DefaultMaxStaff = shiftDescMaxStaff.Default.(int)
	// shift.MaxStaffValidator is a validator for the "max_staff" field. It is called by the builders before save.
	shift.MaxStaffValidator = shiftDescMaxStaff.Validators[0].(func(int) error)
	// shiftDescCreatedAt is the schema descriptor for created_at field.
	shiftDescCreatedAt := shiftFields[6].Descriptor()
	// shift.DefaultCreatedAt holds the default value on creation for the created_at field.
	shift.DefaultCreatedAt = shiftDescCreatedAt.Default.(func() time.Time)
	shopFields := schema.Shop{}.Fields()
	_ = shopFields
	// shopDescTimezone is the schema descriptor for timezone field.
	shopDescTimezone := shopFields[1].Descriptor()
	// shop.DefaultTimezone holds the default value on creation for the timezone field.
	shop.DefaultTimezone = shopDescTimezone.Default.(string)
	// shopDescCreatedAt is the schema descriptor for created_at field.
	shopDescCreatedAt := shopFields[4].Descriptor()
	// shop.DefaultCreatedAt holds the default value on creation for the created_at field.
	shop.DefaultCreatedAt = shopDescCreatedAt.Default.(func() time.Time)
}
