// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/betallsoph/shiftz/internal/ent/schedule"
	"github.com/betallsoph/shiftz/internal/ent/shop"
)

// Schedule is the model entity for the Schedule schema.
type Schedule struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ShopID holds the value of the "shop_id" field.
	ShopID int `json:"shop_id,omitempty"`
	// WeekStart holds the value of the "week_start" field.
	WeekStart time.Time `json:"week_start,omitempty"`
	// Label holds the value of the "label" field.
	Label string `json:"label,omitempty"`
	// Status holds the value of the "status" field.
	Status schedule.Status `json:"status,omitempty"`
	// Score holds the value of the "score" field.
	Score float64 `json:"score,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ScheduleQuery when eager-loading is set.
	Edges        ScheduleEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ScheduleEdges holds the relations/edges for other nodes in the graph.
type ScheduleEdges struct {
	// Shop holds the value of the shop edge.
	Shop *Shop `json:"shop,omitempty"`
	// Assignments holds the value of the assignments edge.
	Assignments []*ScheduleAssignment `json:"assignments,omitempty"`
	// Votes holds the value of the votes edge.
	Votes []*ScheduleVote `json:"votes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ShopOrErr returns the Shop value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ScheduleEdges) ShopOrErr() (*Shop, error) {
	if e.Shop != nil {
		return e.Shop, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: shop.Label}
	}
	return nil, &NotLoadedError{edge: "shop"}
}

// AssignmentsOrErr returns the Assignments value or an error if the edge
// was not loaded in eager-loading.
func (e ScheduleEdges) AssignmentsOrErr() ([]*ScheduleAssignment, error) {
	if e.loadedTypes[1] {
		return e.Assignments, nil
	}
	return nil, &NotLoadedError{edge: "assignments"}
}

// VotesOrErr returns the Votes value or an error if the edge
// was not loaded in eager-loading.
func (e ScheduleEdges) VotesOrErr() ([]*ScheduleVote, error) {
	if e.loadedTypes[2] {
		return e.Votes, nil
	}
	return nil, &NotLoadedError{edge: "votes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Schedule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case schedule.FieldScore:
			values[i] = new(sql.NullFloat64)
		case schedule.FieldID, schedule.FieldShopID:
			values[i] = new(sql.NullInt64)
		case schedule.FieldLabel, schedule.FieldStatus:
			values[i] = new(sql.NullString)
		case schedule.FieldWeekStart, schedule.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Schedule fields.
func (_m *Schedule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case schedule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case schedule.FieldShopID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field shop_id", values[i])
			} else if value.Valid {
				_m.ShopID = int(value.Int64)
			}
		case schedule.FieldWeekStart:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field week_start", values[i])
			} else if value.Valid {
				_m.WeekStart = value.Time
			}
		case schedule.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = value.String
			}
		case schedule.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = schedule.Status(value.String)
			}
		case schedule.FieldScore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field score", values[i])
			} else if value.Valid {
				_m.Score = value.Float64
			}
		case schedule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Schedule.
// This includes values selected through modifiers, order, etc.
func (_m *Schedule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryShop queries the "shop" edge of the Schedule entity.
func (_m *Schedule) QueryShop() *ShopQuery {
	return NewScheduleClient(_m.config).QueryShop(_m)
}

// QueryAssignments queries the "assignments" edge of the Schedule entity.
func (_m *Schedule) QueryAssignments() *ScheduleAssignmentQuery {
	return NewScheduleClient(_m.config).QueryAssignments(_m)
}

// QueryVotes queries the "votes" edge of the Schedule entity.
func (_m *Schedule) QueryVotes() *ScheduleVoteQuery {
	return NewScheduleClient(_m.config).QueryVotes(_m)
}

// Update returns a builder for updating this Schedule.
// Note that you need to call Schedule.Unwrap() before calling this method if this Schedule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Schedule) Update() *ScheduleUpdateOne {
	return NewScheduleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Schedule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Schedule) Unwrap() *Schedule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Schedule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Schedule) String() string {
	var builder strings.Builder
	builder.WriteString("Schedule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("shop_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ShopID))
	builder.WriteString(", ")
	builder.WriteString("week_start=")
	builder.WriteString(_m.WeekStart.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("label=")
	builder.WriteString(_m.Label)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("score=")
	builder.WriteString(fmt.Sprintf("%v", _m.Score))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Schedules is a parsable slice of Schedule.
type Schedules []*Schedule
