// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/betallsoph/shiftz/internal/ent/employee"
	"github.com/betallsoph/shiftz/internal/ent/schedule"
	"github.com/betallsoph/shiftz/internal/ent/scheduleassignment"
	"github.com/betallsoph/shiftz/internal/ent/shift"
	"github.com/betallsoph/shiftz/internal/ent/shop"
)

// ScheduleAssignment is the model entity for the ScheduleAssignment schema.
type ScheduleAssignment struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ShopID holds the value of the "shop_id" field.
	ShopID int `json:"shop_id,omitempty"`
	// ScheduleID holds the value of the "schedule_id" field.
	ScheduleID int `json:"schedule_id,omitempty"`
	// ShiftID holds the value of the "shift_id" field.
	ShiftID int `json:"shift_id,omitempty"`
	// EmployeeID holds the value of the "employee_id" field.
	EmployeeID int `json:"employee_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ScheduleAssignmentQuery when eager-loading is set.
	Edges        ScheduleAssignmentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ScheduleAssignmentEdges holds the relations/edges for other nodes in the graph.
type ScheduleAssignmentEdges struct {
	// Shop holds the value of the shop edge.
	Shop *Shop `json:"shop,omitempty"`
	// Schedule holds the value of the schedule edge.
	Schedule *Schedule `json:"schedule,omitempty"`
	// Shift holds the value of the shift edge.
	Shift *Shift `json:"shift,omitempty"`
	// Employee holds the value of the employee edge.
	Employee *Employee `json:"employee,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// ShopOrErr returns the Shop value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ScheduleAssignmentEdges) ShopOrErr() (*Shop, error) {
	if e.Shop != nil {
		return e.Shop, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: shop.Label}
	}
	return nil, &NotLoadedError{edge: "shop"}
}

// ScheduleOrErr returns the Schedule value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ScheduleAssignmentEdges) ScheduleOrErr() (*Schedule, error) {
	if e.Schedule != nil {
		return e.Schedule, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: schedule.Label}
	}
	return nil, &NotLoadedError{edge: "schedule"}
}

// ShiftOrErr returns the Shift value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ScheduleAssignmentEdges) ShiftOrErr() (*Shift, error) {
	if e.Shift != nil {
		return e.Shift, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: shift.Label}
	}
	return nil, &NotLoadedError{edge: "shift"}
}

// EmployeeOrErr returns the Employee value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ScheduleAssignmentEdges) EmployeeOrErr() (*Employee, error) {
	if e.Employee != nil {
		return e.Employee, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: employee.Label}
	}
	return nil, &NotLoadedError{edge: "employee"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ScheduleAssignment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case scheduleassignment.FieldID, scheduleassignment.FieldShopID, scheduleassignment.FieldScheduleID, scheduleassignment.FieldShiftID, scheduleassignment.FieldEmployeeID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ScheduleAssignment fields.
func (_m *ScheduleAssignment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case scheduleassignment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case scheduleassignment.FieldShopID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field shop_id", values[i])
			} else if value.Valid {
				_m.ShopID = int(value.Int64)
			}
		case scheduleassignment.FieldScheduleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field schedule_id", values[i])
			} else if value.Valid {
				_m.ScheduleID = int(value.Int64)
			}
		case scheduleassignment.FieldShiftID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field shift_id", values[i])
			} else if value.Valid {
				_m.ShiftID = int(value.Int64)
			}
		case scheduleassignment.FieldEmployeeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field employee_id", values[i])
			} else if value.Valid {
				_m.EmployeeID = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ScheduleAssignment.
// This includes values selected through modifiers, order, etc.
func (_m *ScheduleAssignment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryShop queries the "shop" edge of the ScheduleAssignment entity.
func (_m *ScheduleAssignment) QueryShop() *ShopQuery {
	return NewScheduleAssignmentClient(_m.config).QueryShop(_m)
}

// QuerySchedule queries the "schedule" edge of the ScheduleAssignment entity.
func (_m *ScheduleAssignment) QuerySchedule() *ScheduleQuery {
	return NewScheduleAssignmentClient(_m.config).QuerySchedule(_m)
}

// QueryShift queries the "shift" edge of the ScheduleAssignment entity.
func (_m *ScheduleAssignment) QueryShift() *ShiftQuery {
	return NewScheduleAssignmentClient(_m.config).QueryShift(_m)
}

// QueryEmployee queries the "employee" edge of the ScheduleAssignment entity.
func (_m *ScheduleAssignment) QueryEmployee() *EmployeeQuery {
	return NewScheduleAssignmentClient(_m.config).QueryEmployee(_m)
}

// Update returns a builder for updating this ScheduleAssignment.
// Note that you need to call ScheduleAssignment.Unwrap() before calling this method if this ScheduleAssignment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ScheduleAssignment) Update() *ScheduleAssignmentUpdateOne {
	return NewScheduleAssignmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ScheduleAssignment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ScheduleAssignment) Unwrap() *ScheduleAssignment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ScheduleAssignment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ScheduleAssignment) String() string {
	var builder strings.Builder
	builder.WriteString("ScheduleAssignment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("shop_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ShopID))
	builder.WriteString(", ")
	builder.WriteString("schedule_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ScheduleID))
	builder.WriteString(", ")
	builder.WriteString("shift_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ShiftID))
	builder.WriteString(", ")
	builder.WriteString("employee_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EmployeeID))
	builder.WriteByte(')')
	return builder.String()
}

// ScheduleAssignments is a parsable slice of ScheduleAssignment.
type ScheduleAssignments []*ScheduleAssignment
