// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/betallsoph/shiftz/internal/ent/availability"
	"github.com/betallsoph/shiftz/internal/ent/employee"
	"github.com/betallsoph/shiftz/internal/ent/rule"
	"github.com/betallsoph/shiftz/internal/ent/schedule"
	"github.com/betallsoph/shiftz/internal/ent/scheduleassignment"
	"github.com/betallsoph/shiftz/internal/ent/schedulevote"
	"github.com/betallsoph/shiftz/internal/ent/shift"
	"github.com/betallsoph/shiftz/internal/ent/shop"
)

// ShopCreate is the builder for creating a Shop entity.
type ShopCreate struct {
	config
	mutation *ShopMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *ShopCreate) SetName(v string) *ShopCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetTimezone sets the "timezone" field.
func (_c *ShopCreate) SetTimezone(v string) *ShopCreate {
	_c.mutation.SetTimezone(v)
	return _c
}

// SetNillableTimezone sets the "timezone" field if the given value is not nil.
func (_c *ShopCreate) SetNillableTimezone(v *string) *ShopCreate {
	if v != nil {
		_c.SetTimezone(*v)
	}
	return _c
}

// SetInviteCode sets the "invite_code" field.
func (_c *ShopCreate) SetInviteCode(v string) *ShopCreate {
	_c.mutation.SetInviteCode(v)
	return _c
}

// SetOwnerTelegramID sets the "owner_telegram_id" field.
func (_c *ShopCreate) SetOwnerTelegramID(v int64) *ShopCreate {
	_c.mutation.SetOwnerTelegramID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ShopCreate) SetCreatedAt(v time.Time) *ShopCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ShopCreate) SetNillableCreatedAt(v *time.Time) *ShopCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// AddEmployeeIDs adds the "employees" edge to the Employee entity by IDs.
func (_c *ShopCreate) AddEmployeeIDs(ids ...int) *ShopCreate {
	_c.mutation.AddEmployeeIDs(ids...)
	return _c
}

// AddEmployees adds the "employees" edges to the Employee entity.
func (_c *ShopCreate) AddEmployees(v ...*Employee) *ShopCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEmployeeIDs(ids...)
}

// AddAvailabilityIDs adds the "availability" edge to the Availability entity by IDs.
func (_c *ShopCreate) AddAvailabilityIDs(ids ...int) *ShopCreate {
	_c.mutation.AddAvailabilityIDs(ids...)
	return _c
}

// AddAvailability adds the "availability" edges to the Availability entity.
func (_c *ShopCreate) AddAvailability(v ...*Availability) *ShopCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAvailabilityIDs(ids...)
}

// AddShiftIDs adds the "shifts" edge to the Shift entity by IDs.
func (_c *ShopCreate) AddShiftIDs(ids ...int) *ShopCreate {
	_c.mutation.AddShiftIDs(ids...)
	return _c
}

// AddShifts adds the "shifts" edges to the Shift entity.
func (_c *ShopCreate) AddShifts(v ...*Shift) *ShopCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddShiftIDs(ids...)
}

// AddScheduleIDs adds the "schedules" edge to the Schedule entity by IDs.
func (_c *ShopCreate) AddScheduleIDs(ids ...int) *ShopCreate {
	_c.mutation.AddScheduleIDs(ids...)
	return _c
}

// AddSchedules adds the "schedules" edges to the Schedule entity.
func (_c *ShopCreate) AddSchedules(v ...*Schedule) *ShopCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddScheduleIDs(ids...)
}

// AddAssignmentIDs adds the "assignments" edge to the ScheduleAssignment entity by IDs.
func (_c *ShopCreate) AddAssignmentIDs(ids ...int) *ShopCreate {
	_c.mutation.AddAssignmentIDs(ids...)
	return _c
}

// AddAssignments adds the "assignments" edges to the ScheduleAssignment entity.
func (_c *ShopCreate) AddAssignments(v ...*ScheduleAssignment) *ShopCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAssignmentIDs(ids...)
}

// AddVoteIDs adds the "votes" edge to the ScheduleVote entity by IDs.
func (_c *ShopCreate) AddVoteIDs(ids ...int) *ShopCreate {
	_c.mutation.AddVoteIDs(ids...)
	return _c
}

// AddVotes adds the "votes" edges to the ScheduleVote entity.
func (_c *ShopCreate) AddVotes(v ...*ScheduleVote) *ShopCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVoteIDs(ids...)
}

// AddRuleIDs adds the "rules" edge to the Rule entity by IDs.
func (_c *ShopCreate) AddRuleIDs(ids ...int) *ShopCreate {
	_c.mutation.AddRuleIDs(ids...)
	return _c
}

// AddRules adds the "rules" edges to the Rule entity.
func (_c *ShopCreate) AddRules(v ...*Rule) *ShopCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRuleIDs(ids...)
}

// Mutation returns the ShopMutation object of the builder.
func (_c *ShopCreate) Mutation() *ShopMutation {
	return _c.mutation
}

// Save creates the Shop in the database.
func (_c *ShopCreate) Save(ctx context.Context) (*Shop, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ShopCreate) SaveX(ctx context.Context) *Shop {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShopCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShopCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ShopCreate) defaults() {
	if _, ok := _c.mutation.Timezone(); !ok {
		v := shop.DefaultTimezone
		_c.mutation.SetTimezone(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := shop.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ShopCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Shop.name"`)}
	}
	if _, ok := _c.mutation.Timezone(); !ok {
		return &ValidationError{Name: "timezone", err: errors.New(`ent: missing required field "Shop.timezone"`)}
	}
	if _, ok := _c.mutation.InviteCode(); !ok {
		return &ValidationError{Name: "invite_code", err: errors.New(`ent: missing required field "Shop.invite_code"`)}
	}
	if _, ok := _c.mutation.OwnerTelegramID(); !ok {
		return &ValidationError{Name: "owner_telegram_id", err: errors.New(`ent: missing required field "Shop.owner_telegram_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Shop.created_at"`)}
	}
	return nil
}

func (_c *ShopCreate) sqlSave(ctx context.Context) (*Shop, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ShopCreate) createSpec() (*Shop, *sqlgraph.CreateSpec) {
	var (
		_node = &Shop{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(shop.Table, sqlgraph.NewFieldSpec(shop.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(shop.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Timezone(); ok {
		_spec.SetField(shop.FieldTimezone, field.TypeString, value)
		_node.Timezone = value
	}
	if value, ok := _c.mutation.InviteCode(); ok {
		_spec.SetField(shop.FieldInviteCode, field.TypeString, value)
		_node.InviteCode = value
	}
	if value, ok := _c.mutation.OwnerTelegramID(); ok {
		_spec.SetField(shop.FieldOwnerTelegramID, field.TypeInt64, value)
		_node.OwnerTelegramID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(shop.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.EmployeesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shop.EmployeesTable,
			Columns: []string{shop.EmployeesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AvailabilityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shop.AvailabilityTable,
			Columns: []string{shop.AvailabilityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(availability.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ShiftsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shop.ShiftsTable,
			Columns: []string{shop.ShiftsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(shift.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SchedulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shop.SchedulesTable,
			Columns: []string{shop.SchedulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(schedule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AssignmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shop.AssignmentsTable,
			Columns: []string{shop.AssignmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(scheduleassignment.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.VotesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shop.VotesTable,
			Columns: []string{shop.VotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(schedulevote.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RulesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   shop.RulesTable,
			Columns: []string{shop.RulesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rule.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Shop.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ShopUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *ShopCreate) OnConflict(opts ...sql.ConflictOption) *ShopUpsertOne {
	_c.conflict = opts
	return &ShopUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Shop.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ShopCreate) OnConflictColumns(columns ...string) *ShopUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ShopUpsertOne{
		create: _c,
	}
}

type (
	// ShopUpsertOne is the builder for "upsert"-ing
	//  one Shop node.
	ShopUpsertOne struct {
		create *ShopCreate
	}

	// ShopUpsert is the "OnConflict" setter.
	ShopUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *ShopUpsert) SetName(v string) *ShopUpsert {
	u.Set(shop.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ShopUpsert) UpdateName() *ShopUpsert {
	u.SetExcluded(shop.FieldName)
	return u
}

// SetTimezone sets the "timezone" field.
func (u *ShopUpsert) SetTimezone(v string) *ShopUpsert {
	u.Set(shop.FieldTimezone, v)
	return u
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *ShopUpsert) UpdateTimezone() *ShopUpsert {
	u.SetExcluded(shop.FieldTimezone)
	return u
}

// SetInviteCode sets the "invite_code" field.
func (u *ShopUpsert) SetInviteCode(v string) *ShopUpsert {
	u.Set(shop.FieldInviteCode, v)
	return u
}

// UpdateInviteCode sets the "invite_code" field to the value that was provided on create.
func (u *ShopUpsert) UpdateInviteCode() *ShopUpsert {
	u.SetExcluded(shop.FieldInviteCode)
	return u
}

// SetOwnerTelegramID sets the "owner_telegram_id" field.
func (u *ShopUpsert) SetOwnerTelegramID(v int64) *ShopUpsert {
	u.Set(shop.FieldOwnerTelegramID, v)
	return u
}

// UpdateOwnerTelegramID sets the "owner_telegram_id" field to the value that was provided on create.
func (u *ShopUpsert) UpdateOwnerTelegramID() *ShopUpsert {
	u.SetExcluded(shop.FieldOwnerTelegramID)
	return u
}

// AddOwnerTelegramID adds v to the "owner_telegram_id" field.
func (u *ShopUpsert) AddOwnerTelegramID(v int64) *ShopUpsert {
	u.Add(shop.FieldOwnerTelegramID, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Shop.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ShopUpsertOne) UpdateNewValues() *ShopUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(shop.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Shop.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ShopUpsertOne) Ignore() *ShopUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ShopUpsertOne) DoNothing() *ShopUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ShopCreate.OnConflict
// documentation for more info.
func (u *ShopUpsertOne) Update(set func(*ShopUpsert)) *ShopUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ShopUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ShopUpsertOne) SetName(v string) *ShopUpsertOne {
	return u.Update(func(s *ShopUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ShopUpsertOne) UpdateName() *ShopUpsertOne {
	return u.Update(func(s *ShopUpsert) {
		s.UpdateName()
	})
}

// SetTimezone sets the "timezone" field.
func (u *ShopUpsertOne) SetTimezone(v string) *ShopUpsertOne {
	return u.Update(func(s *ShopUpsert) {
		s.SetTimezone(v)
	})
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *ShopUpsertOne) UpdateTimezone() *ShopUpsertOne {
	return u.Update(func(s *ShopUpsert) {
		s.UpdateTimezone()
	})
}

// SetInviteCode sets the "invite_code" field.
func (u *ShopUpsertOne) SetInviteCode(v string) *ShopUpsertOne {
	return u.Update(func(s *ShopUpsert) {
		s.SetInviteCode(v)
	})
}

// UpdateInviteCode sets the "invite_code" field to the value that was provided on create.
func (u *ShopUpsertOne) UpdateInviteCode() *ShopUpsertOne {
	return u.Update(func(s *ShopUpsert) {
		s.UpdateInviteCode()
	})
}

// SetOwnerTelegramID sets the "owner_telegram_id" field.
func (u *ShopUpsertOne) SetOwnerTelegramID(v int64) *ShopUpsertOne {
	return u.Update(func(s *ShopUpsert) {
		s.SetOwnerTelegramID(v)
	})
}

// AddOwnerTelegramID adds v to the "owner_telegram_id" field.
func (u *ShopUpsertOne) AddOwnerTelegramID(v int64) *ShopUpsertOne {
	return u.Update(func(s *ShopUpsert) {
		s.AddOwnerTelegramID(v)
	})
}

// UpdateOwnerTelegramID sets the "owner_telegram_id" field to the value that was provided on create.
func (u *ShopUpsertOne) UpdateOwnerTelegramID() *ShopUpsertOne {
	return u.Update(func(s *ShopUpsert) {
		s.UpdateOwnerTelegramID()
	})
}

// Exec executes the query.
func (u *ShopUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ShopCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ShopUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ShopUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ShopUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ShopCreateBulk is the builder for creating many Shop entities in bulk.
type ShopCreateBulk struct {
	config
	err      error
	builders []*ShopCreate
	conflict []sql.ConflictOption
}

// Save creates the Shop entities in the database.
func (_c *ShopCreateBulk) Save(ctx context.Context) ([]*Shop, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Shop, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShopMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ShopCreateBulk) SaveX(ctx context.Context) []*Shop {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShopCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShopCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Shop.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ShopUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *ShopCreateBulk) OnConflict(opts ...sql.ConflictOption) *ShopUpsertBulk {
	_c.conflict = opts
	return &ShopUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Shop.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ShopCreateBulk) OnConflictColumns(columns ...string) *ShopUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ShopUpsertBulk{
		create: _c,
	}
}

// ShopUpsertBulk is the builder for "upsert"-ing
// a bulk of Shop nodes.
type ShopUpsertBulk struct {
	create *ShopCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Shop.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ShopUpsertBulk) UpdateNewValues() *ShopUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(shop.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Shop.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ShopUpsertBulk) Ignore() *ShopUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ShopUpsertBulk) DoNothing() *ShopUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ShopCreateBulk.OnConflict
// documentation for more info.
func (u *ShopUpsertBulk) Update(set func(*ShopUpsert)) *ShopUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ShopUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *ShopUpsertBulk) SetName(v string) *ShopUpsertBulk {
	return u.Update(func(s *ShopUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ShopUpsertBulk) UpdateName() *ShopUpsertBulk {
	return u.Update(func(s *ShopUpsert) {
		s.UpdateName()
	})
}

// SetTimezone sets the "timezone" field.
func (u *ShopUpsertBulk) SetTimezone(v string) *ShopUpsertBulk {
	return u.Update(func(s *ShopUpsert) {
		s.SetTimezone(v)
	})
}

// UpdateTimezone sets the "timezone" field to the value that was provided on create.
func (u *ShopUpsertBulk) UpdateTimezone() *ShopUpsertBulk {
	return u.Update(func(s *ShopUpsert) {
		s.UpdateTimezone()
	})
}

// SetInviteCode sets the "invite_code" field.
func (u *ShopUpsertBulk) SetInviteCode(v string) *ShopUpsertBulk {
	return u.Update(func(s *ShopUpsert) {
		s.SetInviteCode(v)
	})
}

// UpdateInviteCode sets the "invite_code" field to the value that was provided on create.
func (u *ShopUpsertBulk) UpdateInviteCode() *ShopUpsertBulk {
	return u.Update(func(s *ShopUpsert) {
		s.UpdateInviteCode()
	})
}

// SetOwnerTelegramID sets the "owner_telegram_id" field.
func (u *ShopUpsertBulk) SetOwnerTelegramID(v int64) *ShopUpsertBulk {
	return u.Update(func(s *ShopUpsert) {
		s.SetOwnerTelegramID(v)
	})
}

// AddOwnerTelegramID adds v to the "owner_telegram_id" field.
func (u *ShopUpsertBulk) AddOwnerTelegramID(v int64) *ShopUpsertBulk {
	return u.Update(func(s *ShopUpsert) {
		s.AddOwnerTelegramID(v)
	})
}

// UpdateOwnerTelegramID sets the "owner_telegram_id" field to the value that was provided on create.
func (u *ShopUpsertBulk) UpdateOwnerTelegramID() *ShopUpsertBulk {
	return u.Update(func(s *ShopUpsert) {
		s.UpdateOwnerTelegramID()
	})
}

// Exec executes the query.
func (u *ShopUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ShopCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ShopCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ShopUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
