// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/betallsoph/shiftz/internal/ent/shop"
	"github.com/google/uuid"
)

// Shop is the model entity for the Shop schema.
type Shop struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Timezone holds the value of the "timezone" field.
	Timezone string `json:"timezone,omitempty"`
	// InviteCode holds the value of the "invite_code" field.
	InviteCode string `json:"invite_code,omitempty"`
	// TelegramGroupID holds the value of the "telegram_group_id" field.
	TelegramGroupID int64 `json:"telegram_group_id,omitempty"`
	// Plan holds the value of the "plan" field.
	Plan string `json:"plan,omitempty"`
	// DashboardTokenHash holds the value of the "dashboard_token_hash" field.
	DashboardTokenHash *string `json:"dashboard_token_hash,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ShopQuery when eager-loading is set.
	Edges        ShopEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ShopEdges holds the relations/edges for other nodes in the graph.
type ShopEdges struct {
	// Employees holds the value of the employees edge.
	Employees []*Employee `json:"employees,omitempty"`
	// Shifts holds the value of the shifts edge.
	Shifts []*Shift `json:"shifts,omitempty"`
	// Schedules holds the value of the schedules edge.
	Schedules []*Schedule `json:"schedules,omitempty"`
	// Rules holds the value of the rules edge.
	Rules []*Rule `json:"rules,omitempty"`
	// Availabilities holds the value of the availabilities edge.
	Availabilities []*Availability `json:"availabilities,omitempty"`
	// ReminderDeliveries holds the value of the reminder_deliveries edge.
	ReminderDeliveries []*ReminderDelivery `json:"reminder_deliveries,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [6]bool
}

// EmployeesOrErr returns the Employees value or an error if the edge
// was not loaded in eager-loading.
func (e ShopEdges) EmployeesOrErr() ([]*Employee, error) {
	if e.loadedTypes[0] {
		return e.Employees, nil
	}
	return nil, &NotLoadedError{edge: "employees"}
}

// ShiftsOrErr returns the Shifts value or an error if the edge
// was not loaded in eager-loading.
func (e ShopEdges) ShiftsOrErr() ([]*Shift, error) {
	if e.loadedTypes[1] {
		return e.Shifts, nil
	}
	return nil, &NotLoadedError{edge: "shifts"}
}

// SchedulesOrErr returns the Schedules value or an error if the edge
// was not loaded in eager-loading.
func (e ShopEdges) SchedulesOrErr() ([]*Schedule, error) {
	if e.loadedTypes[2] {
		return e.Schedules, nil
	}
	return nil, &NotLoadedError{edge: "schedules"}
}

// RulesOrErr returns the Rules value or an error if the edge
// was not loaded in eager-loading.
func (e ShopEdges) RulesOrErr() ([]*Rule, error) {
	if e.loadedTypes[3] {
		return e.Rules, nil
	}
	return nil, &NotLoadedError{edge: "rules"}
}

// AvailabilitiesOrErr returns the Availabilities value or an error if the edge
// was not loaded in eager-loading.
func (e ShopEdges) AvailabilitiesOrErr() ([]*Availability, error) {
	if e.loadedTypes[4] {
		return e.Availabilities, nil
	}
	return nil, &NotLoadedError{edge: "availabilities"}
}

// ReminderDeliveriesOrErr returns the ReminderDeliveries value or an error if the edge
// was not loaded in eager-loading.
func (e ShopEdges) ReminderDeliveriesOrErr() ([]*ReminderDelivery, error) {
	if e.loadedTypes[5] {
		return e.ReminderDeliveries, nil
	}
	return nil, &NotLoadedError{edge: "reminder_deliveries"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Shop) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case shop.FieldTelegramGroupID:
			values[i] = new(sql.NullInt64)
		case shop.FieldName, shop.FieldTimezone, shop.FieldInviteCode, shop.FieldPlan, shop.FieldDashboardTokenHash:
			values[i] = new(sql.NullString)
		case shop.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case shop.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Shop fields.
func (_m *Shop) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case shop.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case shop.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case shop.FieldTimezone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field timezone", values[i])
			} else if value.Valid {
				_m.Timezone = value.String
			}
		case shop.FieldInviteCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invite_code", values[i])
			} else if value.Valid {
				_m.InviteCode = value.String
			}
		case shop.FieldTelegramGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field telegram_group_id", values[i])
			} else if value.Valid {
				_m.TelegramGroupID = value.Int64
			}
		case shop.FieldPlan:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field plan", values[i])
			} else if value.Valid {
				_m.Plan = value.String
			}
		case shop.FieldDashboardTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field dashboard_token_hash", values[i])
			} else if value.Valid {
				_m.DashboardTokenHash = new(string)
				*_m.DashboardTokenHash = value.String
			}
		case shop.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Shop.
// This includes values selected through modifiers, order, etc.
func (_m *Shop) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEmployees queries the "employees" edge of the Shop entity.
func (_m *Shop) QueryEmployees() *EmployeeQuery {
	return NewShopClient(_m.config).QueryEmployees(_m)
}

// QueryShifts queries the "shifts" edge of the Shop entity.
func (_m *Shop) QueryShifts() *ShiftQuery {
	return NewShopClient(_m.config).QueryShifts(_m)
}

// QuerySchedules queries the "schedules" edge of the Shop entity.
func (_m *Shop) QuerySchedules() *ScheduleQuery {
	return NewShopClient(_m.config).QuerySchedules(_m)
}

// QueryRules queries the "rules" edge of the Shop entity.
func (_m *Shop) QueryRules() *RuleQuery {
	return NewShopClient(_m.config).QueryRules(_m)
}

// QueryAvailabilities queries the "availabilities" edge of the Shop entity.
func (_m *Shop) QueryAvailabilities() *AvailabilityQuery {
	return NewShopClient(_m.config).QueryAvailabilities(_m)
}

// QueryReminderDeliveries queries the "reminder_deliveries" edge of the Shop entity.
func (_m *Shop) QueryReminderDeliveries() *ReminderDeliveryQuery {
	return NewShopClient(_m.config).QueryReminderDeliveries(_m)
}

// Update returns a builder for updating this Shop.
// Note that you need to call Shop.Unwrap() before calling this method if this Shop
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Shop) Update() *ShopUpdateOne {
	return NewShopClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Shop entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Shop) Unwrap() *Shop {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Shop is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Shop) String() string {
	var builder strings.Builder
	builder.WriteString("Shop(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("timezone=")
	builder.WriteString(_m.Timezone)
	builder.WriteString(", ")
	builder.WriteString("invite_code=")
	builder.WriteString(_m.InviteCode)
	builder.WriteString(", ")
	builder.WriteString("telegram_group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TelegramGroupID))
	builder.WriteString(", ")
	builder.WriteString("plan=")
	builder.WriteString(_m.Plan)
	builder.WriteString(", ")
	if v := _m.DashboardTokenHash; v != nil {
		builder.WriteString("dashboard_token_hash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Shops is a parsable slice of Shop.
type Shops []*Shop
