// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/betallsoph/shiftz/internal/ent/shop"
)

// Shop is the model entity for the Shop schema.
type Shop struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Timezone holds the value of the "timezone" field.
	Timezone string `json:"timezone,omitempty"`
	// InviteCode holds the value of the "invite_code" field.
	InviteCode string `json:"invite_code,omitempty"`
	// OwnerTelegramID holds the value of the "owner_telegram_id" field.
	OwnerTelegramID int64 `json:"owner_telegram_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ShopQuery when eager-loading is set.
	Edges        ShopEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ShopEdges holds the relations/edges for other nodes in the graph.
type ShopEdges struct {
	// Employees holds the value of the employees edge.
	Employees []*Employee `json:"employees,omitempty"`
	// Availability holds the value of the availability edge.
	Availability []*Availability `json:"availability,omitempty"`
	// Shifts holds the value of the shifts edge.
	Shifts []*Shift `json:"shifts,omitempty"`
	// Schedules holds the value of the schedules edge.
	Schedules []*Schedule `json:"schedules,omitempty"`
	// Assignments holds the value of the assignments edge.
	Assignments []*ScheduleAssignment `json:"assignments,omitempty"`
	// Votes holds the value of the votes edge.
	Votes []*ScheduleVote `json:"votes,omitempty"`
	// Rules holds the value of the rules edge.
	Rules []*Rule `json:"rules,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [7]bool
}

// EmployeesOrErr returns the Employees value or an error if the edge
// was not loaded in eager-loading.
func (e ShopEdges) EmployeesOrErr() ([]*Employee, error) {
	if e.loadedTypes[0] {
		return e.Employees, nil
	}
	return nil, &NotLoadedError{edge: "employees"}
}

// AvailabilityOrErr returns the Availability value or an error if the edge
// was not loaded in eager-loading.
func (e ShopEdges) AvailabilityOrErr() ([]*Availability, error) {
	if e.loadedTypes[1] {
		return e.Availability, nil
	}
	return nil, &NotLoadedError{edge: "availability"}
}

// ShiftsOrErr returns the Shifts value or an error if the edge
// was not loaded in eager-loading.
func (e ShopEdges) ShiftsOrErr() ([]*Shift, error) {
	if e.loadedTypes[2] {
		return e.Shifts, nil
	}
	return nil, &NotLoadedError{edge: "shifts"}
}

// SchedulesOrErr returns the Schedules value or an error if the edge
// was not loaded in eager-loading.
func (e ShopEdges) SchedulesOrErr() ([]*Schedule, error) {
	if e.loadedTypes[3] {
		return e.Schedules, nil
	}
	return nil, &NotLoadedError{edge: "schedules"}
}

// AssignmentsOrErr returns the Assignments value or an error if the edge
// was not loaded in eager-loading.
func (e ShopEdges) AssignmentsOrErr() ([]*ScheduleAssignment, error) {
	if e.loadedTypes[4] {
		return e.Assignments, nil
	}
	return nil, &NotLoadedError{edge: "assignments"}
}

// VotesOrErr returns the Votes value or an error if the edge
// was not loaded in eager-loading.
func (e ShopEdges) VotesOrErr() ([]*ScheduleVote, error) {
	if e.loadedTypes[5] {
		return e.Votes, nil
	}
	return nil, &NotLoadedError{edge: "votes"}
}

// RulesOrErr returns the Rules value or an error if the edge
// was not loaded in eager-loading.
func (e ShopEdges) RulesOrErr() ([]*Rule, error) {
	if e.loadedTypes[6] {
		return e.Rules, nil
	}
	return nil, &NotLoadedError{edge: "rules"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Shop) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case shop.FieldID, shop.FieldOwnerTelegramID:
			values[i] = new(sql.NullInt64)
		case shop.FieldName, shop.FieldTimezone, shop.FieldInviteCode:
			values[i] = new(sql.NullString)
		case shop.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Shop fields.
func (_m *Shop) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case shop.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case shop.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case shop.FieldTimezone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field timezone", values[i])
			} else if value.Valid {
				_m.Timezone = value.String
			}
		case shop.FieldInviteCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field invite_code", values[i])
			} else if value.Valid {
				_m.InviteCode = value.String
			}
		case shop.FieldOwnerTelegramID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field owner_telegram_id", values[i])
			} else if value.Valid {
				_m.OwnerTelegramID = value.Int64
			}
		case shop.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Shop.
// This includes values selected through modifiers, order, etc.
func (_m *Shop) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEmployees queries the "employees" edge of the Shop entity.
func (_m *Shop) QueryEmployees() *EmployeeQuery {
	return NewShopClient(_m.config).QueryEmployees(_m)
}

// QueryAvailability queries the "availability" edge of the Shop entity.
func (_m *Shop) QueryAvailability() *AvailabilityQuery {
	return NewShopClient(_m.config).QueryAvailability(_m)
}

// QueryShifts queries the "shifts" edge of the Shop entity.
func (_m *Shop) QueryShifts() *ShiftQuery {
	return NewShopClient(_m.config).QueryShifts(_m)
}

// QuerySchedules queries the "schedules" edge of the Shop entity.
func (_m *Shop) QuerySchedules() *ScheduleQuery {
	return NewShopClient(_m.config).QuerySchedules(_m)
}

// QueryAssignments queries the "assignments" edge of the Shop entity.
func (_m *Shop) QueryAssignments() *ScheduleAssignmentQuery {
	return NewShopClient(_m.config).QueryAssignments(_m)
}

// QueryVotes queries the "votes" edge of the Shop entity.
func (_m *Shop) QueryVotes() *ScheduleVoteQuery {
	return NewShopClient(_m.config).QueryVotes(_m)
}

// QueryRules queries the "rules" edge of the Shop entity.
func (_m *Shop) QueryRules() *RuleQuery {
	return NewShopClient(_m.config).QueryRules(_m)
}

// Update returns a builder for updating this Shop.
// Note that you need to call Shop.Unwrap() before calling this method if this Shop
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Shop) Update() *ShopUpdateOne {
	return NewShopClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Shop entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Shop) Unwrap() *Shop {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Shop is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Shop) String() string {
	var builder strings.Builder
	builder.WriteString("Shop(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("timezone=")
	builder.WriteString(_m.Timezone)
	builder.WriteString(", ")
	builder.WriteString("invite_code=")
	builder.WriteString(_m.InviteCode)
	builder.WriteString(", ")
	builder.WriteString("owner_telegram_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerTelegramID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Shops is a parsable slice of Shop.
type Shops []*Shop
