-- 0001_init.sql — shiftbot core schema.
-- Every tenant-owned table carries shop_id; all queries scope by it.
-- Apply with: psql "$DATABASE_URL" -f migrations/0001_init.sql

BEGIN;

CREATE TABLE shops (
    id                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name              TEXT        NOT NULL,
    timezone          TEXT        NOT NULL DEFAULT 'UTC',
    invite_code       TEXT        NOT NULL UNIQUE,
    owner_telegram_id BIGINT      NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE employees (
    id                 BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    shop_id            BIGINT      NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    telegram_user_id   BIGINT      NOT NULL,
    display_name       TEXT        NOT NULL,
    max_hours_per_week REAL        NOT NULL DEFAULT 40,
    active             BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (shop_id, telegram_user_id)
);
CREATE INDEX employees_shop_id_idx ON employees (shop_id);
CREATE INDEX employees_telegram_user_id_idx ON employees (telegram_user_id);

-- Structured availability parsed from employees' free-text messages.
CREATE TABLE availability (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    shop_id     BIGINT      NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    employee_id BIGINT      NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    week_start  DATE        NOT NULL,
    starts_at   TIMESTAMPTZ NOT NULL,
    ends_at     TIMESTAMPTZ NOT NULL,
    -- 0 = unavailable, 1 = available, 2 = preferred (solver scale)
    preference  SMALLINT    NOT NULL DEFAULT 1,
    note        TEXT        NOT NULL DEFAULT '',
    raw_text    TEXT        NOT NULL DEFAULT '',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (ends_at > starts_at)
);
CREATE INDEX availability_shop_week_idx ON availability (shop_id, week_start);
CREATE INDEX availability_employee_week_idx ON availability (employee_id, week_start);

-- Shifts that need staffing (shift templates/instances per week).
CREATE TABLE shifts (
    id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    shop_id    BIGINT      NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    role       TEXT        NOT NULL DEFAULT '',
    starts_at  TIMESTAMPTZ NOT NULL,
    ends_at    TIMESTAMPTZ NOT NULL,
    min_staff  INT         NOT NULL DEFAULT 1,
    max_staff  INT         NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (ends_at > starts_at),
    CHECK (min_staff >= 0 AND max_staff >= min_staff)
);
CREATE INDEX shifts_shop_starts_at_idx ON shifts (shop_id, starts_at);

-- Schedule candidates generated by the solver; status tracks the voting flow.
CREATE TABLE schedules (
    id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    shop_id    BIGINT      NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    week_start DATE        NOT NULL,
    label      TEXT        NOT NULL DEFAULT '',       -- e.g. "balanced", "fairness-first"
    status     TEXT        NOT NULL DEFAULT 'draft',  -- draft | voting | final | vetoed
    score      DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (status IN ('draft', 'voting', 'final', 'vetoed'))
);
CREATE INDEX schedules_shop_week_idx ON schedules (shop_id, week_start);

-- Assignments of one schedule candidate.
CREATE TABLE schedule_assignments (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    shop_id     BIGINT NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    schedule_id BIGINT NOT NULL REFERENCES schedules(id) ON DELETE CASCADE,
    shift_id    BIGINT NOT NULL REFERENCES shifts(id) ON DELETE CASCADE,
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    UNIQUE (schedule_id, shift_id, employee_id)
);
CREATE INDEX schedule_assignments_schedule_idx ON schedule_assignments (schedule_id);

-- One vote per employee per schedule candidate.
CREATE TABLE schedule_votes (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    shop_id     BIGINT      NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    schedule_id BIGINT      NOT NULL REFERENCES schedules(id) ON DELETE CASCADE,
    employee_id BIGINT      NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (schedule_id, employee_id)
);
CREATE INDEX schedule_votes_shop_idx ON schedule_votes (shop_id);

-- Owner rules translated from natural language into solver penalty specs.
CREATE TABLE rules (
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    shop_id     BIGINT      NOT NULL REFERENCES shops(id) ON DELETE CASCADE,
    kind        TEXT        NOT NULL,               -- avoid_pair | day_off | custom
    params      JSONB       NOT NULL DEFAULT '{}',
    weight      REAL        NOT NULL DEFAULT 1,
    source_text TEXT        NOT NULL DEFAULT '',    -- the owner's original wording
    active      BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX rules_shop_idx ON rules (shop_id) WHERE active;

COMMIT;
