// Code generated by ent, DO NOT EDIT.

package shift

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/betallsoph/shiftz/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Shift {
	return predicate.Shift(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Shift {
	return predicate.Shift(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Shift {
	return predicate.Shift(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Shift {
	return predicate.Shift(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Shift {
	return predicate.Shift(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Shift {
	return predicate.Shift(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Shift {
	return predicate.Shift(sql.FieldLTE(FieldID, id))
}

// ShopID applies equality check predicate on the "shop_id" field. It's identical to ShopIDEQ.
func ShopID(v uuid.UUID) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldShopID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldName, v))
}

// Weekday applies equality check predicate on the "weekday" field. It's identical to WeekdayEQ.
func Weekday(v int) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldWeekday, v))
}

// StartTime applies equality check predicate on the "start_time" field. It's identical to StartTimeEQ.
func StartTime(v string) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldStartTime, v))
}

// EndTime applies equality check predicate on the "end_time" field. It's identical to EndTimeEQ.
func EndTime(v string) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldEndTime, v))
}

// MinStaff applies equality check predicate on the "min_staff" field. It's identical to MinStaffEQ.
func MinStaff(v int) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldMinStaff, v))
}

// MaxStaff applies equality check predicate on the "max_staff" field. It's identical to MaxStaffEQ.
func MaxStaff(v int) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldMaxStaff, v))
}

// ShopIDEQ applies the EQ predicate on the "shop_id" field.
func ShopIDEQ(v uuid.UUID) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldShopID, v))
}

// ShopIDNEQ applies the NEQ predicate on the "shop_id" field.
func ShopIDNEQ(v uuid.UUID) predicate.Shift {
	return predicate.Shift(sql.FieldNEQ(FieldShopID, v))
}

// ShopIDIn applies the In predicate on the "shop_id" field.
func ShopIDIn(vs ...uuid.UUID) predicate.Shift {
	return predicate.Shift(sql.FieldIn(FieldShopID, vs...))
}

// ShopIDNotIn applies the NotIn predicate on the "shop_id" field.
func ShopIDNotIn(vs ...uuid.UUID) predicate.Shift {
	return predicate.Shift(sql.FieldNotIn(FieldShopID, vs...))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Shift {
	return predicate.Shift(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Shift {
	return predicate.Shift(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Shift {
	return predicate.Shift(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Shift {
	return predicate.Shift(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Shift {
	return predicate.Shift(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Shift {
	return predicate.Shift(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Shift {
	return predicate.Shift(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Shift {
	return predicate.Shift(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Shift {
	return predicate.Shift(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Shift {
	return predicate.Shift(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Shift {
	return predicate.Shift(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Shift {
	return predicate.Shift(sql.FieldContainsFold(FieldName, v))
}

// WeekdayEQ applies the EQ predicate on the "weekday" field.
func WeekdayEQ(v int) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldWeekday, v))
}

// WeekdayNEQ applies the NEQ predicate on the "weekday" field.
func WeekdayNEQ(v int) predicate.Shift {
	return predicate.Shift(sql.FieldNEQ(FieldWeekday, v))
}

// WeekdayIn applies the In predicate on the "weekday" field.
func WeekdayIn(vs ...int) predicate.Shift {
	return predicate.Shift(sql.FieldIn(FieldWeekday, vs...))
}

// WeekdayNotIn applies the NotIn predicate on the "weekday" field.
func WeekdayNotIn(vs ...int) predicate.Shift {
	return predicate.Shift(sql.FieldNotIn(FieldWeekday, vs...))
}

// WeekdayGT applies the GT predicate on the "weekday" field.
func WeekdayGT(v int) predicate.Shift {
	return predicate.Shift(sql.FieldGT(FieldWeekday, v))
}

// WeekdayGTE applies the GTE predicate on the "weekday" field.
func WeekdayGTE(v int) predicate.Shift {
	return predicate.Shift(sql.FieldGTE(FieldWeekday, v))
}

// WeekdayLT applies the LT predicate on the "weekday" field.
func WeekdayLT(v int) predicate.Shift {
	return predicate.Shift(sql.FieldLT(FieldWeekday, v))
}

// WeekdayLTE applies the LTE predicate on the "weekday" field.
func WeekdayLTE(v int) predicate.Shift {
	return predicate.Shift(sql.FieldLTE(FieldWeekday, v))
}

// StartTimeEQ applies the EQ predicate on the "start_time" field.
func StartTimeEQ(v string) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldStartTime, v))
}

// StartTimeNEQ applies the NEQ predicate on the "start_time" field.
func StartTimeNEQ(v string) predicate.Shift {
	return predicate.Shift(sql.FieldNEQ(FieldStartTime, v))
}

// StartTimeIn applies the In predicate on the "start_time" field.
func StartTimeIn(vs ...string) predicate.Shift {
	return predicate.Shift(sql.FieldIn(FieldStartTime, vs...))
}

// StartTimeNotIn applies the NotIn predicate on the "start_time" field.
func StartTimeNotIn(vs ...string) predicate.Shift {
	return predicate.Shift(sql.FieldNotIn(FieldStartTime, vs...))
}

// StartTimeGT applies the GT predicate on the "start_time" field.
func StartTimeGT(v string) predicate.Shift {
	return predicate.Shift(sql.FieldGT(FieldStartTime, v))
}

// StartTimeGTE applies the GTE predicate on the "start_time" field.
func StartTimeGTE(v string) predicate.Shift {
	return predicate.Shift(sql.FieldGTE(FieldStartTime, v))
}

// StartTimeLT applies the LT predicate on the "start_time" field.
func StartTimeLT(v string) predicate.Shift {
	return predicate.Shift(sql.FieldLT(FieldStartTime, v))
}

// StartTimeLTE applies the LTE predicate on the "start_time" field.
func StartTimeLTE(v string) predicate.Shift {
	return predicate.Shift(sql.FieldLTE(FieldStartTime, v))
}

// StartTimeContains applies the Contains predicate on the "start_time" field.
func StartTimeContains(v string) predicate.Shift {
	return predicate.Shift(sql.FieldContains(FieldStartTime, v))
}

// StartTimeHasPrefix applies the HasPrefix predicate on the "start_time" field.
func StartTimeHasPrefix(v string) predicate.Shift {
	return predicate.Shift(sql.FieldHasPrefix(FieldStartTime, v))
}

// StartTimeHasSuffix applies the HasSuffix predicate on the "start_time" field.
func StartTimeHasSuffix(v string) predicate.Shift {
	return predicate.Shift(sql.FieldHasSuffix(FieldStartTime, v))
}

// StartTimeEqualFold applies the EqualFold predicate on the "start_time" field.
func StartTimeEqualFold(v string) predicate.Shift {
	return predicate.Shift(sql.FieldEqualFold(FieldStartTime, v))
}

// StartTimeContainsFold applies the ContainsFold predicate on the "start_time" field.
func StartTimeContainsFold(v string) predicate.Shift {
	return predicate.Shift(sql.FieldContainsFold(FieldStartTime, v))
}

// EndTimeEQ applies the EQ predicate on the "end_time" field.
func EndTimeEQ(v string) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldEndTime, v))
}

// EndTimeNEQ applies the NEQ predicate on the "end_time" field.
func EndTimeNEQ(v string) predicate.Shift {
	return predicate.Shift(sql.FieldNEQ(FieldEndTime, v))
}

// EndTimeIn applies the In predicate on the "end_time" field.
func EndTimeIn(vs ...string) predicate.Shift {
	return predicate.Shift(sql.FieldIn(FieldEndTime, vs...))
}

// EndTimeNotIn applies the NotIn predicate on the "end_time" field.
func EndTimeNotIn(vs ...string) predicate.Shift {
	return predicate.Shift(sql.FieldNotIn(FieldEndTime, vs...))
}

// EndTimeGT applies the GT predicate on the "end_time" field.
func EndTimeGT(v string) predicate.Shift {
	return predicate.Shift(sql.FieldGT(FieldEndTime, v))
}

// EndTimeGTE applies the GTE predicate on the "end_time" field.
func EndTimeGTE(v string) predicate.Shift {
	return predicate.Shift(sql.FieldGTE(FieldEndTime, v))
}

// EndTimeLT applies the LT predicate on the "end_time" field.
func EndTimeLT(v string) predicate.Shift {
	return predicate.Shift(sql.FieldLT(FieldEndTime, v))
}

// EndTimeLTE applies the LTE predicate on the "end_time" field.
func EndTimeLTE(v string) predicate.Shift {
	return predicate.Shift(sql.FieldLTE(FieldEndTime, v))
}

// EndTimeContains applies the Contains predicate on the "end_time" field.
func EndTimeContains(v string) predicate.Shift {
	return predicate.Shift(sql.FieldContains(FieldEndTime, v))
}

// EndTimeHasPrefix applies the HasPrefix predicate on the "end_time" field.
func EndTimeHasPrefix(v string) predicate.Shift {
	return predicate.Shift(sql.FieldHasPrefix(FieldEndTime, v))
}

// EndTimeHasSuffix applies the HasSuffix predicate on the "end_time" field.
func EndTimeHasSuffix(v string) predicate.Shift {
	return predicate.Shift(sql.FieldHasSuffix(FieldEndTime, v))
}

// EndTimeEqualFold applies the EqualFold predicate on the "end_time" field.
func EndTimeEqualFold(v string) predicate.Shift {
	return predicate.Shift(sql.FieldEqualFold(FieldEndTime, v))
}

// EndTimeContainsFold applies the ContainsFold predicate on the "end_time" field.
func EndTimeContainsFold(v string) predicate.Shift {
	return predicate.Shift(sql.FieldContainsFold(FieldEndTime, v))
}

// MinStaffEQ applies the EQ predicate on the "min_staff" field.
func MinStaffEQ(v int) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldMinStaff, v))
}

// MinStaffNEQ applies the NEQ predicate on the "min_staff" field.
func MinStaffNEQ(v int) predicate.Shift {
	return predicate.Shift(sql.FieldNEQ(FieldMinStaff, v))
}

// MinStaffIn applies the In predicate on the "min_staff" field.
func MinStaffIn(vs ...int) predicate.Shift {
	return predicate.Shift(sql.FieldIn(FieldMinStaff, vs...))
}

// MinStaffNotIn applies the NotIn predicate on the "min_staff" field.
func MinStaffNotIn(vs ...int) predicate.Shift {
	return predicate.Shift(sql.FieldNotIn(FieldMinStaff, vs...))
}

// MinStaffGT applies the GT predicate on the "min_staff" field.
func MinStaffGT(v int) predicate.Shift {
	return predicate.Shift(sql.FieldGT(FieldMinStaff, v))
}

// MinStaffGTE applies the GTE predicate on the "min_staff" field.
func MinStaffGTE(v int) predicate.Shift {
	return predicate.Shift(sql.FieldGTE(FieldMinStaff, v))
}

// MinStaffLT applies the LT predicate on the "min_staff" field.
func MinStaffLT(v int) predicate.Shift {
	return predicate.Shift(sql.FieldLT(FieldMinStaff, v))
}

// MinStaffLTE applies the LTE predicate on the "min_staff" field.
func MinStaffLTE(v int) predicate.Shift {
	return predicate.Shift(sql.FieldLTE(FieldMinStaff, v))
}

// MaxStaffEQ applies the EQ predicate on the "max_staff" field.
func MaxStaffEQ(v int) predicate.Shift {
	return predicate.Shift(sql.FieldEQ(FieldMaxStaff, v))
}

// MaxStaffNEQ applies the NEQ predicate on the "max_staff" field.
func MaxStaffNEQ(v int) predicate.Shift {
	return predicate.Shift(sql.FieldNEQ(FieldMaxStaff, v))
}

// MaxStaffIn applies the In predicate on the "max_staff" field.
func MaxStaffIn(vs ...int) predicate.Shift {
	return predicate.Shift(sql.FieldIn(FieldMaxStaff, vs...))
}

// MaxStaffNotIn applies the NotIn predicate on the "max_staff" field.
func MaxStaffNotIn(vs ...int) predicate.Shift {
	return predicate.Shift(sql.FieldNotIn(FieldMaxStaff, vs...))
}

// MaxStaffGT applies the GT predicate on the "max_staff" field.
func MaxStaffGT(v int) predicate.Shift {
	return predicate.Shift(sql.FieldGT(FieldMaxStaff, v))
}

// MaxStaffGTE applies the GTE predicate on the "max_staff" field.
func MaxStaffGTE(v int) predicate.Shift {
	return predicate.Shift(sql.FieldGTE(FieldMaxStaff, v))
}

// MaxStaffLT applies the LT predicate on the "max_staff" field.
func MaxStaffLT(v int) predicate.Shift {
	return predicate.Shift(sql.FieldLT(FieldMaxStaff, v))
}

// MaxStaffLTE applies the LTE predicate on the "max_staff" field.
func MaxStaffLTE(v int) predicate.Shift {
	return predicate.Shift(sql.FieldLTE(FieldMaxStaff, v))
}

// HasShop applies the HasEdge predicate on the "shop" edge.
func HasShop() predicate.Shift {
	return predicate.Shift(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ShopTable, ShopColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasShopWith applies the HasEdge predicate on the "shop" edge with a given conditions (other predicates).
func HasShopWith(preds ...predicate.Shop) predicate.Shift {
	return predicate.Shift(func(s *sql.Selector) {
		step := newShopStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAssignments applies the HasEdge predicate on the "assignments" edge.
func HasAssignments() predicate.Shift {
	return predicate.Shift(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AssignmentsTable, AssignmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssignmentsWith applies the HasEdge predicate on the "assignments" edge with a given conditions (other predicates).
func HasAssignmentsWith(preds ...predicate.ScheduleAssignment) predicate.Shift {
	return predicate.Shift(func(s *sql.Selector) {
		step := newAssignmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Shift) predicate.Shift {
	return predicate.Shift(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Shift) predicate.Shift {
	return predicate.Shift(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Shift) predicate.Shift {
	return predicate.Shift(sql.NotPredicates(p))
}
