// Code generated by ent, DO NOT EDIT.

package availability

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/betallsoph/shiftz/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Availability {
	return predicate.Availability(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Availability {
	return predicate.Availability(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Availability {
	return predicate.Availability(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Availability {
	return predicate.Availability(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Availability {
	return predicate.Availability(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Availability {
	return predicate.Availability(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Availability {
	return predicate.Availability(sql.FieldLTE(FieldID, id))
}

// ShopID applies equality check predicate on the "shop_id" field. It's identical to ShopIDEQ.
func ShopID(v int) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldShopID, v))
}

// EmployeeID applies equality check predicate on the "employee_id" field. It's identical to EmployeeIDEQ.
func EmployeeID(v int) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldEmployeeID, v))
}

// WeekStart applies equality check predicate on the "week_start" field. It's identical to WeekStartEQ.
func WeekStart(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldWeekStart, v))
}

// StartsAt applies equality check predicate on the "starts_at" field. It's identical to StartsAtEQ.
func StartsAt(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldStartsAt, v))
}

// EndsAt applies equality check predicate on the "ends_at" field. It's identical to EndsAtEQ.
func EndsAt(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldEndsAt, v))
}

// Preference applies equality check predicate on the "preference" field. It's identical to PreferenceEQ.
func Preference(v int) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldPreference, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldNote, v))
}

// RawText applies equality check predicate on the "raw_text" field. It's identical to RawTextEQ.
func RawText(v string) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldRawText, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldCreatedAt, v))
}

// ShopIDEQ applies the EQ predicate on the "shop_id" field.
func ShopIDEQ(v int) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldShopID, v))
}

// ShopIDNEQ applies the NEQ predicate on the "shop_id" field.
func ShopIDNEQ(v int) predicate.Availability {
	return predicate.Availability(sql.FieldNEQ(FieldShopID, v))
}

// ShopIDIn applies the In predicate on the "shop_id" field.
func ShopIDIn(vs ...int) predicate.Availability {
	return predicate.Availability(sql.FieldIn(FieldShopID, vs...))
}

// ShopIDNotIn applies the NotIn predicate on the "shop_id" field.
func ShopIDNotIn(vs ...int) predicate.Availability {
	return predicate.Availability(sql.FieldNotIn(FieldShopID, vs...))
}

// EmployeeIDEQ applies the EQ predicate on the "employee_id" field.
func EmployeeIDEQ(v int) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldEmployeeID, v))
}

// EmployeeIDNEQ applies the NEQ predicate on the "employee_id" field.
func EmployeeIDNEQ(v int) predicate.Availability {
	return predicate.Availability(sql.FieldNEQ(FieldEmployeeID, v))
}

// EmployeeIDIn applies the In predicate on the "employee_id" field.
func EmployeeIDIn(vs ...int) predicate.Availability {
	return predicate.Availability(sql.FieldIn(FieldEmployeeID, vs...))
}

// EmployeeIDNotIn applies the NotIn predicate on the "employee_id" field.
func EmployeeIDNotIn(vs ...int) predicate.Availability {
	return predicate.Availability(sql.FieldNotIn(FieldEmployeeID, vs...))
}

// WeekStartEQ applies the EQ predicate on the "week_start" field.
func WeekStartEQ(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldWeekStart, v))
}

// WeekStartNEQ applies the NEQ predicate on the "week_start" field.
func WeekStartNEQ(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldNEQ(FieldWeekStart, v))
}

// WeekStartIn applies the In predicate on the "week_start" field.
func WeekStartIn(vs ...time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldIn(FieldWeekStart, vs...))
}

// WeekStartNotIn applies the NotIn predicate on the "week_start" field.
func WeekStartNotIn(vs ...time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldNotIn(FieldWeekStart, vs...))
}

// WeekStartGT applies the GT predicate on the "week_start" field.
func WeekStartGT(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldGT(FieldWeekStart, v))
}

// WeekStartGTE applies the GTE predicate on the "week_start" field.
func WeekStartGTE(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldGTE(FieldWeekStart, v))
}

// WeekStartLT applies the LT predicate on the "week_start" field.
func WeekStartLT(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldLT(FieldWeekStart, v))
}

// WeekStartLTE applies the LTE predicate on the "week_start" field.
func WeekStartLTE(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldLTE(FieldWeekStart, v))
}

// StartsAtEQ applies the EQ predicate on the "starts_at" field.
func StartsAtEQ(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldStartsAt, v))
}

// StartsAtNEQ applies the NEQ predicate on the "starts_at" field.
func StartsAtNEQ(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldNEQ(FieldStartsAt, v))
}

// StartsAtIn applies the In predicate on the "starts_at" field.
func StartsAtIn(vs ...time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldIn(FieldStartsAt, vs...))
}

// StartsAtNotIn applies the NotIn predicate on the "starts_at" field.
func StartsAtNotIn(vs ...time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldNotIn(FieldStartsAt, vs...))
}

// StartsAtGT applies the GT predicate on the "starts_at" field.
func StartsAtGT(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldGT(FieldStartsAt, v))
}

// StartsAtGTE applies the GTE predicate on the "starts_at" field.
func StartsAtGTE(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldGTE(FieldStartsAt, v))
}

// StartsAtLT applies the LT predicate on the "starts_at" field.
func StartsAtLT(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldLT(FieldStartsAt, v))
}

// StartsAtLTE applies the LTE predicate on the "starts_at" field.
func StartsAtLTE(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldLTE(FieldStartsAt, v))
}

// EndsAtEQ applies the EQ predicate on the "ends_at" field.
func EndsAtEQ(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldEndsAt, v))
}

// EndsAtNEQ applies the NEQ predicate on the "ends_at" field.
func EndsAtNEQ(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldNEQ(FieldEndsAt, v))
}

// EndsAtIn applies the In predicate on the "ends_at" field.
func EndsAtIn(vs ...time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldIn(FieldEndsAt, vs...))
}

// EndsAtNotIn applies the NotIn predicate on the "ends_at" field.
func EndsAtNotIn(vs ...time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldNotIn(FieldEndsAt, vs...))
}

// EndsAtGT applies the GT predicate on the "ends_at" field.
func EndsAtGT(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldGT(FieldEndsAt, v))
}

// EndsAtGTE applies the GTE predicate on the "ends_at" field.
func EndsAtGTE(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldGTE(FieldEndsAt, v))
}

// EndsAtLT applies the LT predicate on the "ends_at" field.
func EndsAtLT(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldLT(FieldEndsAt, v))
}

// EndsAtLTE applies the LTE predicate on the "ends_at" field.
func EndsAtLTE(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldLTE(FieldEndsAt, v))
}

// PreferenceEQ applies the EQ predicate on the "preference" field.
func PreferenceEQ(v int) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldPreference, v))
}

// PreferenceNEQ applies the NEQ predicate on the "preference" field.
func PreferenceNEQ(v int) predicate.Availability {
	return predicate.Availability(sql.FieldNEQ(FieldPreference, v))
}

// PreferenceIn applies the In predicate on the "preference" field.
func PreferenceIn(vs ...int) predicate.Availability {
	return predicate.Availability(sql.FieldIn(FieldPreference, vs...))
}

// PreferenceNotIn applies the NotIn predicate on the "preference" field.
func PreferenceNotIn(vs ...int) predicate.Availability {
	return predicate.Availability(sql.FieldNotIn(FieldPreference, vs...))
}

// PreferenceGT applies the GT predicate on the "preference" field.
func PreferenceGT(v int) predicate.Availability {
	return predicate.Availability(sql.FieldGT(FieldPreference, v))
}

// PreferenceGTE applies the GTE predicate on the "preference" field.
func PreferenceGTE(v int) predicate.Availability {
	return predicate.Availability(sql.FieldGTE(FieldPreference, v))
}

// PreferenceLT applies the LT predicate on the "preference" field.
func PreferenceLT(v int) predicate.Availability {
	return predicate.Availability(sql.FieldLT(FieldPreference, v))
}

// PreferenceLTE applies the LTE predicate on the "preference" field.
func PreferenceLTE(v int) predicate.Availability {
	return predicate.Availability(sql.FieldLTE(FieldPreference, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.Availability {
	return predicate.Availability(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.Availability {
	return predicate.Availability(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.Availability {
	return predicate.Availability(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.Availability {
	return predicate.Availability(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.Availability {
	return predicate.Availability(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.Availability {
	return predicate.Availability(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.Availability {
	return predicate.Availability(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.Availability {
	return predicate.Availability(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.Availability {
	return predicate.Availability(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.Availability {
	return predicate.Availability(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.Availability {
	return predicate.Availability(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.Availability {
	return predicate.Availability(sql.FieldContainsFold(FieldNote, v))
}

// RawTextEQ applies the EQ predicate on the "raw_text" field.
func RawTextEQ(v string) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldRawText, v))
}

// RawTextNEQ applies the NEQ predicate on the "raw_text" field.
func RawTextNEQ(v string) predicate.Availability {
	return predicate.Availability(sql.FieldNEQ(FieldRawText, v))
}

// RawTextIn applies the In predicate on the "raw_text" field.
func RawTextIn(vs ...string) predicate.Availability {
	return predicate.Availability(sql.FieldIn(FieldRawText, vs...))
}

// RawTextNotIn applies the NotIn predicate on the "raw_text" field.
func RawTextNotIn(vs ...string) predicate.Availability {
	return predicate.Availability(sql.FieldNotIn(FieldRawText, vs...))
}

// RawTextGT applies the GT predicate on the "raw_text" field.
func RawTextGT(v string) predicate.Availability {
	return predicate.Availability(sql.FieldGT(FieldRawText, v))
}

// RawTextGTE applies the GTE predicate on the "raw_text" field.
func RawTextGTE(v string) predicate.Availability {
	return predicate.Availability(sql.FieldGTE(FieldRawText, v))
}

// RawTextLT applies the LT predicate on the "raw_text" field.
func RawTextLT(v string) predicate.Availability {
	return predicate.Availability(sql.FieldLT(FieldRawText, v))
}

// RawTextLTE applies the LTE predicate on the "raw_text" field.
func RawTextLTE(v string) predicate.Availability {
	return predicate.Availability(sql.FieldLTE(FieldRawText, v))
}

// RawTextContains applies the Contains predicate on the "raw_text" field.
func RawTextContains(v string) predicate.Availability {
	return predicate.Availability(sql.FieldContains(FieldRawText, v))
}

// RawTextHasPrefix applies the HasPrefix predicate on the "raw_text" field.
func RawTextHasPrefix(v string) predicate.Availability {
	return predicate.Availability(sql.FieldHasPrefix(FieldRawText, v))
}

// RawTextHasSuffix applies the HasSuffix predicate on the "raw_text" field.
func RawTextHasSuffix(v string) predicate.Availability {
	return predicate.Availability(sql.FieldHasSuffix(FieldRawText, v))
}

// RawTextEqualFold applies the EqualFold predicate on the "raw_text" field.
func RawTextEqualFold(v string) predicate.Availability {
	return predicate.Availability(sql.FieldEqualFold(FieldRawText, v))
}

// RawTextContainsFold applies the ContainsFold predicate on the "raw_text" field.
func RawTextContainsFold(v string) predicate.Availability {
	return predicate.Availability(sql.FieldContainsFold(FieldRawText, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Availability {
	return predicate.Availability(sql.FieldLTE(FieldCreatedAt, v))
}

// HasShop applies the HasEdge predicate on the "shop" edge.
func HasShop() predicate.Availability {
	return predicate.Availability(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ShopTable, ShopColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasShopWith applies the HasEdge predicate on the "shop" edge with a given conditions (other predicates).
func HasShopWith(preds ...predicate.Shop) predicate.Availability {
	return predicate.Availability(func(s *sql.Selector) {
		step := newShopStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEmployee applies the HasEdge predicate on the "employee" edge.
func HasEmployee() predicate.Availability {
	return predicate.Availability(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, EmployeeTable, EmployeeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEmployeeWith applies the HasEdge predicate on the "employee" edge with a given conditions (other predicates).
func HasEmployeeWith(preds ...predicate.Employee) predicate.Availability {
	return predicate.Availability(func(s *sql.Selector) {
		step := newEmployeeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Availability) predicate.Availability {
	return predicate.Availability(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Availability) predicate.Availability {
	return predicate.Availability(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Availability) predicate.Availability {
	return predicate.Availability(sql.NotPredicates(p))
}
