// Code generated by ent, DO NOT EDIT.

package schedule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/betallsoph/shiftz/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldID, id))
}

// ShopID applies equality check predicate on the "shop_id" field. It's identical to ShopIDEQ.
func ShopID(v uuid.UUID) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldShopID, v))
}

// WeekStart applies equality check predicate on the "week_start" field. It's identical to WeekStartEQ.
func WeekStart(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldWeekStart, v))
}

// VariantLabel applies equality check predicate on the "variant_label" field. It's identical to VariantLabelEQ.
func VariantLabel(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldVariantLabel, v))
}

// Score applies equality check predicate on the "score" field. It's identical to ScoreEQ.
func Score(v float64) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldScore, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldCreatedAt, v))
}

// ShopIDEQ applies the EQ predicate on the "shop_id" field.
func ShopIDEQ(v uuid.UUID) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldShopID, v))
}

// ShopIDNEQ applies the NEQ predicate on the "shop_id" field.
func ShopIDNEQ(v uuid.UUID) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldShopID, v))
}

// ShopIDIn applies the In predicate on the "shop_id" field.
func ShopIDIn(vs ...uuid.UUID) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldShopID, vs...))
}

// ShopIDNotIn applies the NotIn predicate on the "shop_id" field.
func ShopIDNotIn(vs ...uuid.UUID) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldShopID, vs...))
}

// WeekStartEQ applies the EQ predicate on the "week_start" field.
func WeekStartEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldWeekStart, v))
}

// WeekStartNEQ applies the NEQ predicate on the "week_start" field.
func WeekStartNEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldWeekStart, v))
}

// WeekStartIn applies the In predicate on the "week_start" field.
func WeekStartIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldWeekStart, vs...))
}

// WeekStartNotIn applies the NotIn predicate on the "week_start" field.
func WeekStartNotIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldWeekStart, vs...))
}

// WeekStartGT applies the GT predicate on the "week_start" field.
func WeekStartGT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldWeekStart, v))
}

// WeekStartGTE applies the GTE predicate on the "week_start" field.
func WeekStartGTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldWeekStart, v))
}

// WeekStartLT applies the LT predicate on the "week_start" field.
func WeekStartLT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldWeekStart, v))
}

// WeekStartLTE applies the LTE predicate on the "week_start" field.
func WeekStartLTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldWeekStart, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldStatus, vs...))
}

// VariantLabelEQ applies the EQ predicate on the "variant_label" field.
func VariantLabelEQ(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldVariantLabel, v))
}

// VariantLabelNEQ applies the NEQ predicate on the "variant_label" field.
func VariantLabelNEQ(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldVariantLabel, v))
}

// VariantLabelIn applies the In predicate on the "variant_label" field.
func VariantLabelIn(vs ...string) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldVariantLabel, vs...))
}

// VariantLabelNotIn applies the NotIn predicate on the "variant_label" field.
func VariantLabelNotIn(vs ...string) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldVariantLabel, vs...))
}

// VariantLabelGT applies the GT predicate on the "variant_label" field.
func VariantLabelGT(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldVariantLabel, v))
}

// VariantLabelGTE applies the GTE predicate on the "variant_label" field.
func VariantLabelGTE(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldVariantLabel, v))
}

// VariantLabelLT applies the LT predicate on the "variant_label" field.
func VariantLabelLT(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldVariantLabel, v))
}

// VariantLabelLTE applies the LTE predicate on the "variant_label" field.
func VariantLabelLTE(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldVariantLabel, v))
}

// VariantLabelContains applies the Contains predicate on the "variant_label" field.
func VariantLabelContains(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldContains(FieldVariantLabel, v))
}

// VariantLabelHasPrefix applies the HasPrefix predicate on the "variant_label" field.
func VariantLabelHasPrefix(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldHasPrefix(FieldVariantLabel, v))
}

// VariantLabelHasSuffix applies the HasSuffix predicate on the "variant_label" field.
func VariantLabelHasSuffix(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldHasSuffix(FieldVariantLabel, v))
}

// VariantLabelEqualFold applies the EqualFold predicate on the "variant_label" field.
func VariantLabelEqualFold(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldEqualFold(FieldVariantLabel, v))
}

// VariantLabelContainsFold applies the ContainsFold predicate on the "variant_label" field.
func VariantLabelContainsFold(v string) predicate.Schedule {
	return predicate.Schedule(sql.FieldContainsFold(FieldVariantLabel, v))
}

// ScoreEQ applies the EQ predicate on the "score" field.
func ScoreEQ(v float64) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldScore, v))
}

// ScoreNEQ applies the NEQ predicate on the "score" field.
func ScoreNEQ(v float64) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldScore, v))
}

// ScoreIn applies the In predicate on the "score" field.
func ScoreIn(vs ...float64) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldScore, vs...))
}

// ScoreNotIn applies the NotIn predicate on the "score" field.
func ScoreNotIn(vs ...float64) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldScore, vs...))
}

// ScoreGT applies the GT predicate on the "score" field.
func ScoreGT(v float64) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldScore, v))
}

// ScoreGTE applies the GTE predicate on the "score" field.
func ScoreGTE(v float64) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldScore, v))
}

// ScoreLT applies the LT predicate on the "score" field.
func ScoreLT(v float64) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldScore, v))
}

// ScoreLTE applies the LTE predicate on the "score" field.
func ScoreLTE(v float64) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldScore, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Schedule {
	return predicate.Schedule(sql.FieldLTE(FieldCreatedAt, v))
}

// HasShop applies the HasEdge predicate on the "shop" edge.
func HasShop() predicate.Schedule {
	return predicate.Schedule(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ShopTable, ShopColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasShopWith applies the HasEdge predicate on the "shop" edge with a given conditions (other predicates).
func HasShopWith(preds ...predicate.Shop) predicate.Schedule {
	return predicate.Schedule(func(s *sql.Selector) {
		step := newShopStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAssignments applies the HasEdge predicate on the "assignments" edge.
func HasAssignments() predicate.Schedule {
	return predicate.Schedule(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AssignmentsTable, AssignmentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssignmentsWith applies the HasEdge predicate on the "assignments" edge with a given conditions (other predicates).
func HasAssignmentsWith(preds ...predicate.ScheduleAssignment) predicate.Schedule {
	return predicate.Schedule(func(s *sql.Selector) {
		step := newAssignmentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasVotes applies the HasEdge predicate on the "votes" edge.
func HasVotes() predicate.Schedule {
	return predicate.Schedule(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, VotesTable, VotesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVotesWith applies the HasEdge predicate on the "votes" edge with a given conditions (other predicates).
func HasVotesWith(preds ...predicate.ScheduleVote) predicate.Schedule {
	return predicate.Schedule(func(s *sql.Selector) {
		step := newVotesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Schedule) predicate.Schedule {
	return predicate.Schedule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Schedule) predicate.Schedule {
	return predicate.Schedule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Schedule) predicate.Schedule {
	return predicate.Schedule(sql.NotPredicates(p))
}
